### ISSUE TITLE
Maximum line width

### ISSUE THREAD

**Issue by martinheidegger** [DavidAnson/markdownlint#10]
First off: Its really great that you work on this :+1: markdown files make out a lot of our work and linting it can really help. That being said,...

One important issue that I have with markdown is if the paragraphs should be multiline or not. I am of the opinion that paragraphs should be broken after 80 characters to make sure that pull requests go through smoother (and see changes easier). Do you think it would be possible to add an optional check for the maximum line size?

**Comment by martinheidegger** [comment]
Just found the rule :+1:

**Comment by DavidAnson** [comment]
Thanks - glad I could help. ;)
