### ISSUE TITLE
Heading style parsing bug

### ISSUE THREAD

**Issue by marcospgp** [DavidAnson/markdownlint#1003]
![image](https://github.com/DavidAnson/markdownlint/assets/3464445/a3aac585-e015-4f1d-85b0-1115bc92b59f)

**Comment by DavidAnson** [comment]
You and I know that C# is a programming language, but that heading looks like it could be a closed ATX heading, so I claim the warnings are appropriate. You can escape the hash like `\#` to avoid the warnings: https://dlaa.me/markdownlint/#%25m%23%20Issue%201003%0A%0A%23%23%20Programming%20in%20C%5C%23%0A
