### ISSUE TITLE
How to configure MD012

### ISSUE THREAD

**Issue by dbolser** [DavidAnson/markdownlint#1023]
Really sorry for the basic question... For me MD012 looks too crowded, I like a lot of vertical whitespace ;-)

When I look here:
https://github.com/DavidAnson/markdownlint/blob/main/doc/md012.md#md012---multiple-consecutive-blank-lines

I see that I can increase the default maximum, but I can't work out where to do it...

Many thanks,
Dan.

**Comment by DavidAnson** [comment]
That documentation is here: https://github.com/DavidAnson/markdownlint#optionsconfig

If you are using the library through a CLI, you will probably want to create a `.markdownlint.json(c)` file instead: https://github.com/DavidAnson/markdownlint-cli2#configuration

A complete example can be found here: https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.jsonc

**Comment by dbolser** [comment]
Thank you. Where do I put that file? (Sorry!) I'm using vscode.

**Comment by DavidAnson** [comment]
That's described here: https://github.com/DavidAnson/vscode-markdownlint#markdownlintconfig

Typically the root of the project.
