### ISSUE TITLE
Provide custom rules with other rule configurations

### ISSUE THREAD

**Issue by greyscaled** [DavidAnson/markdownlint#1024]
I have a use-case in mind where my custom rule would like to see the configuration for [`proper-names`](https://github.com/DavidAnson/markdownlint/blob/main/doc/md044.md) but I'm pretty sure I cannot access that information from my rule.

In general, it seems leaky for rules to know details of other rules, and so maybe this isn't the right thing to do. However, it could also be true that a few configurations make sense for custom rules to have context on, like:

- `proper-names`
- `no-inline-html`

that may give helpful context when parsing/linting

**Comment by DavidAnson** [comment]
I agree there are some scenarios where this would be useful, but I am reluctant to allow it because it introduces interdependencies between rules (especially custom rules) and may lead to versioning problems.

**Comment by greyscaled** [comment]
> I agree there are some scenarios where this would be useful, but I am reluctant to allow it because it introduces interdependencies between rules (especially custom rules) and may lead to versioning problems.

I agree, and somewhat regretted my words once I saw them rendered (unfortunately, it sometimes takes putting things out there to arrive at the answer...): Which is to say, I think the best way to share a config (for scenarios where that makes sense) is to use `.mjs` or `.cjs` instead of `.json`, and just use a var 😆 (oops!).

```js
const properNames = ["JavaScript"]

export default {
  config: {
    "my-custom-rule": {
      properNames,
    },
    
   "proper-names": {
     names: properNames
   },
  },
}
```

In light of this, I'll close the issue!
