### ISSUE TITLE
Read from stdin

### ISSUE THREAD

**Issue by tylucaskelley** [DavidAnson/markdownlint#108]
Would be helpful for the linter to support reading markdown from stdin, as linters like ESLint allow. Currently trying to integrate the project into https://github.com/w0rp/ale

**Comment by DavidAnson** [comment]
I think the correct location for this is the CLI project, so will defer to your issue there: https://github.com/igorshubovych/markdownlint-cli/issues/32

If this project needs changes, I will make them as part of that work.

Thanks!
