### ISSUE TITLE
MD035 - Horizontal rule style: Allow multiple styles

### ISSUE THREAD

**Issue by osk** [DavidAnson/markdownlint#110]
I use markdown for creating slides with reveal.js that has the concept of vertical and horizontal slides. In my markdown I use `***` to switch between vertical ones and `---` to switch between horizontal.

When configuring my `.markdownlint.json` I expected to be able to do something like `"MD035": { "style": ["---", "***"] }` to allow for both styles but that does not work and I am forced to disable the rule.

**Comment by DavidAnson** [comment]
Because there are only three types of [thematic breaks](http://spec.commonmark.org/0.28/#thematic-breaks), all the proposed configuration would do is prevent the use of “___”. I’m not thinking the extra complexity in configuration is worth it for what seems like a pretty unusual scenario.
