### ISSUE TITLE
MD033 : allowed_elements ignoring the <kdb> element

### ISSUE THREAD

**Issue by o0Sam0o** [DavidAnson/markdownlint#1143]
Tested with other elements without issue but for some reason this one element is not being recognized.

<img width="1440" alt="Screenshot 2024-02-28 at 10 57 31 PM" src="https://github.com/DavidAnson/markdownlint/assets/3577664/7feea1b4-9f42-48a9-93cb-798c798071e7">

Markdown
```
Editor - Go Back: <kbd> ⌃ Ctrl</kbd> + <kbd>_</kbd>
```

Configuration
```
{
  "default": true,
  "MD033": {
    "allowed_elements": ["kdb"]
  }
}
```

**Comment by nschonni** [comment]
Typo "kbd" vs "kdb"

**Comment by nschonni** [comment]
Typo "kbd" vs "kdb"

**Comment by o0Sam0o** [comment]
So sorry, been at it for hours and did not see the type.

**Comment by theking2** [comment]
> So sorry, been at it for hours and did not see the typo.

Please look again 😁

(The third last line in configuration)
