### ISSUE TITLE
Formatter functionality: adjust table size to its content

### ISSUE THREAD

**Issue by jerrygreen** [DavidAnson/markdownlint#1159]
Just like prettier. Unfortunately prettier has some weird formatting style [like this](https://github.com/prettier/prettier/issues/4114).

So I prefer markdownlint. But unfortunately, it doesn’t format tables.

**Comment by DavidAnson** [comment]
Sorry, what are you asking for? The example above is a 3-item list, not a table?

**Comment by nschonni** [comment]
I think "tab size" rather than "table size". It seems to be talking about the trailing space/alignment after an ordered list start

**Comment by nschonni** [comment]
That would already be covered by [MD030](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md030---spaces-after-list-markers) already

**Comment by jerrygreen** [comment]
Sorry for confusing. The list example was just to tell that I don’t like prettier: it’s weird, just look how they format lists lol.

But markdownlint doesn’t format tables. That’s sadge.

**Comment by nschonni** [comment]
This is a terribly explained issue, if the maintainers or others can't understand what you're asking/reporting, you waste a lot of peoples time

**Comment by DavidAnson** [comment]
I still don't understand this issue or how it relates to prettier. Please show an example of the current behavior of markdownlint and explain what you would like to see instead.

**Comment by jerrygreen** [comment]
Here's what prettier does to tables:

![gif3](https://github.com/DavidAnson/markdownlint/assets/13215662/d0f23c40-ee72-4d39-b028-da49282d8775)

But `markdownlint` can't do this, unfortunately.

---

> This is a terribly explained issue

Can you please tell me what is terribly explained here:

> Formatter functionality: adjust table size to its content

My bad though, that I placed body into the issue: sorry for that. It was perfectly clear from just the title.

**Comment by DavidAnson** [comment]
Thanks for the clip! This seems to be the same request as #90, for table cells to align vertically.
