### ISSUE TITLE
MD004 overwritten by prettier

### ISSUE THREAD

**Issue by CWSites** [DavidAnson/markdownlint#1179]
I have both markdownlint and prettier configured for my project. I observed that prettier is overwriting my unordered list options (it auto changes `+` and `*` to `-`) and was wondering if there is a way to prevent this from happening?

The only thing I can think of right now is to have prettier ignore `.md` files, but this isn't ideal.

When researching prettier's approach I came across this issue which I believe is the root cause. https://github.com/prettier/prettier/issues/4251

**Comment by DavidAnson** [comment]
I'm not a prettier user and don't have recommendations for how to configure it, sorry.

**Comment by aphedges** [comment]
Prettier intentionally limits how much it can be configured, which includes providing no option to change the style of Markdown unordered lists. If you want a formatter that is less opinionated, then Prettier is probably not the tool for you.

**Comment by CWSites** [comment]
Looks like I'll just stick with adding `.md` to my `.prettierignore`.
