### ISSUE TITLE
No bare-urls when using _redirects file

### ISSUE THREAD

**Issue by MikePfunk28** [DavidAnson/markdownlint#1182]
From what I can tell it thinks my _redirects file is a markdown, when it has no extension.  Using cloudflare pages, you create a _redirects file with no extension in order to write your redirects.  I got this error and change my file accordingly, then realized it does not apply here.

Edit:
This happens for at least MD022, and MD025, probably every single one in this case.  So maybe priority isnt low, but it doesnt break anything.

MD022/blanks-around-headings: Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Below]markdownlint[MD022](https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md022.md)

MD025/single-title/single-h1: Multiple top-level headings in the same documentmarkdownlint[MD025](https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md025.md)

MD034/no-bare-urls: Bare URL usedmarkdownlint[MD034](https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md034.md)

**Comment by DavidAnson** [comment]
As a library, this package only lints the files/strings you pass in to it. If you don't want that file linted, don't pass it in.

If you are using this library via some other means (CLI), the same advice applies.
