### ISSUE TITLE
MD033 - Inline HTML Not ignoring custom HTML tags, but recognizing them as tags

### ISSUE THREAD

**Issue by tjperry07** [DavidAnson/markdownlint#1187]
This applies to multiple versions of markdownlint, so I'm asking here and using VSCode as the example. 

In VS code, it recognizes `<GitIntegration />` as a custom HTML tag. 

<img width="647" alt="Screenshot 2024-04-24 at 2 57 25 PM" src="https://github.com/DavidAnson/markdownlint/assets/5667652/dab3ff56-8f99-414e-ad4d-7542417488eb">

I added it to my settings.json to ignore that GitIntegration, but it still won't ignore it and comes up as an error. I did add iframe and img as a test, so I know it works for those, but not the custom tag I added. 

<img width="437" alt="Screenshot 2024-04-24 at 2 58 16 PM" src="https://github.com/DavidAnson/markdownlint/assets/5667652/d0d1bc85-1833-469e-8b29-1e3f04c8948c">

 My questions are:
 
 - If it recognizes as a HTML tag, why can't I treat it as such?
 - Does it only work on standard HTML?

**Comment by DavidAnson** [comment]
Your scenario works as expected in the demo project: https://dlaa.me/markdownlint/#%25m%23%20Issue%201187%0A%0A%3CGitIntegration%20%2F%3E%0A%0A%3C!--%20markdownlint-configure-file%20%7B%0A%20%22no-inline-html%22%3A%20%7B%0A%20%20%22allowed_elements%22%3A%20%5B%0A%20%20%20%22iframe%22%2C%0A%20%20%20%22img%22%2C%0A%20%20%20%22GitIntegration%22%0A%20%20%5D%0A%20%7D%0A%7D%20--%3E

My guess is that your project has a local `.markdownlint.json` (or similar) configuration file which is overriding the user/workspace settings you show.
