### ISSUE TITLE
Include filename in mardown-it objects

### ISSUE THREAD

**Issue by johntron** [DavidAnson/markdownlint#119]
I'd like to add a custom rule to check for broken links and orphaned pages in my Markdown documents. I've been using Markdown in a personal knowledgebase, and have a lot of relative paths I want to maintain.

This would be simple with the customRules API, but it doesn't provide the filename in the line-annotated markdown-it objects. I believe this could be added by modifying [this call in lintFile()](https://github.com/DavidAnson/markdownlint/blob/e938f421a9a0bbb6c3ff82d7b41c2cb227e9414e/lib/markdownlint.js#L413) and the called function, [lintContent()](https://github.com/DavidAnson/markdownlint/blob/e938f421a9a0bbb6c3ff82d7b41c2cb227e9414e/lib/markdownlint.js#L285) to accept the filename as an argument. I can submit a PR if this makes sense.

**Comment by DavidAnson** [comment]
Sure! If you want to start with a sketch, I’d be happy to review that to be sure we are on the same page.

**Comment by DavidAnson** [comment]
Thinking about this, I propose:

- Add it to `params`
- Call it `file`
- Pass it exactly as provided to `options.files`
- Use `null` when not available (strings)
- Update the README and CustomRules docs
- Update the tests

**Comment by DavidAnson** [comment]
Update: The value of `file` should be the same path already used to open it successfully. I don’t think we should commit to normalizing it.

**Comment by DavidAnson** [comment]
(Don't worry about a PR - I did this just now and will push it tomorrow after reviewing the changes.)
