### ISSUE TITLE
Allow atx_closed with setext in rule MD003

### ISSUE THREAD

**Issue by ciwchris** [DavidAnson/markdownlint#12]
Currently rule MD003 has the style option of `setext_with_atx`, but this does not allow `atx_closed` to be used with `setext`. Either adding a new style of `setext_with_atx_closed` to the rule or allowing `atx_closed` be acceptable when using the style `setext_with_atx` would be nice. Thoughts? Is there a preference one way or the other?

**Comment by DavidAnson** [comment]
My preference is for `setext_with_atx_closed` because it gives the most control and doesn't change the meaning of an existing option.
