### ISSUE TITLE
 MD040 - fenced-code-language - Fenced code blocks should have a language specified

### ISSUE THREAD

**Issue by V0d01ey** [DavidAnson/markdownlint#120]
Why the rule MD040 is introduced?

Why not using "code block" without syntax highlighting? 
It is a simple useful marking for a preformatted text without indenting.

**Comment by DavidAnson** [comment]
Correct syntax highlighting is usually clearer for the reader than without it, so this rule helps remind authors to add a language. If you do not want to do that, the rule can be disabled OR 4-space indenting can be used to create the code block instead.
