### ISSUE TITLE
Diabling rules from the front matter?

### ISSUE THREAD

**Issue by PaulWalkerUK** [DavidAnson/markdownlint#1250]
I can put `<!-- markdownlint-disable MD010 -->` in a file to disable to rule, and I realise that since it's a HTML comment it won't be rendered, but is it possible to put something in the front matter that will achieve the same? If I try put this in the front matter section, it is ignored, as is `markdownlint-disable: MD010`

**Comment by DavidAnson** [comment]
This is not supported.

**Comment by PaulWalkerUK** [comment]
No problem, thanks
