### ISSUE TITLE
MD010 no-hard-tabs rule is intended for indentation, but is triggered from any tabs

### ISSUE THREAD

**Issue by seppo498573908457** [DavidAnson/markdownlint#1287]
The [description](https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md010.md) states:
> This rule is triggered by any lines that contain hard tab characters instead of using spaces for indentation.

But in reality the rule is triggered also from tabs that are not used for indentation.

The rule should allow use of tabs in other use than indentation because it's not a forbidden character in Markdown syntax.

**Comment by DavidAnson** [comment]
The use of the word "indentation" may be misleading, but the rule name and the rest of the rule description try to communicate that its purpose is to prevent tab characters anywhere within a line. As the rationale at the bottom outlines, tab characters can be handled inconsistently and may be considered confusing and unnecessary.

https://spec.commonmark.org/0.31.2/#tabs
