### ISSUE TITLE
blanks-around-tables (like MD031 and MD032 for fences/lists)

### ISSUE THREAD

**Issue by DavidAnson** [DavidAnson/markdownlint#132]
Original issue for context: https://github.com/DavidAnson/vscode-markdownlint/issues/43

**Comment by jpluimers** [comment]
An incomplete [babelmark2 reproduction](https://johnmacfarlane.net/babelmark2/?normalize=1&text=%23+1%0A%0A-+aa%0A++%7C+key+%7C+value++%0A++%7C-----%7C-------++%0A++%7C+1+++%7C+xx++%0A++%7C+2+++%7C+yy++%0A-+bb%0A%0A++%7C+key+%7C+value++%0A++%7C-----%7C-------++%0A++%7C+1+++%7C+xx++%0A++%7C+2+++%7C+yy++%0A%0A-+cc%0A++++%7C+key+%7C+value++%0A++++%7C-----%7C-------++%0A++++%7C+1+++%7C+xx++%0A++++%7C+2+++%7C+yy++%0A-+dd%0A%0A++++%7C+key+%7C+value++%0A++++%7C-----%7C-------++%0A++++%7C+1+++%7C+xx++%0A++++%7C+2+++%7C+yy++%0A%0A-+ee) of

``` markdown
# 1

- aa
  | key | value  
  |-----|-------  
  | 1   | xx  
  | 2   | yy  
- bb

  | key | value  
  |-----|-------  
  | 1   | xx  
  | 2   | yy  

- cc
    | key | value  
    |-----|-------  
    | 1   | xx  
    | 2   | yy  
- dd

    | key | value  
    |-----|-------  
    | 1   | xx  
    | 2   | yy  

- ee
```

This was after bumping into [blackfriday](https://github.com/russross/blackfriday) rendering issues which I need to wait for our internal Go lang based git repository has been updated to the most recent blackfriday so I can check how it behaves now.

**Comment by riuson** [comment]
Example from Microsoft Team Foundation Server, rendering markdown file.

Code:
```
#### 0x0209 [1] Offset

Request:
| Field    | Type    | Meaning         |
| :------- | :------ | :-------------- |
| address  | uint8_t | Device address. |
| standard | float   | Standard value. |

Answer: empty.

#### 0x020a [1] Scale

Request:

| Field    | Type    | Meaning         |
| :------- | :------ | :-------------- |
| address  | uint8_t | Device address. |
| standard | float   | Standard value. |

Answer: empty.
```

Screenshot:
![1](https://user-images.githubusercontent.com/415202/91760730-4ecc2680-ebed-11ea-9f4c-14686eb0ba19.png)

**Comment by A-2f** [comment]
#### 0x0209 [1] Offset

Request:
| Field    | Type    | Meaning         |
| :------- | :------ | :-------------- |
| address  | uint8_t | Device address. |
| standard | float   | Standard value. |

Answer: empty.

#### 0x020a [1] Scale

Request:

| Field    | Type    | Meaning         |
| :------- | :------ | :-------------- |
| address  | uint8_t | Device address. |
| standard | float   | Standard value. |

Answer:
