### ISSUE TITLE
More documentation on how to include a custom rule, please

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [DavidAnson/markdownlint#133]
Continuing https://github.com/igorshubovych/markdownlint-cli/issues/41: there's no documentation on what structure a repository that contains a custom rule should have.

I'm working on one now and can probably fix this soon.

**Comment by DavidAnson** [comment]
The custom rule document (https://github.com/DavidAnson/markdownlint/blob/master/doc/CustomRules.md) includes a link to https://github.com/DavidAnson/markdownlint/blob/master/test/rules/package.json which should be helpful?
