### ISSUE TITLE
MD028: Add specific handling of GitHub-style callouts

### ISSUE THREAD

**Issue by volker-raschek** [DavidAnson/markdownlint#1331]
Hello everyone, 
GitHub has introduced Markdown callouts in the past. These are or have already been adopted by other VCSs - for example by [Gitea](https://github.com/go-gitea/gitea/issues/29032). In this issue are all callouts as example defined.

If I now write several callouts in a row, this violates the MD028 rule. I understand the rule and would like to keep it, but there should be an exception for a callout. 

Example of callout nesting:

```text 
# Title

> [!TIP] You can use a container image mirror [germany - west](https://example.com) to increase the download speed.

> [!WARNING]
> Please do not use the latest image, because ...
```

> [!TIP] 
> You can use a container image mirror [germany - west](https://example.com) to increase the download speed.

> [!WARNING]
> Please do not use the latest image, because ...

Please adapt MD028 to allow nested callouts by default or implement a setting to allow it generally.

**Comment by DavidAnson** [comment]
As you show, the GitHub parser does not merge consecutive block quotes, so the rationale of MD028 does not apply there. Why not disable the rule?

**Comment by DavidAnson** [comment]
I may not have been clear. What I was pointing out is that GitHub does not seem to merge consecutive block quotes that are separated by an empty line. This appears to be the case whether or not they are callouts. Rule MD028 exists to warn people about the problem of unexpected behavior for parsers that DO merge, but GitHub does not seem to be such a parser and therefore the rule does not seem necessary in that context. I propose that you can disable MD028 for GitHub scenarios regardless of whether callouts are being used.
