### ISSUE TITLE
When will micromark be available to custom rules?

### ISSUE THREAD

**Issue by rachmari** [DavidAnson/markdownlint#1332]
Hello 👋 

We have implemented a large set of custom rules in the https://github.com/github/docs project. I saw your update in https://github.com/github/docs/pull/33113 that the Markdownlint project will be moving towards micromark. We'd like to write a new custom rule that looks at Markdown tables that include Liquid templating syntax. It looks like micromark exposes more information about the delimiter row of a table than markdown-it, making the rule easier to write with the micromark parser.

I noticed that in the latest version 0.34.0, specifying the parser `parser: 'micromark'` results in an error. When will specifying `micromark` be available or when will the default be set to micromark?

Thank you!

**Comment by DavidAnson** [comment]
Not sure. :) The goal of the current release (which should be out in maybe two weeks) is to convert all the core rules over so markdown-it no longer needs to run by default. There have been a lot of rule changes to get to this point, so I anticipate a couple of regressions. The goal for the next release will probably be to surface micromark for custom rules. As part of that, I want to review the public API and maybe also expose some useful functions like the helpers library does today.

**Comment by rachmari** [comment]
Thank you for the timeline @DavidAnson 🙏

**Comment by DavidAnson** [comment]
@rachmari If you want early access, you and I could coordinate to PR any interesting rules into this repo as test cases. That may not be practical or interesting to you, but it's an opportunity for you to play around a little earlier. (I suppose you could do the same in a fork of the repo without sharing it back, too.)

**Comment by rachmari** [comment]
Hi @DavidAnson. Sorry I missed this follow up last week.

Unfortunately, our rules are often very specific to our authoring system for docs.github.com being a combination of Liquid (including custom Liquid) and Markdown. We run into several cases where we need to reimplement a rule already available in Markdownlint due to the implications of how we use Liquid to version Markdown. Unfortunately, this means most (probably all) of our custom rules wouldn't be much use to Markdownlint. However, I do have an issue to go through all of our rules and identify any that might be upstreamable.

**Comment by DavidAnson** [comment]
No worries. FYI that the first library release (not everything you want, but on the path) could go out as soon as tonight or tomorrow night if everything cooperates.

**Comment by DavidAnson** [comment]
@rachmari, `micromark` parser tokens are available to custom rules in the just-published `v0.36.0`.

Documentation: <https://github.com/DavidAnson/markdownlint/blob/main/doc/CustomRules.md>

There are a few convenience functions in `markdownlint-rule-helpers/micromark`.

**Comment by rachmari** [comment]
@DavidAnson that exciting! Thank you for letting me know. ✨ We'll get our Markdownlint version updated soon.
