### ISSUE TITLE
How to turn off the Intellisense from this extension?

### ISSUE THREAD

**Issue by yuriever** [DavidAnson/markdownlint#1335]
Thanks for this useful extension.

In most of the time I don't need the Intellisense like
<img width="621" alt="image" src="https://github.com/user-attachments/assets/fa0802e0-a553-4c95-b39b-63b3b255ca59">

Is it able to turn them off? I have read the doc but didn't find relevant settings or methods.

**Comment by DavidAnson** [comment]
That would be a VS Code setting. Extensions just make completions available and VS Code decides when to show them.
