### ISSUE TITLE
Is shared.js meant to be used externally? [Allow helper methods to be used by external rules]

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [DavidAnson/markdownlint#134]
I'm writing a custom rule, and it would be very useful to use methods such as `forEachLine` in it. Is this file part of the public API?

**Comment by DavidAnson** [comment]
No, this is not public (so not exported or documented). That was deliberate to keep the surface area down, but I will use this issue to track the suggestion to make it public.

**Comment by JoshuaKGoldberg** [comment]
In that case, +1 to making it public! I would hate to have to re-implement many of those methods externally.

You could also go with a [tsutils](https://github.com/ajafff/tsutils/) approach of separating them out... but I would personally prefer keeping them here for simplicity's sake.

**Comment by DavidAnson** [comment]
Understood! (Offhand, I think the tsutils approach may be more stable from a versioning POV so that extensions aren’t tied to a specific version of the library.)

**Comment by byzyk** [comment]
+1

While working on the custom rule I've found some of the shared helpers' methods quite handy. I had to copy/paste them but I think they should be accessible for everyone

**Comment by DavidAnson** [comment]
shared.js is now available as `markdownlint-rule-helpers`:
https://www.npmjs.com/package/markdownlint-rule-helpers
