### ISSUE TITLE
Mixing ordered and unordered lists triggers MD032

### ISSUE THREAD

**Issue by charlescoult-boeing** [DavidAnson/markdownlint#1342]
![image](https://github.com/user-attachments/assets/6d7af8c8-60fd-4455-8f4b-33cb978f3c8e)

If I want to have a bulleted list mixed in with a numbered list (unordered sub-items of an item in an ordered list), the linter sees them as two separate lists. Is it possible to configure the linter to allow mixed lists so that I don't have to turn of MD032?

**Comment by nschonni** [comment]
The unoreded list doesn't look like it's indented enough. It would need to start at least 3 spaces in, if it's supposed to be part of the list time

**Comment by DavidAnson** [comment]
Thanks, Nick. @charlescoult-boring, the relevant part of the specification is here (especially examples 255-258): https://spec.commonmark.org/0.31.2/#list-items
