### ISSUE TITLE
Should shared.js' `createTokenCache` not recreate an existing cache?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [DavidAnson/markdownlint#135]
_Context: I'm writing a custom rule and would like to use the `forEachLine` method (#134). That method uses the `tokenCache` created by `createTokenCache`._

If it just so happens that a custom rule's version of markdownlint is different from the package's, then `forEachLine` will crash as its version of `tokenCache` won't exist. The solution is to manually call `shared.createTokenCache()` in the rule... but that seems wasteful for the general case of everyone using the same markdownlint version.

**Comment by DavidAnson** [comment]
Per #134, these functions are not public at present (partly due to challenges like this), so this scenario is not one that should be encountered.
