### ISSUE TITLE
This GitHub repo's Wiki should be disabled

### ISSUE THREAD

**Issue by its-miroma** [DavidAnson/markdownlint#1373]
The Wiki tab (<https://github.com/DavidAnson/markdownlint/wiki>) does not currently hold any useful information, instead it seems to be home to spam messages/edits, since it also seems to be publicly editable.

Please disable the wiki from the repo's settings. See <https://docs.github.com/en/communities/documenting-your-project-with-wikis/disabling-wikis>.

**Comment by DavidAnson** [comment]
Thank you! GitHub's default behavior to enable wikis and make them writable by everyone (seemingly without notice to the project maintainer?) seems wrong to me.

**Comment by its-miroma** [comment]
Couldn't agree more—forcefully and/or silently turning on any features will probably not make me enjoy them.
