### ISSUE TITLE
How do we ignore files?

### ISSUE THREAD

**Issue by ardauzan** [DavidAnson/markdownlint#1377]
I have been trying to configure markdownlint via the dot files. No matter what I do, .markdownlintignore is not respected. Can you help me? Also sorry if this is a stupid thing to ask but I have been trying to solve this issue for 4 hours now...

**Comment by DavidAnson** [comment]
This project is a library that lints exactly the files you pass to it via code. I'm guessing you are using one of the CLIs or the VS Code extension? Please specify which and how you are using it.
