### ISSUE TITLE
MD001 fails to detect <hN> tag

### ISSUE THREAD

**Issue by xuhdev** [DavidAnson/markdownlint#1390]
markdownlint-cli2 reports error for the following markdown file:

```md
# H1

<h2>H2</h2>

### H3

```

```
a.md:5 MD001/heading-increment Heading levels should only increment by one level at a time [Expected: h2; Actual: h3]
```

**Comment by DavidAnson** [comment]
This rule (along with almost all the rules) does not attempt to reconcile Markdown structure with embedded HTML elements. (In fact, using HTML is discouraged per rule MD033.) There are many ways a document could alternate between Markdown and HTML and it is not a goal of this tool to try to make sense of all that.
