### ISSUE TITLE
Publish npm Package with Provenance Statement

### ISSUE THREAD

**Issue by dsanders11** [DavidAnson/markdownlint#1408]
[Provenance statements](https://github.blog/security/supply-chain-security/introducing-npm-package-provenance/) are a nice way to increase confidence in the integrity of published npm packages. It would be great if this package adopted the practice.

A prerequisite to publishing with provenance statements would be to move the publish step to GitHub Actions. Happy to help with guidance there if you'd like any (regarding the workflow or setting up the npm token secret for publishing).

**Comment by DavidAnson** [comment]
https://dlaa.me/blog/post/npmprovenance

**Comment by dsanders11** [comment]
Thanks for linking your blog post! Nice to see that you've considered it and shared your thoughts on it. Personally, I still believe there's value in it, so I hope you'll reconsider your stance in the future. 🙂

For what it's worth, regarding the bypassing 2FA concerns (very valid) Electron has been using a solution for that problem for quite some time now with [Continuous Factor Auth (CFA)](https://github.com/continuousauth/web). It's not a good fit for every project, but it has worked well for us and allows us to publish with a 2FA enabled account while also allowing a number of maintainers to provide the 2FA token without any of them having credentials for the publishing account.

**Comment by DavidAnson** [comment]
If any of the claims I make are wrong, I am happy to learn why and reevaluate. :) But if they're right, what's the value of doing this?
