### ISSUE TITLE
Disable link checking for GitHub Alerts

### ISSUE THREAD

**Issue by gabeseltzer** [DavidAnson/markdownlint#1418]
GitHub uses the following syntax for ["Alerts"](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts):

```markdown
> [!NOTE]
> Useful information that users should know, even when skimming content.
```

markdownlint will flag the `[!NOTE]` as a link, and will tell you `No link definition found: '!NOTE'(link.no-such-reference)`. Can we turn this off for the keywords that make up alerts? Specifically: 
* `[!NOTE]`
* `[!TIP]`
* `[!IMPORTANT]`
* `[!WARNING]`
* `[!CAUTION]`

**Comment by DavidAnson** [comment]
The error error message you show above is not coming from this tool. You can see that your example produces no violations: https://dlaa.me/markdownlint/#%25m%23%20Issue%201418%0A%0A%3E%20%5B!NOTE%5D%0A%3E%20Useful%20information%0A

It looks like the message you show is coming from VS Code instead:  https://stackoverflow.com/questions/75252767/have-vscode-ignore-specific-reference-links-in-markdown-validation

**Comment by gabeseltzer** [comment]
Ah, thanks and sorry for the trouble! For those wondering, it looks like there's a follow-on ticket for VSCode here: https://github.com/microsoft/vscode-markdown-languageservice/issues/152
