### ISSUE TITLE
MD051 - Support alternate heading link algorithms

### ISSUE THREAD

**Issue by otteydw** [DavidAnson/markdownlint#1424]
My team primarily uses Bitbucket which has an alternate algorithm for linking to headings. In the case of Bitbucket, they want the linked headings to begin with `#markdown-header-` such that a link to the header "My Header" would need to be `[my header](#markdown-header-my-header)`.

I don't know if there are other algorithms around (and I truly wish that Bitbucket did not use this uncommon algorithm), I was wondering if an option could be added to rule MD051 that supported Bitbucket's algorithm specifically? Or maybe an option to allow us to specify a header prefix that we should require for the link fragment to be valid?

**Comment by DavidAnson** [comment]
Duplicate of https://github.com/DavidAnson/markdownlint/issues/547#issuecomment-1361218474

I'll revisit this soon.

**Comment by otteydw** [comment]
Ugh, I swear I did search for it. I'm not sure how I missed that.  Thank you.

**Comment by otteydw** [comment]
Ugh, I swear I did search for it. I'm not sure how I missed that. Thank you.

**Comment by otteydw** [comment]
Sorry, I'm actually not sure if I should have closed this or not.  Please re-open if you need that for tracking.

**Comment by DavidAnson** [comment]
It's cool. :) I have a private TODO list I use for tracking.
