### ISSUE TITLE
Jun-marksown

### ISSUE THREAD

**Issue by ijunxyz123** [DavidAnson/markdownlint#1433]
> 36adb5e4d2932cb5fd39beee48f773ec647ce185
> 
> Damarcus Jones Sr  

 _Originally posted by @ijunxyz123 in [36adb5e](https://github.com/DavidAnson/markdownlint/commit/36adb5e4d2932cb5fd39beee48f773ec647ce185#r149703406)_

**Comment by DavidAnson** [comment]
SPAM
