### ISSUE TITLE
Can't preview local image when coordinate with "Markdown All in One" 

### ISSUE THREAD

**Issue by ChildishChange** [DavidAnson/markdownlint#147]
I installed this two extensions below for markdown writing, both of them are enabled.
![image](https://user-images.githubusercontent.com/8814510/46649844-28eaa280-cbcd-11e8-88c3-aa5714d1256a.png)

When inserting **local** image, the preview page just can't load the image.
(It works well when inserting picture url :) )

![_20181009140816](https://user-images.githubusercontent.com/8814510/46649801-048ec600-cbcd-11e8-9e81-d2a2d6ef9aee.png)

I disabled markdownlint and reload vs code, the preview page just can load the local image.

**Comment by ChildishChange** [comment]
I tried again. 
It works well (successfully loaded local and internet images) when disabling either markdown all in one or markdownlint.

However, if I disabled markdown all in one, the preview page just can't render Latex :(

**Comment by DavidAnson** [comment]
What you describe about images not loading sounds like this behavior in the documentation: https://code.visualstudio.com/docs/languages/markdown#_markdown-preview-security

Could you please have a look to see if it is related?

The markdownlint extension does not do anything to modify the document and it is not involved with the Preview window, so I do not think it should be part of this problem.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ChildishChange** [comment]
Thanks for your warming help :) !

I tried but it seems not related to the preview security settings :(

I also raised issue under all-in-one repo.
https://github.com/neilsustc/vscode-markdown/issues/296

They seem to have some clues now :)

Thanks again!

**Comment by DavidAnson** [comment]
Closed as suggested by https://github.com/neilsustc/vscode-markdown/issues/296#issuecomment-428305193

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
