### ISSUE TITLE
MD010 - Hard tabs (go use tabs in default)

### ISSUE THREAD

**Issue by charrywanganthony** [DavidAnson/markdownlint#149]
when i use go code block, it should not report error

![go-markdownlint-tabs](https://github.com/charrywanganthony/MarkdownPhotos/blob/master/Photos/2018-10-11%2011-34-31.png?raw=true)

**Comment by DavidAnson** [comment]
To allow tabs inside code blocks, set the `code_blocks` parameter of `MD010` to `false`: 
https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md010
