### ISSUE TITLE
CommonMark mention

### ISSUE THREAD

**Issue by igorshubovych** [DavidAnson/markdownlint#15]
Currently README.md call markdownlint `A Node.js style checker and lint tool for Markdown files`.

Should CommonMark be mentioned too?

As far as I understood it covers CommonMark pretty good. CommonMark nowadays is becoming a de-facto standard, because it has spec unlike Markdown. I see that you included link to this spec in README.md.

**Comment by DavidAnson** [comment]
Makes sense! As you say, the `markdown-it` parser is CommonMark-compliant. Because CommonMark is a dialect/subset of Markdown, maybe something like the following:

> A Node.js style checker and lint tool for Markdown/CommonMark files.

**Comment by igorshubovych** [comment]
Well, honestly I am not sure. Need to double check.

**Comment by igorshubovych** [comment]
http://talk.commonmark.org/t/is-commonmark-really-markdown-compatible/540

**Comment by DavidAnson** [comment]
Lots of strong opinions there. :) My proposal above deliberately does not take sides. "Markdown/CommonMark" suggests that both are supported without saying one is better or a subset, etc..

Until the day we find a rule that needs to behave differently, this may be good enough.

**Comment by DavidAnson** [comment]
BTW, the title on the page http://commonmark.org/ says the following which is what I based my phrase "dialect/subset" on:
> CommonMark - A strongly defined, highly compatible specification of Markdown

**Comment by igorshubovych** [comment]
> CommonMark - A strongly defined, highly compatible specification of Markdown

Then it should be ok to have Markdown/CommonMark

**Comment by DavidAnson** [comment]
Great - I'll make the update soon.
