### ISSUE TITLE
YAML Front Matter Regex Not Handling Pandoc Mixed Fencing

### ISSUE THREAD

**Issue by jason-dour** [DavidAnson/markdownlint#153]
Right or wrong, Pandoc promotes the use of mixed fencing on YAML Front Matter.  Throughout their documentation, they promote the following front matter style:

``` YAML
---
title: Blah
yadda: Foo
...
```

Which triggers rule MD041 to not recognize the front matter.  As I dove in further, I don't think it is MD041 itself being triggered (no amount of options settings of `front_matter_title` made a difference), but the recognition of the front matter as existing thanks to:

`shared.js:9-10`
``` javascript
// Regular expression for matching common front matter (YAML and TOML)
module.exports.frontMatterRe = /^(---|\+\+\+)$[^]*?^\1$(\r\n|\r|\n)/m;
```

Whereas, if I tweak that regex to be the following, Pandoc front matter is recognized appropriately:

`shared.js:9-10`
``` javascript
// Regular expression for matching common front matter (YAML and TOML)
module.exports.frontMatterRe = /^([-]{3}|[+]{3}|[.]{3})$[\s\S]+^([-]{3}|[+]{3}|[.]{3})$/m;
```

I don't know if Pandoc YAML FM is important enough to modify this in your release codebase.  Just figured I'd share what I found.  Thanks.

**Comment by DavidAnson** [comment]
Why, Pandoc, why?

**Comment by jason-dour** [comment]
I don't know.  I don't make the _"standards"_; I just get impacted by them.  😄
