### ISSUE TITLE
Erroneously marks 4 space indentations as warning for unordered lists

### ISSUE THREAD

**Issue by poshcodebear** [DavidAnson/markdownlint#158]
When working with unordered lists, if I'm using 4 space indentations (as per the spec), it marks them as invalid with ```[markdownlint] MD007/ul-indent: Unordered list indentation [Expected: 2; Actual: 4]```.

Example:

```markdown
- Base item
    - Indented item
```
Ordered lists, on the other hand, don't get warnings for either 2 or 4 space indentations.

Since 4 spaces is what's specified in the official spec, and it's more that many implementations let you do 2 spaces, I feel this should be corrected to allow 4 spaces without warnings.

**Comment by DavidAnson** [comment]
Please see #141 for an explanation of why I don’t see a good way to make everyone happy here.

**Comment by poshcodebear** [comment]
I still think adding a note to the tooltip that this is configurable could help, but either way, thank you for pointing me down that avenue.

**Comment by DavidAnson** [comment]
Follow-up: I've done this in https://github.com/DavidAnson/vscode-markdownlint/commit/33ee19a243cba0cee96f01075a92a524504b465a
