### ISSUE TITLE
MD033 for <details> <summary>

### ISSUE THREAD

**Issue by OzakIOne** [DavidAnson/markdownlint#161]
I wrote a guide in markdown and i did a FAQ , but the problem was i needed to hide it and the only solution was to use inline html elements such as <details> and <summary> but it detects it  as MD033, it should have exeptions sometimes when there is no better way to do it with html

**Comment by DavidAnson** [comment]
The `allowed_elements` property of MD033 allows you to ignore a list of elements for cases like this. More info: https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md033---inline-html
