### ISSUE TITLE
default config for a repo

### ISSUE THREAD

**Issue by ksnyde** [DavidAnson/markdownlint#162]
Possibly this is a documentation issue but I want a way to add a config file to the root of one of my repo to ignore certain rules and add others. In the docs I see a way to change rules with **frontmatter** and **HTML comments** but not as a default config file. 

> Note: there is some reference to an "options" object but I have on idea what file naming convention to use to have this get picked up.

**Comment by DavidAnson** [comment]
This package provides a function that you call with whatever input you choose. If you want to standardize on a configuration file  of a particular name in a particular place when calling it, that is under your control.

That said, if you are (also) using `markdownlint-cli` or `vscode-markdownlint`,  both automatically apply any rule configuration you have in a file named `.markdownlint.json`.

Here’s some documentation about that: https://github.com/DavidAnson/vscode-markdownlint/blob/master/README.md#markdownlintconfig

And an example: https://github.com/DavidAnson/vscode-markdownlint/blob/master/.markdownlint.json
