### ISSUE TITLE
How to use MD013 (line length) for headings only

### ISSUE THREAD

**Issue by amimas** [DavidAnson/markdownlint#170]
I like the "line length" rule coming from MD013, but I want to enforce shorter length for headings only. For example: headings should not be more than 30 characters.

https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md013---line-length

I can't seem to figure out how to set this configuration. If this does not exist at the moment, do you think it can be enhanced to allow this configuration? I don't want to enforce this rule on paragraphs as most users would be using a modern IDE which can wrap lines very easily. Enforcing this rule on paragraph could be challenging too (from an adoption perspective).

**Comment by DavidAnson** [comment]
This would be a new feature. I’ll look into it soon.

**Comment by michaeltlombardi** [comment]
This issue is marked `fixed in next` but doesn't seem to be referenced in a commit - I'm looking to do essentially the same but only for lines of code and headings. I explicitly do _not_ want to check line lengths inside of normal body copy.
