### ISSUE TITLE
Create a "markdownlint" binary that's invokable as a shell command

### ISSUE THREAD

**Issue by nija-at** [DavidAnson/markdownlint#178]
A `markdownlint` binary that,
* with no parameters runs on all markdown files found recursively from the current folder
* chooses the set of files to run against based on parameters
* Recognises and uses .markdown.(json|yaml), if it's present

**Comment by nschonni** [comment]
There is already a CLI project mentioned in the README https://github.com/igorshubovych/markdownlint-cli

**Comment by DavidAnson** [comment]
I link to `markdownlint-cli` at the top of the README - I think that does everything you want?

https://github.com/igorshubovych/markdownlint-cli

**Comment by nija-at** [comment]
Didn't realize there was another tool. I was expecting it as part of the same repo.

That satisfies what I'm looking for. Thanks!
