### ISSUE TITLE
MD033 being flagged for elemenents with `_`

### ISSUE THREAD

**Issue by nschonni** [DavidAnson/markdownlint#188]
I believe this wasn't the case before 0.14. Elements like <parameter_name> do not need to be escaped because markdown doesn't recognize strings with `_` as elmements. Maybe due to the new Email handling since that added an `_` to a regex in the rule. This also doesn't so in VS Code as an issue, just from the Markdown-CLI 0.16.0

**Comment by DavidAnson** [comment]
Valid, but picky. :)

Reproduction: https://dlaa.me/markdownlint/#%25m%23%20Heading%0A%0A%3Cabc_def%2F%3E%0A

I believe this comes from the new custom detection (for better accuracy) vs. letting the parser handle this.
