### ISSUE TITLE
It would be nice if MD002 could be configured

### ISSUE THREAD

**Issue by GarthDB** [DavidAnson/markdownlint#19]
When I use markdown files in a static site generator I usually have a template use the title as an h1; I'd like to configure MD002 to check if an h2 is used first.

**Comment by DavidAnson** [comment]
Seems reasonable, but it plays havoc with the name of the rule, first-header-h1. :) I may introduce an alias for this rule so it's less confusing when used with an h2. Thanks!

**Comment by GarthDB** [comment]
Sounds good.

**Comment by DavidAnson** [comment]
I decided not to alias the name, but to normalize the description a bit. I also changed the MD025 and MD041 rules in a similar manner.

**Comment by GarthDB** [comment]
Ah, excellent! Thanks @DavidAnson!

**Comment by GarthDB** [comment]
What's the release schedule like? I'd like to make a pull request to update it in [atom-linter-node-markdownlint](https://github.com/josa42/atom-linter-node-markdownlint).

**Comment by DavidAnson** [comment]
I published version `0.2.0` a few minutes ago. :)

**Comment by GarthDB** [comment]
I just made a pull request to the [ruby implementation](https://github.com/mivok/markdownlint/) mirroring these changes; hopefully, it's accepted.

https://github.com/mivok/markdownlint/pull/142
