### ISSUE TITLE
Enable linting code blocks in Markdown content with external tools like eslint and flake8

### ISSUE THREAD

**Issue by proofit404** [DavidAnson/markdownlint#197]
Hi, thanks for an awesome package!

I wonder if there is any possibility to integrate somehow `markdownlint` with external tools like `eslint`, `flake8` or `rubocop` to lint code examples written in the markdown document?

No pressure at all, I'm just asking if there is an internal API available I can use to write such plugins myself.

Best regards, Artem.

**Comment by DavidAnson** [comment]
Yes, that should be possible!

There are examples of calling the `markdownlint` API directly, as well as from Grunt and Gulp in the README: https://github.com/DavidAnson/markdownlint/blob/master/README.md#usage

If you can get the other tool(s) to flag chunks of Markdown content they encounter, you can lint that as `strings` input like in the examples above.

**Comment by DavidAnson** [comment]
Oh, wait, you are asking about the reverse! That would take a bit of work on my part. I’ll look into this for a future release. Thanks!

**Comment by proofit404** [comment]
Cool! Thanks!

**Comment by DavidAnson** [comment]
I realized the best way to do this was with a custom rule (vs. modifying the library as I'd first considered). So I wrote a custom rule example that runs ESLint against any JavaScript code fences in Markdown. There's a lot more this rule could do (and I may expand upon it in the future), but it shows how to accomplish the task in a reasonable manner and you should be able to translate it to other tools pretty easily. Hope it helps!

**Comment by DavidAnson** [comment]
Direct link from the commit above: https://github.com/DavidAnson/markdownlint/blob/4d11e60cfe2cc50e36445bb1aaaf209ea063845e/test/rules/lint-javascript.js
