### ISSUE TITLE
MD018 triggered inside HTML pre/code block

### ISSUE THREAD

**Issue by nschonni** [DavidAnson/markdownlint#198]
Looks like `#` inside pre/code blocks still get picked up as Markdown headers
EX: 
```md
<pre><code>
#Place the cluster in maintenance mode
sudo crm configure property maintenance-mode=true

#Create Pacemaker resources for the Azure agent
sudo crm configure primitive rsc_azure-events ocf:heartbeat:azure-events op monitor interval=10s
sudo crm configure clone cln_azure-events rsc_azure-events

#Take the cluster out of maintenance mode
sudo crm configure property maintenance-mode=false
</code></pre>
```
From https://github.com/MicrosoftDocs/azure-docs/blob/ceeac2e6be7a281f128a590e978c43415e09070f/articles/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker.md

**Comment by DavidAnson** [comment]
That’s not a Markdown code block - it’s an HTML code block. Is that deliberate? If so, why? I don’t think there’s precedent for markdownlint to recognize HTML structures.

**Comment by nschonni** [comment]
Not sure why they decided to use a manual pre/code block here, but I would have thought it would treat it similarly to a code fence. I know this style can be required inside tables, since code fences don't always work properly there.

**Comment by DavidAnson** [comment]
My current thinking is that this is not proper Markdown and represents an anti-pattern. I’m not looking to maintain an HTML parser/linter in addition to this one - which would seem necessary to catch cases like this or to find spaces inside a bold or italics or link tag (all of which are rules today which someone might reasonably be expected to extend to HTML). Unless  someone points to widespread use of this pattern that seems justified, my thinking is to close this issue as being outside the scope of the project.

I hope that reasoning makes sense!

**Comment by nschonni** [comment]
Yup, it's a weird edge case. Looking at some of the other blocks, it looks like they're using this style to use `<b>` tags to add emphasis to text inside the blocks. I don't think that works inside the regular code fences.
I could see treating these as code fences, but I can see that would have problems with other rules (EX: adding language to the code fence)

**Comment by DavidAnson** [comment]
Yep, there is already a rule saying not to include HTML elements in your Markdown; supporting this would be in defiance of that!

**Comment by nschonni** [comment]
I'll see if I can give some other examples besides the `<b>` thing here. Markdown tables commonly need HTML for things like code fences, lists, line breaks anyway, so that might be a better test case. That wouldn't apply to the MD018 rule though

**Comment by DavidAnson** [comment]
Closing for now.
