### ISSUE TITLE
Deprecated rules are not identified as such in the root README.md

### ISSUE THREAD

**Issue by travisclagrone** [DavidAnson/markdownlint#203]
## Description

Deprecated rules (e.g. [MD002]) are not identified as such in the [Rules / Aliases] section of the root [README.md].

## Discussion

Considering that the [Rules / Aliases] section is an otherwise comprehensive list on the "front page" so-to-speak, the lack of deprecation identification there runs the risk of perpetuating deprecated rules by way of users quick-referencing this list (despite any deprecation notice in the full [Rules.md]). Obversely, considering that the [Rules / Aliases] section *is* otherwise able to serve as a "quick reference" for the full [Rules.md] documentation, it could be made even more helpful by easily identifying which rules are deprecated.

## Proposal

For each rule that is deprecated, ~~strike through~~ the corresponding list item in [Rules / Aliases].

[README.md]:
<https://github.com/DavidAnson/markdownlint/blob/master/README.md>
'markdownlint'

[Rules / Aliases]:
<https://github.com/DavidAnson/markdownlint/blob/master/README.md#rules--aliases>

[Rules.md]:
<https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md>
'Rules'

[MD002]:
<https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md002---first-heading-should-be-a-top-level-heading>
'MD002 - First heading should be a top level heading'

**Comment by DavidAnson** [comment]
Agreed. Your PR looks good and I should be able to complete it later after a review. Thanks!
