### ISSUE TITLE
Unordered sublist with different symbol

### ISSUE THREAD

**Issue by lampo808** [DavidAnson/markdownlint#21]
When writing an unordered sublist I like to use a different list symbol rather than the same used for the main list:

    - item 1
    - item 2
      + subitem 1
      + subitem 2

In my opinion this should be fine, but I get a MD004 warning instead. I suggest to modify the linter not to raise a warning in this case.

**Comment by DavidAnson** [comment]
Thinking about this briefly, I'd want to add a new value for the `style` parameter named something like `differentiated` which would behave like `consistent`, but only check within each level of a list. For simplicity, I probably would not try to ensure consistency across lists.

**Comment by lampo808** [comment]
Yes, better keep each list on its own. Thanks.

**Comment by DavidAnson** [comment]
After playing with both implementations, it ended up being much simpler to enforce a consistent style for each level across all lists in the document. So I went with that. :)

**Comment by tomByrer** [comment]
> enforce a consistent style for each level across all lists in the document

Cool, I was hoping on that!
