### ISSUE TITLE
Rule MD032 is not correctly checked

### ISSUE THREAD

**Issue by mebeim** [DavidAnson/markdownlint#211]
Rule MD032 does not seem to be correctly enforced when text is present on a line immediately *following* a list. See the example below.

File `test.md`:

    # Title

    * This is
    not okay

File `test.js`:

    const markdownlint = require("markdownlint");

    markdownlint({"files": ["test.md"]}, (_, res) => {
        console.log(res);
    });

Output:

    Results { 'test.md': [] }

Expected output:

    // Something like this:
    Results {
        'test.md': [
            {
                lineNumber: 4,
                ruleNames: [Array],
                ruleDescription: 'Lists should be surrounded by blank lines',
                // ...
            }
        ]
    }
    

---

Node version: 12.7.0
npm version: 6.10.2
`markdownlint` version: 0.16.0

**Comment by DavidAnson** [comment]
Your example is valid syntax for a list with a single item: https://dlaa.me/markdownlint/#%25m%23%20Title%0A%0A*%20This%20is%0Anot%20okay%0A

I believe this is called “lazy continuation” - here it is in the specification: https://spec.commonmark.org/0.29/#lazy-continuation-line

As such, I believe the current behavior is correct.

**Comment by mebeim** [comment]
Thanks for the quick response. You're right, the spec allows this for list items. I got confused by the last example for MD032 in `Rules.md`:

> Note: **List items without hanging indents are a violation of this rule**; list items with hanging indents are okay:
>
>     * This is
>     not okay
>
>     * This is
>       okay

Should this be reworded to be clearer?

**Comment by DavidAnson** [comment]
Ugh, yes! That section came from the original Ruby implementation and seems wrong for CommonMark. I will remove it entirely - or accept a PR that does so.

Sorry about that!
