### ISSUE TITLE
Extends does not work for subfolders (possible CLI issue)

### ISSUE THREAD

**Issue by TheJaredWilcurt** [DavidAnson/markdownlint#219]
# YAML configs

✔️ YAML next to file works

```yml
extends: file.yml
```

✔️ JSON next to file works

```yml
extends: file.json
```

❌ `./` subfolder YAML does not work

```yml
extends: ./node_modules/folder/file.yml
```

❌ `./` subfolder JSON does not work

```yml
extends: ./node_modules/folder/file.json
```

❌ Relative subfolder YAML does not work

```yml
extends: node_modules/folder/file.yml
```

❌ Relative subfolder JSON does not work

```yml
extends: node_modules/folder/file.json
```

# JSON configs

✔️ YAML next to file works

```json
{
  "extends": "file.yml"
}
```

✔️ JSON next to file works

```json
{
  "extends": "file.json"
}
```

❌ `./` subfolder YAML does not work

```json
{
  "extends": "./node_modules/folder/file.yml"
}
```

❌ `./` subfolder JSON does not work

```json
{
  "extends": "./node_modules/folder/file.json"
}
```

❌ Relative subfolder YAML does not work

```json
{
  "extends": "node_modules/folder/file.yml"
}
```

❌ Relative subfolder JSON does not work

```json
{
  "extends": "node_modules/folder/file.json"
}
```

**Comment by TheJaredWilcurt** [comment]
I updated this repo:

* https://github.com/TheJaredWilcurt/cole-cat

So you just need to do

1. `git clone https://github.com/TheJaredWilcurt/cole-cat.git`
1. `cd cole-cat`
1. `npm install`
1. `npm run markdown-lint`

Should be able to see it not ignoring `node_modules`, and not extending the rules.

**Comment by DavidAnson** [comment]
Thank you!

**Comment by DavidAnson** [comment]
@TheJaredWilcurt:

- The problem of the CLI not ignoring `node_modules` is because of the single quotes around the path which get interpreted as part of the path. Removing them gives the expected behavior.
- The problem of the CLI not extending the rules is due to a typo in the file path of the root config file. Fixing that gives the expected behavior.
  - It's possible that's what was responsible for the original "extends doesn't work" issue as well - please double-check?

Here's a diff with the two change I made to the above repo on Windows to get this working:

```diff
diff --git a/.markdown-lint.yml b/.markdown-lint.yml
index 930040d..eb86918 100644
--- a/.markdown-lint.yml
+++ b/.markdown-lint.yml
@@ -1,5 +1,5 @@
 ---
-extends: ./node_modules/tjw-markdown-lint-rules/tjwmarkdownlint.yml
+extends: ./node_modules/tjw-markdownlint-rules/tjwmarkdownlint.yml
 # Override the proper-names rule to enforce capitalization of your project's name and other proper nouns
 proper-names:
   names:
diff --git a/package.json b/package.json
index d1285b4..e19a19c 100644
--- a/package.json
+++ b/package.json
@@ -7,7 +7,7 @@
     "start": "node node_modules/npm-free-server/dist/server.js",
     "lint": "eslint components/**/*.vue",
     "fix": "npm run lint -- --fix",
-    "markdown-lint": "markdownlint -i './node_modules/**/*' --config ./.markdown-lint.yml ./**/*.md"
+    "markdown-lint": "markdownlint -i ./node_modules/**/* --config ./.markdown-lint.yml ./**/*.md"
   },
   "license": "MIT",
   "devDependencies": {
```

**Comment by TheJaredWilcurt** [comment]
The ignore being double quotes was really dumb and I should have caught. I originally had no quotes, then it wouldn't work in Linux, so I added single quotes and it worked in linux but not Windows. Anyways, double quotes works for that!

And yeah, the typo thing is really dumb too. Thanks for catching that.

**Comment by DavidAnson** [comment]
Glad this had a happy ending! :)
