### ISSUE TITLE
Trouble with character encoding in the Table of Contents

### ISSUE THREAD

**Issue by Troupal** [DavidAnson/markdownlint#225]
Hello !

I am a French user and I write my titles with characters like ***é,à,Œ,î,î,etc.***. And, when I use the module **Table of Contents**, the titles are converted with a string like ***%c3%a9***. So I can't click and follow the link because the titles are not the same, and I can't change the **ToC** either because it's automatically changing itself.

_Could you (and how) fix this?_

**Comment by DavidAnson** [comment]
The “table of contents“ module is not part of this project. I do not have experience with it, so I don’t think I can help with that problem.

**Comment by DavidAnson** [comment]
Closing as an external issue.
