### ISSUE TITLE
MD020 triggers for single-character headings

### ISSUE THREAD

**Issue by mfederczuk** [DavidAnson/markdownlint#229]
The rule [MD020](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md020) triggers for headings that are just one character long.  
![example1](https://user-images.githubusercontent.com/14075939/67204683-5be58a00-f40e-11e9-8d9b-5774c360623b.png)

For some reason the rule does not get triggered when the character is a hash, though.  
![example2](https://user-images.githubusercontent.com/14075939/67205090-3efd8680-f40f-11e9-8fa9-e058b1dec0e8.png)  
![example3](https://user-images.githubusercontent.com/14075939/67205187-779d6000-f40f-11e9-88de-ff97e7019bb6.png)

**Comment by DavidAnson** [comment]
I’m not seeing this problem in the library itself: https://dlaa.me/markdownlint/#%25m%23%20A%20%23%0A%0A%23%23%20B%20%23%23%0A

Could you please double check that you are running the latest version of the VS Code extension? (I’ll also check myself later when I’m able to.)

**Comment by DavidAnson** [comment]
Wait, that’s wrong. My example link does demonstrate it, but it didn’t when I  built it interactively. There definitely seems to be a bug here. I will look into it soon. Thank you!
