### ISSUE TITLE
MD030 (list-marker-space) fires on list marker with no text behind it

### ISSUE THREAD

**Issue by rpdelaney** [DavidAnson/markdownlint#235]
My use case is from a github issue template:

```
## Steps to Reproduce the Problem

1.
1.
1.
```

This suggests numbered lists for the repro steps. However, markdownlint throws `MD030/list-marker-space` on this. Of course, adding white space after the list marker gives `MD009/no-trailing-spaces`.

**Comment by DavidAnson** [comment]
This is a pretty specialized scenario, but I don’t see a problem with supporting it offhand. Thanks for the suggestion!

https://dlaa.me/markdownlint/#%25m%23%20Issue%20235%0A%0A%23%23%20Steps%0A%0A1.%0A1.%0A1.%0A%0A%23%23%20Items%0A%0A*%0A*%0A*%0A
