### ISSUE TITLE
Parsing of markdownlintrc fails because of comments

### ISSUE THREAD

**Issue by Stanzilla** [DavidAnson/markdownlint#239]
Currently when run via the CLI as `npx markdownlint src/ --config .markdownlintrc` the script fails with 

```
Cannot read or parse config file .markdownlintrc: Unable to parse '.markdownlintrc'; Unexpected token / in JSON at position 169; missed comma between flow collection entries at line 10, column 12:
        "MD046": false,
               ^
```

is there a way this could be fixed by switching to a JSON5 compatible parser or maybe just strip them out instead of failing?

**Comment by DavidAnson** [comment]
This is an issue with the CLI project which is found here: https://github.com/igorshubovych/markdownlint-cli

I can’t move this issue, so will ask you to please open one there instead. When doing so, please include the .markdownlintrc file you are using - the details above aren’t clearly a comment issue to me.

Thanks!

**Comment by Stanzilla** [comment]
https://github.com/igorshubovych/markdownlint-cli/issues/72
