### ISSUE TITLE
Request: No empty link rule

### ISSUE THREAD

**Issue by aubergine10** [DavidAnson/markdownlint#24]
When working on large documents, sometimes placeholder links are added with the expectation they will be defined later. For example:

```
[foo]()

[bar](#)
```

Such links are somewhat difficult to spot in big documents. The rule would warn against those patterns.

Note: A `#` link is sometimes used to jump to top of document, however similar effect can be achieved by linking to main heading or a html anchor tag.

**Comment by DavidAnson** [comment]
A bit tangential, but this is starting to veer pretty close to an existing `check-pages` feature:
https://github.com/DavidAnson/check-pages#noemptyfragments

No objection to adding to `markdownlint`, however. :)

**Comment by aubergine10** [comment]
Been away due to RL issues, but great to see this feature implemented - many thanks!
