### ISSUE TITLE
Add support .markdownlintignore

### ISSUE THREAD

**Issue by Yegorich555** [DavidAnson/markdownlint#245]
Every linter (stylelint, eslint) supports **.ignore** file for excluding files from linting. When I run 
```markdownlint **/*.md``` command from it checks **node_modules** folder and this is stupid. I can add this folder via ```markdownlint **/*.md --ignore node_modules``` but this is doesn't match with best practices.

I would like to use **.markdownlintignore** file for excluding files/folders

**Comment by DavidAnson** [comment]
I am halfway through making this change, actually!

You can track it here: https://github.com/igorshubovych/markdownlint-cli/issues/61

**Comment by Yegorich555** [comment]
Nice to know. Thank you

**Comment by DavidAnson** [comment]
I hope to release a new CLI with this feature over the weekend.
