### ISSUE TITLE
MD029 Allow lists ordered starting with 0

### ISSUE THREAD

**Issue by yakatz** [DavidAnson/markdownlint#250]
Lists in my document start with the number 0 and are ordered after that. Is there a way to allow zero-indexed lists?

**Comment by DavidAnson** [comment]
Not today. The supported options are here: https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md029---ordered-list-item-prefix

0/1/2 is possible, but I’ve not had this request before and would like to avoid adding more options to this rule.

**Comment by DavidAnson** [comment]
Actually, I think this can be supported without a new parameter. The rule will prefer 1/2/3, but allow 0/1/2 if present. I’ll look into this for the next round of updates.
