### ISSUE TITLE
Inline rule ignore

### ISSUE THREAD

**Issue by t-rad679** [DavidAnson/markdownlint#255]
Hello!

I'd like to be able to ignore specific rules for specific sections of a markdown file. In particular, the use case I have now is in a styleguide itself. I'd like to leave the rules on overall, but exempt demonstration blocks where it is intentionally incorrect to show how not to do it. Is this possible?

**Comment by DavidAnson** [comment]
Yes, it’s documented here: https://github.com/DavidAnson/markdownlint/blob/master/README.md#configuration

**Comment by t-rad679** [comment]
Oh cool! Thanks! I googled it and didn't find anything so I figured it didn't exist.
