### ISSUE TITLE
Unspaced Line Length Enforcement

### ISSUE THREAD

**Issue by t-rad679** [DavidAnson/markdownlint#256]
The feature I would like is described in detail in an [issue](https://github.com/markdownlint/markdownlint/issues/300) on the Ruby version of the markdownlint project

**Comment by DavidAnson** [comment]
Makes sense. I’m tentatively thinking to name the corresponding parameter `stern`.

**Comment by t-rad679** [comment]
Lol what a great name.

**Comment by t-rad679** [comment]
Thank you so much! This is a great feature!
