### ISSUE TITLE
Markdownlint links to old Rules.md documentation

### ISSUE THREAD

**Issue by VideoPlayerCode** [DavidAnson/markdownlint#259]
Inside the extension, you when you open VS Code's Problems pane, and right-click on a linting error, you have "Click for more information about MDxyz...". It takes the user to `https://github.com/DavidAnson/markdownlint/blob/v0.19.0/doc/Rules.md#` which is ancient. You're up to v0.34.0 now. I suggest changing all links to `https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#`

**Comment by DavidAnson** [comment]
It takes you to the documentation for the version of the library that corresponds to what is used by the extension. In this case, version 0.34.0 of the extension uses version 0.19.0 of the library: https://github.com/DavidAnson/vscode-markdownlint/blob/master/package.json
