### ISSUE TITLE
Unable to specify custom line length

### ISSUE THREAD

**Issue by metablaster** [DavidAnson/markdownlint#260]
Unless I don't understand English and the documentation here on github, to specify line length for MD013, I have following setup:

```json
{
	"default": true,
	"line-length": 100,
	"heading_line_length": 100,
	"code_block_line_length": 100
}
```

All properties except `"default": true` are "not allowed" according to intellisense.

**Comment by metablaster** [comment]
I apologize,

It looks like I got this wrong:

```json
{
	"default": true,
	"line-length":
	{
		"line_length": 100,
		"heading_line_length": 100,
		"code_block_line_length": 100
	}
}
```

**Comment by DavidAnson** [comment]
Sorry this one instance is a little bit harder to get right the first time because the rule and property name are the same. I think this is the only place that’s true. You’ve sorted it out, though, and have the right idea that properties are stored in objects associated with each rule name.
