### ISSUE TITLE
Can we autofix length?

### ISSUE THREAD

**Issue by dotku** [DavidAnson/markdownlint#261]
I just want to check if the length 80 chars (MD013) will be on agenda?

**Comment by DavidAnson** [comment]
To fix violations of this rule “correctly” requires reflowing the entire paragraph - or else you get structure like:

    Text text text text text
    text
    text text text text text
    text
    text text text text.

That’s more sophisticated than most of the fix code is so far. The “simple” fix for this rule that creates the problem above is not very hard to do - but I think it would not be what most people want and may actually create more work for them.

Editors are already pretty good at reflow, so I am tempted to leave that challenge to them.

**Comment by dotku** [comment]
@DavidAnson okay, that make sense. let me check if editor has the option.
