### ISSUE TITLE
MD028 doesn't differentiate between two blockquotes and one blockquote with a blank line

### ISSUE THREAD

**Issue by NatoCMI** [DavidAnson/markdownlint#263]
Here's a list of quotes.

> Urban vous enroule comme une couverture chaude et vous convainc qu’on est si bien à la maison.

> Vous y avez pensé, dans la boutique en Italie, où vous étiez l’été dernier. Vous y avez pensé à l’exposition de Jackson Pollock le mois dernier. Vous y avez pensé au comptoir de l’épicerie un peu plus tôt aujourd’hui. C’est l’apparence du Terrazzo de la tuile de porcelaine Venice Villa, et vous y pensez beaucoup.

This perfectly valid use of Markdown will output the following error : 

> MD028/no-blanks-blockquote: Blank line inside blockquote *markdownlint(MD028)*

**Comment by DavidAnson** [comment]
I cannot see the original text you used in the example above, but what you describe sounds exactly like the scenario that MD028 is meant to detect and report on. Please have another look at the rule description, let me know if your situation is different, and show the original Markdown. Thanks!

https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md028---blank-line-inside-blockquote

**Comment by NatoCMI** [comment]
Yes, this is the case. Is there a proposed solution to appropriately display a list of quotes without adding useless text between? Like a double-space on an empty line or something?

**Comment by DavidAnson** [comment]
Would the below approach work?

https://dlaa.me/markdownlint/#%25m%23%20Issue%20263%0A%0A%3E%20Hello%0A%0A%3C!--%20comment%20--%3E%0A%0A%3E%20world%0A

You can also disable that rule, either for the entire project or just the file.

**Comment by NatoCMI** [comment]
That would depend on HTML support, I'm not sure if it's widespread enough. Moreover, it looks a bit more hacky than necessary. Isn't there some more natural way to do it?

I disabled the rule in my own settings, looks like it's an acceptable solution. But then, anyone else opening this file would get the errors, so I'm not so sure about it.

> Rationale: Some markdown parsers will treat two blockquotes separated by one or more blank lines as the same blockquote, while others will treat them as separate blockquotes.

Is this behaviour widespread enough to warrant being in the default settings?

**Comment by DavidAnson** [comment]
You can disable the rule in project settings so that others automatically benefit. I’m not sure how widespread this behavior difference is; the original Ruby implementation predates me. However, many of the original rules were inspired by this document which references the case we are discussing, though it does not address popularity: https://cirosantilli.com/markdown-style-guide#blockquotes

**Comment by DavidAnson** [comment]
This hack also works:

https://dlaa.me/markdownlint/#%25m%23%20Issue%20263%0A%0A%3E%20Hello%0A%0A%5B%5D(ignored)%0A%0A%3E%20world%0A

**Comment by NatoCMI** [comment]
Well then, I guess the solution is to disable it in the user settings when the file is not in a repo. Thanks for the helpful insights!
