### ISSUE TITLE
Support rule configuration changes via inline comment syntax

### ISSUE THREAD

**Issue by koppor** [DavidAnson/markdownlint#264]
MD033 allows for adding paramters:

![grafik](https://user-images.githubusercontent.com/1366654/75816898-53c33100-5d96-11ea-8592-899e1df92c44.png)

It is unclear how this works with `markdown-lint-disable-file`

I tried

```html
<!-- markdownlint-disable-file MD024 MD033(['kbd']) -->
<!-- markdownlint-disable-file MD024 MD033(kbd) -->
```

Both do not result in `<kbd>Enter</kbd>` is ignored.

**Comment by DavidAnson** [comment]
The comment syntax above allows one to enable or disable rules by name, but does not allow configuring those rules. If you want to disable MD033, just identify it by that name.

FYI that I have already sketched out a design that would allow inline comments to configure rules. I expect to work on that in the next few weeks.

**Comment by DavidAnson** [comment]
By the way, “disabling” a rule turns it off. Retreading your issue, it seems you want to “enable” MD033 (and configure it).

**Comment by koppor** [comment]
Oh, yes, you are right. I wanted to "disable MD033 for all elements besides kbd" to allow <kbd>Enter</kbd> in [CHANGELOG.md files](https://keepachangelog.com/en/1.0.0/). Reason: It renders nice:

![image](https://user-images.githubusercontent.com/1366654/75849040-2dc47d80-5de4-11ea-86dc-8a4fa9cd2a30.png)

Maybe, I ask for 

    

or (simpler syntax as html element names do not contain spaces:

    

Then one can also do easily

**Comment by DavidAnson** [comment]
You correctly guessed the planned name of the new directive! :) However, I expect to use JSON for the data so that it is consistent with the most common configuration file format. JSON is also validate-able by the user and offers auto-completion in the VS Code extension. But your scenario/proposal maps pretty well to what I had in mind.
