### ISSUE TITLE
Use of backtick in code

### ISSUE THREAD

**Issue by gjdonkers** [DavidAnson/markdownlint#271]
Hi,

When using a backtick in a line of code the following rule [MD038](https://github.com/DavidAnson/markdownlint/blob/v0.19.0/doc/Rules.md#md038---spaces-inside-code-span-elements) is triggered. 

Example:
Open a terminal [`` ⌃⇧` ``]

The result is correct, or should I use a different syntax?

Regards Giedo

**Comment by DavidAnson** [comment]
I cannot see the markdown you used, but I expect it is something like this:

    Open a terminal [`` ⌃⇧` ``]

Assuming so, the scenario of including a single space on both sides to provide separation for the backtick is not currently recognized by this rule.

But it probably should be. I will look at adding that soon, thank you!
