### ISSUE TITLE
MD037 line break not supported

### ISSUE THREAD

**Issue by regseb** [DavidAnson/markdownlint#272]
Hi,

Since _0.20.0_, error _MD037/no-space-in-emphasis_ (_Spaces inside emphasis markers [Context: "* *"])_ is displayed for this code:

```markdown
*one
two* *three*
```

I think the line break are not supported.

**Comment by DavidAnson** [comment]
Sorry about that! I rewrote this rule and probably introduced this problem. I thought I had tests for multi-line, but they may not be good enough. I’ll have a look soon.

**Comment by DavidAnson** [comment]
Definitely my bug and a regression. I have something better working now and hope to publish a patch this evening.
