### ISSUE TITLE
make work with .rmd (R Markdown) files

### ISSUE THREAD

**Issue by SpeedCoder5** [DavidAnson/markdownlint#274]
Works great with .md (Markdown) files.  Don't know how to make it work with .rmd (R Markdown) files.  If it already does - perhaps it is just an update to the documentation?

**Comment by DavidAnson** [comment]
R Markdown appears to be based on Markdown, so I would assume all of the common structure would be handled similarly. Context: https://ourcodingclub.github.io/tutorials/rmarkdown/

What do you mean when you say it doesn’t work?

**Comment by SpeedCoder5** [comment]
When I edit a .md file in VSCode with the extension installed it shows rule violations in the "problems" view.  If, instead, the extension of the file is .rmd the rule violations do not show up in the "problems" view.

**Comment by DavidAnson** [comment]
It sounds like you want to change the language mode of the current file - or maybe for all “.rmd“ files to “markdown“. Here is the documentation for how to do that in VS Code: https://code.visualstudio.com/docs/languages/overview

**Comment by SpeedCoder5** [comment]
Yes.  That worked. Thanks. :D
