### ISSUE TITLE
[bug]: MD037 can not ignore `*` in code blocks

### ISSUE THREAD

**Issue by Mister-Hope** [DavidAnson/markdownlint#278]
```
上面代码中的`export *`，表示再输出 `circle` 模块的所有属性和方法。注意，`export *`命令会忽略`circle`模块的`default`方法。
```

Got error `MD037/no-space-in-emphasis: Spaces inside emphasis markers`

**Comment by DavidAnson** [comment]
Sorry, this is a consequence of reimplementing the rule to add some other behavior.

More examples here: https://github.com/DavidAnson/vscode-markdownlint/issues/113
