### ISSUE TITLE
Document the .markdownlintignore feature in the README

### ISSUE THREAD

**Issue by KasparEtter** [DavidAnson/markdownlint#287]
When looking into how to ignore files, I stumbled upon https://github.com/DavidAnson/vscode-markdownlint#markdownlintignore and I think the `.markdownlintignore` file should also be documented in the README of this project (because this is where people look first).

(Now that I know what to search for, I also saw the issue #245. Is it such a new feature then?)

Let me know if you want me to make a pull request. I think the content could just be copy-pasted from the link above.

**Comment by DavidAnson** [comment]
Only the VS Code extension and the CLI will automatically look for and use a `.markdownlint.json` file. Both already document that. Providing custom config to this library is documented in the following places:
- https://github.com/DavidAnson/markdownlint/blob/master/README.md#optionsconfig
- https://github.com/DavidAnson/markdownlint/blob/master/README.md#config

**Comment by KasparEtter** [comment]
I see. I probably got confused by the different projects. Here is the documentation for the CLI: https://github.com/igorshubovych/markdownlint-cli#ignoring-files. Let's close this issue again then.
