### ISSUE TITLE
Top of file markdownlint comment displays in the browser

### ISSUE THREAD

**Issue by 185driver** [DavidAnson/markdownlint#293]
It seems my top of file markdownlint comment is wrapped in paragraph tags when sent to the browser (Chrome). As a result, my comment displays along with my markdown text. Can this wrapping behavior be avoided? I'd prefer comments not to be displayed.

```md
<!-- markdownlint-disable MD024 -->
# Title
```
```html
<p>&lt;!-- markdownlint-disable MD024 --&gt;</p>
<h1 id="title">Title</h1>
```

**Comment by DavidAnson** [comment]
markdownlint does not render anything, so the paragraph wrapping behavior you describe is being done by some other tool in your workflow. If that tool supports comments but just not at the top of the file, you can use the `markdownlint-disable-file` comment to move that to the bottom of your file instead (and have it still apply to the entire file). If your renderer does not support comments at all, you may need to change the markdownlint configuration in JSON or YAML instead.

**Comment by 185driver** [comment]
@DavidAnson  Thank you for replying. You're right, my apologies. It was being caused by a setting in the Markdown Preview Plus Chrome extension I use to display markdown in the browser. Resolved.
