### ISSUE TITLE
[Feature request] add `markdownlint-disable-next-line`

### ISSUE THREAD

**Issue by Mister-Hope** [DavidAnson/markdownlint#295]
Currently, we can do this:

```md
<!-- markdownlint-disable no-space-in-emphasis -->
deliberate space * in * emphasis
<!-- markdownlint-enable no-space-in-emphasis -->
```

But I think a support for this is better(just like eslint):

```md
<!-- markdownlint-disable-next-line no-space-in-emphasis -->
deliberate space * in * emphasis
```

## Why do we need it?

We can easily copy `<!-- markdownlint-disable-next-line xxx -->` and paste it across markdown files, while we can not do it using the first one.

E.G.:

I do not want MD040 when writing like below:

````md
```
MyProject/
  src/
    MyActivity.java
  res/
    drawable/
      graphic.png
    layout/
      main.xml
      info.xml
    mipmap/
      icon.png
    values/
      strings.xml
```
````

A situation like this can be triggered several times in different pages, so I would like to diable them more conviniently.

**Comment by Mister-Hope** [comment]
Any progress on this issue? I really think it's a good enhancement

**Comment by DavidAnson** [comment]
No progress, but probably for the next release.

**Comment by Mister-Hope** [comment]
I think we might need to improve it.

Some parser a new line between comment and the next line.
For example, some markdown parser requires an empty new line between HTML comment and the next line.

```md
1. <!-- text-disable-next-line -->
2. 
3. text text.
```

I think the methods should be:

1. if the next line is an empty line, go to the next one.
2. if the line only contains comments and contains -disable -enable or -disable-next-line( May be support by other linters day after) go to the next one
3. keep doing 1,2 then disable in next line and then enable it in the second line.

And if users do want two or more empty line, they should write:

```md
This is error text.

<!-- textlint-disable -->


<!-- textlint-enable -->

This is error text.
```

Also, in this case `next-line` would be misleading, something like `next-ast` would be better.

**Comment by DavidAnson** [comment]
`next-line` is clear, easy to understand, consistent with other tools like ESLint, and it works with CommonMark which is the specification I use for resolving ambiguities. I'd like to stay with this implementation and see how it works for people. Scenarios like what you describe can always be handled by `disable`/`enable`.
