### ISSUE TITLE
Extending a common configuration from remote

### ISSUE THREAD

**Issue by huseyin** [DavidAnson/markdownlint#299]
I'm working on different GitHub repositories and it's not possible to extend a common configuration from remote. Is there a plan to add such a feature in the future?

**Comment by DavidAnson** [comment]
I’m not sure I understand what you are trying to do. You can already use `require` to load configuration and there is support for `extends` - both are documented here: https://github.com/DavidAnson/markdownlint/blob/main/README.md#optionsconfig

Are you hoping to do something else?
