### ISSUE TITLE
MD033 "Inline HTML" should allow exceptions

### ISSUE THREAD

**Issue by rodneyrehm** [DavidAnson/markdownlint#3]
My markdown files contain certain html tags (like `<kbd>`) that just can't be expressed in markdown. I'd suggest to extend the configuration option to accept an array of tags that are considered safe for use in a document.

I generally want to be warned about html in my markdown, but there are situations where I actually need to use the html. I was wondering if there is any way to mark those situations inline, like you would with eslint's `/*eslint-disable foobar */`. (long shot, I don't see any obvious notation for this…)

**Comment by DavidAnson** [comment]
FYI, what you talk about in the second paragraph is a little like mivok/markdownlint#16 and might be a nice way to handle this as a special case of a more general pattern.

**Comment by rodneyrehm** [comment]
yeah, that's pretty much what I was hoping for :)

why are there two projects called markdownlint? Have you guys not tried to merge your code bases?

**Comment by DavidAnson** [comment]
The other markdownlint is for Ruby. It didn't seem clean to turn it into a dual Ruby/JavaScript offering, so I created this one for JavaScript after checking with Mark - and then reused as much as I could.

**Comment by rodneyrehm** [comment]
ah, didn't realize it was ruby - good choice, would've done the same :)

**Comment by DavidAnson** [comment]
As I revisit this request now, I see that you referenced the ability to disable MD033 inline. That functionality wasn't available at the time, but is now. Is that sufficient for your needs, or are you still interested in more granular control like what your pull request implements? I assume the latter, but wanted to check with you to be sure. Thanks!

**Comment by rodneyrehm** [comment]
I'm still interested in the tag based filter. It allows me to grant global exceptions for `<kbd>`, `<var>` etc. The inline exceptions (via `<!-- markdownlint-disable MD033 -->`) would be useful for larger constructs that are, well, the exception.

**Comment by DavidAnson** [comment]
I believe the commit above does what you'd like. If you have any issues with it, please let me know! And thanks for your patience. :)

**Comment by rodneyrehm** [comment]
very nice, thank you!
