### ISSUE TITLE
Don't print empty lines on valid Markdown

### ISSUE THREAD

**Issue by adriangrigore** [DavidAnson/markdownlint#30]
When validating successfully a `.md` file, the utility prints an empty new line. This is not needed IMO.

**Comment by DavidAnson** [comment]
@adriangrigore, I think you're referring to the command-line version of `markdownlint`, right? When I run that with a clean file, I do seem to see an extra line in the output. If that's what you have in mind, could you please open an issue in the corresponding repository: https://github.com/igorshubovych/markdownlint-cli

If not, could you please explain what you're seeing in a bit more detail?

Thanks!

**Comment by DavidAnson** [comment]
I've quickly verified removing the line identified in the related issue does what's requested, so I'm closing this issue to allow that one to track the request. Thanks!
