### ISSUE TITLE
Support EditorConfig for configuration

### ISSUE THREAD

**Issue by ejball** [DavidAnson/markdownlint#303]
It would be great if we could configure markdownlint in an [`.editorconfig`](https://editorconfig.org/) file. The syntax could be very similar to the JSON configuration, e.g. the [options.config example](https://github.com/DavidAnson/markdownlint#optionsconfig) could look something like this:

```
[*.md]
markdownlint.default = true
markdownlint.MD003.style = atx_closed
markdownlint.MD007.indent = 4
markdownlint.no_hard_tabs = false
markdownlint.whitespace = false
```

**Comment by DavidAnson** [comment]
Do you mean for the `markdownlint` CLI and/or VS Code extension? This library already supports alternate parsers for configuration: https://github.com/DavidAnson/markdownlint#parsers

**Comment by ejball** [comment]
> Do you mean for the markdownlint CLI and/or VS Code extension?

Yes, sorry about that; should I reopen this case at [vscode-markdownlint](https://github.com/DavidAnson/vscode-markdownlint) and/or [markdownlint-cli](https://github.com/igorshubovych/markdownlint-cli)? Does one use the other, or are they independent?

**Comment by DavidAnson** [comment]
No worries! They are independent projects, though I own one and am a significant contributor for the other. I think this is most applicable for VS Code, but if there is history of CLI lint tools supporting this file, it would make sense there, too. Thanks!

**Comment by ejball** [comment]
Moved to https://github.com/DavidAnson/vscode-markdownlint/issues/120
