### ISSUE TITLE
colored output

### ISSUE THREAD

**Issue by astier** [DavidAnson/markdownlint#307]
Hallo. Great project. Thank you. Is it possible to get colored output?
For example the fist part (filename/line-number/cursor-position) would be read/blue/green/etc and the actual message would be white. Something like the colored output from `grep`.

![2020-07-29-163154_354x66_scrot](https://user-images.githubusercontent.com/36510152/88813309-0cac6100-d1b9-11ea-883d-e7fa889e7b77.png)

**Comment by DavidAnson** [comment]
Thanks! I think you want to open the issue against `markdownlint-cli` (this library doesn’t output anything). Unfortunately, I can’t transfer the issue for you.

https://github.com/igorshubovych/markdownlint-cli

**Comment by astier** [comment]
You are right. I will transfer it.
