### ISSUE TITLE
Ignore indenting within code blocks

### ISSUE THREAD

**Issue by adriangrigore** [DavidAnson/markdownlint#31]
I write code with tabs and when I copy paste the code inside my markdown files, `markdownlint` complains about hard tabs. Wouldn't be a good idea to not enforce the indenting rule within code block s to allow any kind of indent?

**Comment by DavidAnson** [comment]
It sounds like you would appreciate a code_blocks parameter similar to MD013. Should be straightforward to add. My only concern would be if parsers aren't consistent about handling tabs when converting to HTML. Maybe you already know that your workflow handles this okay?
