### ISSUE TITLE
Add rule for no-line-length

### ISSUE THREAD

**Issue by bnb** [DavidAnson/markdownlint#314]
I generally want to explicitly avoid hard wrapping at 80 lines and would love to be able to have markdownlint yell at people if they try to hard wrap lines.

**Comment by DavidAnson** [comment]
This seems like a duplicate of the `single` mode discussed in #298?

**Comment by bnb** [comment]
It is indeed.

**Comment by mrmanc** [comment]
@bnb you may wish to subscribe to https://github.com/markdownlint/markdownlint/pull/319, since that’s where the conversation has been.
