### ISSUE TITLE
Question: markdownlint doesn't seem to be reading .markdownlint.json

### ISSUE THREAD

**Issue by FilBot3** [DavidAnson/markdownlint#317]
I have a little sample project I was trying to use

```bash
➜  Markdown_Pandoc_Reveal.JS tree .
.
├── dist
│   ├── slides.html
│   ├── slides_not_worky.html
│   └── slides_working.html
├── images
│   └── MechAssaultCover.png
├── Makefile
├── markdownlint.yaml
├── .markdownlint.json
├── reveal.js-3.9.2.tar.gz
├── reveal.js
│   └── <files...>
└── src
│   └── 00_introduction.md
│   └── title.yml

3 directories, 9 files
```

The `.markdownlint.json` file has the following contents:

```json
{
    "default": true,
    "MD025": false
}
```

and my `00_introduction.md` file has multiple `#` headers, which is what I want. However, markdownlint doesn't seem to be reading it. Am I doing this correctly?

**Comment by FilBot3** [comment]
I have this same `.markdownlint.json` in other folders and it seems to work there. Even a `.yaml` version of this file. I don't understand why it's not being loaded or applied to the project above.

**Comment by DavidAnson** [comment]
What tool are you using? Probably the CLI or VS Code extension?￼￼ If you're using the CLI, what command line are you using?￼

As you say, this same file works elsewhere, so what do you think is special about this situation? Do you have a pointer to a repository that demonstrates the problem?￼

**Comment by FilBot3** [comment]
I am using Vim with coc.nvim and the coc-markdownlint plugin.  Form my tinkering around, it seems that unless my folder is a Git repository, my `.markdownlint.json` wasn't getting loaded or something. This may not be an issue with this application itself and may be more of an issue with the coc-markdownlint plugin.

**Comment by DavidAnson** [comment]
Agreed. Please open an issue against that tool. The `markdownlint` library doesn’t handle this scenario. (It just exposes a helper function to load files it is specifically asked to.)

**Comment by FilBot3** [comment]
Thank you for your quick responses, @DavidAnson !
