### ISSUE TITLE
Shareable configs

### ISSUE THREAD

**Issue by pascalberger** [DavidAnson/markdownlint#33]
It would be nice if markdownlint could support shareable configs like eg. [ESLint](http://eslint.org/docs/developer-guide/shareable-configs) does.

**Comment by DavidAnson** [comment]
Interesting! What is it about shareable configuration that interests you most? The ability to upload to npm, the ability to extend other configuration, or something else?

For the first two benefits, they can be done today using styles as described in the README: https://github.com/DavidAnson/markdownlint#optionsconfig It's not quite as elegant as what ESLint has, but it captures many of the important aspects. (Note that styles could come from an npm package as loose files in the archive.)

Is this sufficient for your purposes, or do you have something else in mind?

**Comment by pascalberger** [comment]
My use case:
* I want to edit Markdown files using Visual Studio Code with the [MarkdownLint Extension](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint).
* I have a gulp script doing the linting of the files and generates a website from them
* I have several repositories, run by different teams

Therefore I'm looking for a way to share Markdown linting settings across repositories and implement them so that they are used by the Markdownlint Extension in Visual Studio Code, but also in the gulp script.

My current approach to share settings between Visual Studio Code and gulp is to have a `.markdownlint.json` file in the root of the project:

```
{
    "default": true,
    "MD003": { "style": "atx" },
}
```

In the gulp script I include the `.markdownlint.json` from the root as style:

```
markdownlint(
  {
    files: ...,
    config: require('./.markdownlint.json')
    },
    ...
```

While styles can be a solution for sharing settings between repositories, I unfortunately cannot use them since I use the feature already to share the settings beteween Visual Studio Code and the gulp script.

IMHO best solution for my use case would be to allow to reference a base settings file from a `.markdownlint.js` file. In this case I can publish common setting through as npm package, use them in all projects, add a `.markdownlint.js` file to the root of each repo, which extends the common settings and adds repos specific settings, and use the `.markdownlint.js` from the root as style in the gulp script.

**Comment by DavidAnson** [comment]
Makes sense, thanks! The idea of chaining config seems useful.

**Comment by tomByrer** [comment]
@pascalberger Why not a `.markdownlint.JSON` file (or ini like `[.editorconfig](http://editorconfig.org/)`?

Though IMHO I prefer something inside `package.json`; I have too many files in the root folder.

**Comment by pascalberger** [comment]
@tomByrer Sorry, that was a typo. Should have been `markdownlint.json` of course
