### ISSUE TITLE
Add fixInfo for MD022

### ISSUE THREAD

**Issue by nschonni** [DavidAnson/markdownlint#330]
It seems like this one should be "fixable". Not sure if you already looked at it and ruled it out because of some edge cases

**Comment by DavidAnson** [comment]
MD022 should include fix info for all scenarios it flags as an error: https://github.com/DavidAnson/markdownlint/blob/main/lib/md022.js

Is that not working or did you mean a different rule?

**Comment by nschonni** [comment]
Sorry, I think i'm actually hitting a small bug between cli and cli2.
I was running it against dotnet/docs to try out the fix for that one. cli returns 5K+ changed files, and CLI2 returned ~4K files.
I was getting mixed up because CLI2 was returning errors into the console in addition to some fixed files

**Comment by DavidAnson** [comment]
Can you describe the difference or give an example or the commands to reproduce this?

**Comment by nschonni** [comment]
Sure, here is the steps:
1. Clone dotnet/docs
2. Remove MD022 suppression in `.markdownlint.json`
3. Run `markdownlint "**/*.md" --fix`
4. 5K+ files updated, no warnings in console
5. Reset changes, and reapply `.markdownlint.json` MD022 supression
6. Run `markdownlint-cli2 "**/*.md" --fix`
7. 4K< files changed, and console warnings for MD022 issues printed

**Comment by DavidAnson** [comment]
At the risk of nitpicking, "--fix" is not a command line argument for CLI2; I assume you are setting `fix:true` in its options file? I can try this and have a look.

**Comment by nschonni** [comment]
Nope, was just using the old config format. Not sure why CLI2 was updating the files then :P

**Comment by DavidAnson** [comment]
I've never seen files get updated without `fix:true`. If that's happening, please let me know how. The `--fix` argument should only seem like another file glob.

**Comment by nschonni** [comment]
I'll take a look tomorrow again when I'm on my other machine. Feel free to flip this issue over to the cli2 repo though, since it's not really related to the core lib anymore

**Comment by nschonni** [comment]
You're right, I must have not reset the changes fully. I'll stick with the original CLI for the fixes since the config way is a little annoying when trying out fixes
