### ISSUE TITLE
Allow configuration to be read from package.json

### ISSUE THREAD

**Issue by ylavoie** [DavidAnson/markdownlint#332]
Many Linters allow their configuration to be read from a key in package.json. JS & CSS linters, for example. Allowing Markdownlint to read its config from a 'markdownlint' key would consistent with others.
This simplifies maintenance by regrouping all relevant configs in a single file.

**Comment by DavidAnson** [comment]
Do you mean to open this issue for one of the CLI packages? The library (this package) doesn’t read configuration from anywhere - it requires the caller to pass it in from wherever the caller wants to get it.

**Comment by DavidAnson** [comment]
This approach isn't really consistent with the goals of `markdownlint-cli2`, but it might be good for `markdownlint-cli` here: https://github.com/igorshubovych/markdownlint-cli
