### ISSUE TITLE
How to sponsor this Open Source project?

### ISSUE THREAD

**Issue by gianpaj** [DavidAnson/markdownlint#333]
https://github.com/sponsors

Is there a preferred way by the maintainer(s)?

I'd be happy to donate. I think **markdownlint** is very useful together with this other VSCode extension

https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one

And `prettier` markdown support https://prettier.io/blog/2017/11/07/1.8.0.html

**Comment by DavidAnson** [comment]
That's very kind, thank you!! Please donate to a worthy cause or charity instead - there are plenty of organizations that need help and are doing far more good for the world.

**Comment by gianpaj** [comment]
cool :) will do
