### ISSUE TITLE
MD037/no-space-in-emphasis triggers when using LaTex block

### ISSUE THREAD

**Issue by bathtown** [DavidAnson/markdownlint#357]
when I write something like this:

```md
$$
x * y = x * (y_1 + y_2 + \cdots + y_n)
$$
```

it says MD037/no-space-in-emphasis: Spaces inside emphasis markers. But it's just `*` in LaTex block, and I think this should be fixed :)

![image](https://user-images.githubusercontent.com/49479124/102000480-eb40b180-3d22-11eb-9d6d-3af5eef39f2c.png)

**Comment by marek-zeleny** [comment]
Hi, there's a very similar problem with `*` within a LaTeX block.
```
Some text $a * b$ some *highlighted* text.
```
Text between the first `*` (within the LaTeX expression) and the second `*` (starting the highlighted text) gets underlined as an error MD037.

By the way, thanks for doing this, it's an awesome tool :)
