### ISSUE TITLE
Inline HTML vs. having vertical bars inside tables

### ISSUE THREAD

**Issue by Youssef1313** [DavidAnson/markdownlint#363]
Is there a way to have vertical bars inside code snippet in a table without violating the "No HTML elements" rule?

See https://github.com/dotnet/docs/pull/22222#discussion_r551917298 for details.

Thanks in advance.

**Comment by DavidAnson** [comment]
Yes, please see my PR for the relevant issue: https://github.com/dotnet/docs/pull/21977

**Comment by Youssef1313** [comment]
Thanks @DavidAnson. That helps a lot!
