### ISSUE TITLE
MD029 Is there a way to "hide" tables embedded in an ordered list?

### ISSUE THREAD

**Issue by jamesmrollins** [DavidAnson/markdownlint#365]
Hi @DavidAnson 
We have developed training documentation where we want to embed a table into an ordered list.  Unfortunately, when we do that, it breaks the ordered list and is reported as an error in MD029.  See below for an example.  If there was a way to "hide" the table, such as when one hides a special character by placing the backslash character immediately before it, that might work?  

![image](https://user-images.githubusercontent.com/30132017/104054226-8fdad580-51a1-11eb-9e86-9b0dc8b9767b.png)

**Comment by DavidAnson** [comment]
Here is a table in an ordered list with no issues. Is that what you want?

https://dlaa.me/markdownlint/#%25m%23%20Table%20in%20ordered%20list%0A%0A1.%20Text%0A%20%20%20%7C%20Table%20%7C%20Table%20%7C%0A%20%20%20%7C-%7C-%7C%0A%20%20%20%7C%20Table%20%7C%20Table%20%7C%0A

**Comment by jamesmrollins** [comment]
Yes this would work.  I attempted to indent the tables 4 spaces, but when I did that, they blew up.

**Comment by nschonni** [comment]
Maybe try adding the leading `|` to the rows when you indent

**Comment by jamesmrollins** [comment]
Thank you @DavidAnson and @nschonni.  It worked great.  The tables blew up because I didn't indent the appropriate number of spaces. Now is both formatted correctly and passing the lint check.  This item has been resolved.
