### ISSUE TITLE
MD037  Not Detecting Error Consistently

### ISSUE THREAD

**Issue by jamesmrollins** [DavidAnson/markdownlint#369]
Hi @DavidAnson 
I cannot seem to get this line of code to clear the test indicated in the title of this issue.  Funny thing is, the exact line of text is used earlier in the document, but seems to avoid detection.  I literally copied and pasted this line lower down in the document.   The _MTL_ logo is italicized and the whole line is bold face.  I am not sure how to correct his.

## Line earlier in the document that is not detected
![image](https://user-images.githubusercontent.com/30132017/105554651-a06c6f00-5cbc-11eb-8a84-1eb9fc3024df.png)

## Line in question that violates rule MD037
![image](https://user-images.githubusercontent.com/30132017/105554724-ca259600-5cbc-11eb-871e-fca3bf00935d.png)

## As shown in GitHub Actions
![image](https://user-images.githubusercontent.com/30132017/105554767-e0cbed00-5cbc-11eb-861b-87878757dc66.png)

**Comment by DavidAnson** [comment]
It's hard to tell from the screenshots and I don't seem to have access to that repository (https://github.com/mtl/blue), but what seems likely is that there is another '_' somewhere earlier that is unmatched and therefore skewing the results. My guess is that it's the one in data_ui. By spec, that should not be relevant for this rule, but this rule exists to identify scenarios that are outside the spec and so it can get confused by things like that. If you find and escape (with '\') the relevant '_', that should address the issue.

**Comment by jamesmrollins** [comment]
The full code is below.  I'm sorry I can't share the repo with you, it doesn't belong to me, I'm just a contributor.  I checked for an unpaired quote elsewhere in the table, but was unable to locate any.  As you can see with the code below, that same line of code exists all over the place in the file.

# Code Follows

---
title: "MTL Session 2 - Learner See"
author: "Team PSD"
date: "March 2020"
release: "MTL 2.0"
output: 
  github_document: default
  html_document: default
  pdf_document: default
  word_document: default
  ioslides_presentation: default
  slidy_presentation: default
  powerpoint_presentation: default
---

[<img src = "https://github.com/lzim/teampsd/blob/master/resources/title_slides/mtl_s02_data_ui_title.png"
    height = "175" width = "420">](#DontLink)

**Note**: If you are a self-directed learner, then some of the details in the guides may not apply to you. These guides were developed for facilitated *Modeling to Learn* Live team meetings.

# MTL Live Session 02

## Today we're modeling to learn how to check our patient data and team trends

## Done and Do (15 minutes)


| [<img src = "https://github.com/lzim/teampsd/blob/master/resources/icons/done.png" height = "80" width = "80">](#DontLink) **Done** | [<img src = "https://github.com/lzim/teampsd/blob/master/resources/icons/do.png" height = "90" width = "90">](#DontLink) **Do** |
| --- | --- |
| [<img src = "https://raw.githubusercontent.com/lzim/teampsd/master/resources/logos/va_team_psd_logo_sq_sm.png" height = "75" width = "100">](mailto:mtl.help@va.gov) [<img src = "https://raw.githubusercontent.com/lzim/teampsd/master/resources/logos/mtl_how_data_sm.png" height = "75" width = "110">](http://mtl.how/data) We identified our Team Vision, selected our Team Lead and set a standing team meeting time. We logged in to mtl.how/data to look at the facility data.  [![data ui login screen cast](https://raw.githubusercontent.com/lzim/teampsd/master/resources/gifs/mtl_2.0/data_ui_login.gif)](#DontLink)  **_MTL_ 2.0. For _MTL_ 1.7, click [here](https://github.com/lzim/mtl/blob/master/release_1.7/mtl_session02_see.md)**  | [<img src= "https://raw.githubusercontent.com/lzim/teampsd/master/resources/logos/mtl_how_data_sm.png" height= "75" width= "110"/>](http://mtl.how/data) We will confirm and review Team Data for _MTL_ relevant to our Team Vision. [![session 2 data ui screen cast](https://raw.githubusercontent.com/lzim/teampsd/master/resources/gifs/mtl_2.0/session2_data_ui_2.gif)](#DontLink) **_MTL_ 2.0. For _MTL_ 1.7, click [here](https://github.com/lzim/mtl/blob/master/release_1.7/mtl_session02_see.md)**  |


[<img src = "https://github.com/lzim/teampsd/blob/master/resources/icons/learning_objectives.png" alt = "learning objectives" height = "90" width = "90" style ="display: inline-block"/>](#DontLink)

## Learning Objectives

1. Describe the decisions your team made in producing your team data table.

2. Test out whether your expectations about team historical trends are displayed in the "viz" tabs.

3. Apply your clinical expertise to identify new information about a team patient in the "data" tabs.

## In-session Exercise (30 minutes)

[<img src = "https://raw.githubusercontent.com/lzim/teampsd/master/resources/illustrations/data_ui_sim_ui.png">](data UI says what is and sim UI asks What if - illustration?)

## *MTL* on BISL

### 1. Open an internet browser window. Go to mtl.how/data. First select your VISN and then select your facility

[![Data UI Login Screen Cast](https://github.com/lzim/teampsd/blob/master/resources/gifs/mtl_2.0/data_ui_login.gif)](#DontLink)

**_MTL_ 2.0. For _MTL_ 1.7, click [here](https://github.com/lzim/mtl/blob/master/release_1.7/mtl_session02_see.md)**

### 2. Explore the facility data

- To **view facility data** click on the [...] next to the file **"facility.xlsb"** and click **"Edit"** to open in Excel.
- **Team files are in team folders.** If you do not see a team folder, **request a team folder above.**

[![data ui login screen cast](https://github.com/lzim/teampsd/blob/master/resources/gifs/mtl_2.0/data_ui_splashpage.gif)](#DontLink)

***MTL* 2.0. For *MTL* 1.7, click [here](https://github.com/lzim/mtl/blob/master/release_1.7/mtl_session02_see.md)**

- Click through the tabs on the bottom of the Excel spreadsheet. What options are there and what do they mean? Hints:
  - Data: Sortable report of data
  - Diag: Diagnostic data
  - Enc: Encounter types of visits
  - HF: Health Factors data related to visits
  - Meas: Measures or flag names
  - Viz: Visualization of trends

- What filtering options are available?
  - Filter to your clinic or division to see trends for the last two years.

**New for _MTL_ 2.0**

- You no longer need to use only Internet Explorer or Edge to open mtl.how/data. You can use any browser.

- View facility data via the "facility.xlsb" Excel sheet instead of the splash page.

- vizDiag shows unique visits by primary diagnosis on the visit of PTSD, Dep, OUD, or AUD.

- Patient SSID is no longer asterisked out in the facility data. It has been completely removed. Please go to the data UI to see Patient SSID information.

### Your Team Data Folder

### 3. Scroll to your team folder at the bottom of the page. Open the data_ui folder and open your data_ui file in Excel

- Click on the 3 dots /[/./././] next to the data_ui file.
- Click on "Edit" to open in Excel, then click "Edit Workbook" at the top of the sheet.

[![edit in excel screen cast](https://github.com/lzim/teampsd/blob/master/resources/gifs/mtl_2.0/edit_in_excel.gif)](#DontLink)

### 4. Go to the ClinicSelection tab. Use columns C-H to select the clinics that make up your team

- You can sort and filter by Clinic Name, Division Name, Physical Location, Primary Stopcode, Secondary Stopcode, and Default Provider.
- Note: This will pull all clinics used in the last two years (including de-activated clinics: denoted by "ZZ"). For de-activated clinics, you can find the date of de-activation in column I.
- Follow the instructions in **Box A2.**
- After filtering, click the "Add All" arrow in column B (Cell B6). Fine-tune your selections by double-clicking on the clinic name in column A (to remove) or column C (to add).

[![clinic selection screen cast](https://github.com/lzim/teampsd/blob/master/resources/gifs/mtl_2.0/clinic_selection.gif)](#DontLink)

**New for _MTL_ 2.0**

- In the future, if you want to quickly get the same list of clinics again, you can select the grey "Get previous clinic list from last click of Get Patient-level Data" arrow in Column B (Cell B3).

For *MTL* 1.7 click [here](https://github.com/lzim/mtl/blob/master/release_1.7/mtl_session02_see.md).

### 5. To view your team patient data and your team trends click "Get Patient-level Data." We will not do this in-session today

- **You already have a fresh data UI file to work with in your team data_ui folder.**
- We will learn about the "Create Team Data Table" button in our next team meeting.
- **To query patient and clinic level data using the data_ui, you will need LSV permissions.** To check which facilities you have LSV access for, click [here](https://spsites.cdw.va.gov/sites/PBM_AD/_layouts/15/ReportServer/RSViewerPage.aspx?rv%3aRelativeReportUrl=/sites/PBM_AD/AnalyticsReports/LSVAccessVerification.rdl) (VA intranet link to access verification).
- **If you don't have access to facilities that you believe you should, please verify:**
   1. CPRS access/permissions at your station (i.e COR tab access for CPRS).
   2. Your network username recorded in VistA.
   To have your network username recording in VistA, please follow the instructions outlined [here](https://vaww.dev.fre.cdw.va.gov/sites/D05_VISN21/DashboardDevelopment/Updating%20Network%20UserName%20in%20VistA.aspx) (VA intranet link to Vista).

**New for _MTL_ 2.0**

- "Create Team Data Table for Sim UI" is now called "Create Team Data."

[![create team data folder graphic](https://github.com/lzim/teampsd/blob/master/resources/gifs/mtl_2.0/create_team_data_folder.png)](#DontLink)

For *MTL* 1.7 click [here](https://github.com/lzim/mtl/blob/master/release_1.7/mtl_session02_see.md).

**NOTE: It takes some time to run a query from your team data UI to the VA Corporate Data Warehouse.**

- On average (depending on the size of your team) it may take 15 minutes or so for your team data UI to pull in fresh data, and Microsoft Excel will be unresponsive until the data UI has finished pulling in your data.

[![data user interface screen cast](https://github.com/lzim/teampsd/blob/master/resources/gifs/mtl_2.0/session2_data_ui_2.gif)](#DontLink)

**_MTL_ 2.0. For _MTL_ 1.7, click [here](https://github.com/lzim/mtl/blob/master/release_1.7/mtl_session02_see.md)**

### 6. Click to view the "viz" tab, which show team trends

- There are team trends for diagnoses, encounters, health factor data (e.g., suicide plans, evidence-based practice templates), and measures from Mental Health Assistant.
- What stands out to you?
- What is most important to you to check out first?
- What is most surprising?

[![session 2 data ui visual diagram screen cast](https://github.com/lzim/teampsd/blob/master/resources/gifs/mtl_2.0/session2_data_ui_4_viz_diag.gif)](#DontLink)

**_MTL_ 2.0. For _MTL_ 1.7, click [here](https://github.com/lzim/mtl/blob/master/release_1.7/mtl_session02_see.md)**

**New for _MTL_ 2.0**

- Click on any trend line and then "Quick Explore" (look for the magnifying glass). In the "Explore" box, pick the item you want to explore and click "Drill To." Keep using the Quick Explore to drill until you reach the data you want. To return to the original settings, click on the gray "Reset Pivot Chart."

- The viz tabs will also return to default selections, when you click "Get Patient-level Data" for new data pulls.

- Right click on a trend line and filter to hide a selected item or only keep the selected item.

- vizDiag in the data UI shows a drill down by diagnoses or combination of diagnoses.

[![data user interface screen cast](https://github.com/lzim/teampsd/blob/master/resources/gifs/mtl_2.0/session2_data_ui_4_viz_diag_mtl_2.0.gif)](#DontLink)

For *MTL* 1.7 click [here](https://github.com/lzim/mtl/blob/master/release_1.7/mtl_session02_see.md).

### 7. Click to view the "data" tab, which show your team's individual patient information

- Patients who have requested restricted access to their information have asterisks /(/*/*/*/*/) in Columns F & G. If you are a VA provider, you can still identify patients from Column H.
- Patient information corresponds to the same categories as the team trends: diagnoses, encounters, health factor data (e.g., suicide plans, evidence-based practice templates), and measures from Mental Health Assistant.
- Providers can filter to find specific patients, or produce reports.

**New for _MTL_ 2.0**

- dataDiag in the data UI has an additional column after "Diagnoses of Interest," called "Primary Diagnoses", specifying which diagnosis is primary.

[![primary diagnosis example graphic](https://github.com/lzim/teampsd/blob/master/resources/gifs/mtl_2.0/primary_diagnoses.png)](#DontLink)

For *MTL* 1.7 click [here](https://github.com/lzim/mtl/blob/master/release_1.7/mtl_session02_see.md).

- What **data** tab would you use to find out how many current patients on the team are engaged in a specific evidence-based psychotherapy? What column shows you the session number (EBP template) that the patient is on?
- What **viz** option would you use to see what the most common service encounters or visits are?
- Are there services that have been increasing over time? Are there services that have been decreasing over time?

**With the team trends (viz) and team patient (data) information in the data UI, your team can efficiently use team meetings to focus on the interrelated issues of care coordination and team quality improvement.**

## Done and Do (15 minutes)

| [<img src = "https://github.com/lzim/teampsd/blob/master/resources/icons/done.png" height = "80" width = "80">](Done icon) **Done** | [<img src = "https://github.com/lzim/teampsd/blob/master/resources/icons/do.png" height = "90" width = "90">](Do icon)) **Do** |
| --- | --- |
| [<img src = "https://raw.githubusercontent.com/lzim/teampsd/master/resources/logos/mtl_how_data_sm.png" height = "75" width = "110">](http://mtl.how/data) We confirmed the clinics that make up our team for the Team Data UI. [![session 2 data screen cast](https://github.com/lzim/teampsd/blob/master/resources/gifs/mtl_2.0/session2_data_ui_2.gif)](#DontLink) ***MTL* 2.0. For *MTL* 1.7, click [here](https://github.com/lzim/mtl/blob/master/release_1.7/mtl_session02_see.md)** | [<img src = "https://raw.githubusercontent.com/lzim/teampsd/master/resources/logos/mtl_how_data_sm.png" height = "75" width = "110">](http://mtl.how/data) Review the HF, Diag, Enc and SP tabs in Team Data UI to find a patient (zoom in) and find a team trend (zoom out). Log in to mtl.how/data and look at the two team folders: data_ui and team_data_table. [![session 2 data ui screen cast](https://github.com/lzim/teampsd/blob/master/resources/gifs/mtl_2.0/session2_data_ui_4_viz_diag.gif)](#DontLink) **_MTL_ 2.0. For _MTL_ 1.7, click [here](https://github.com/lzim/mtl/blob/master/release_1.7/mtl_session02_see.md)**  |

**Comment by DavidAnson** [comment]
I can't do much with the rendered Markdown. If you put it in a code block, GitHub should preserve the original text.

**Comment by jamesmrollins** [comment]
Code block as requested - thank you.

**Comment by DavidAnson** [comment]
Thanks, that confirms its due to `data_ui` in the text like I suggested above. Changing to `data\_ui` avoids the warning.

**Comment by jamesmrollins** [comment]
I will check it out. Thank you.

**Comment by jamesmrollins** [comment]
Yes - that corrected the problem.  Thanks for your help @DavidAnson.
