### ISSUE TITLE
Add JSON Schema support for `.markdownlintrc` config files

### ISSUE THREAD

**Issue by YashTotale** [DavidAnson/markdownlint#372]
Currently, `.markdownlint.json` config files have JSON schema support. It would be great if `.markdownlintrc` files also had JSON schema support.

**Comment by DavidAnson** [comment]
Did you mean to open this for the VS Code extension at <https://github.com/DavidAnson/vscode-markdownlint>?

**Comment by YashTotale** [comment]
Oops, I'll open this issue in the other repository 👍

**Comment by YashTotale** [comment]
New issue: https://github.com/DavidAnson/vscode-markdownlint/issues/155
