### ISSUE TITLE
Add a .pre-commit hook

### ISSUE THREAD

**Issue by JensHeinrich** [DavidAnson/markdownlint#374]
The ruby implementation already supplies a [pre-commit](https://pre-commit.com/) hook and it would be useful to have one for the npm version too

**Comment by DavidAnson** [comment]
Both CLI’s have this already:
- https://github.com/igorshubovych/markdownlint-cli/blob/master/.pre-commit-hooks.yaml
- https://github.com/DavidAnson/markdownlint-cli2/blob/main/.pre-commit-hooks.yaml

**Comment by JensHeinrich** [comment]
Thank you very much.

I did not see it.

Can I add a reference to the CLI section to the example usage section?

**Comment by janosh** [comment]
I second @JensHeinrich's suggestion to specifically mention pre-commit in the readme. ac8545e did not help me find this.

**Comment by janosh** [comment]
Fair enough. I noticed you have a file on Prettier in the docs. Perhaps a file for pre-commit could be added as well?￼
