### ISSUE TITLE
[feature request] disable for next block

### ISSUE THREAD

**Issue by CircleCode** [DavidAnson/markdownlint#389]
Say i want to enforce MD013 for all code blocks, except one (for example, I show raw script output, and I want it be unaltered)

I'd like to have something like

`````md
<!-- markdownlint-disable-next-block MD013 -->
```raw
some text with very long lines
[…]
```
`````

**Comment by CircleCode** [comment]
after a more attentive reading, I was able to fulfill my needs with

`````md
<!-- markdownlint-capture -->
<!-- markdownlint-disable MD013 -->
```raw
some text with very long lines
[…]
```
<!-- markdownlint-restore -->
`````

However, i do not close this issue because I think a *per block exception* would make sense for readibility.
But if you consider this is too much work compared to the real benefit, feel free to close this request

**Comment by DavidAnson** [comment]
I agree that would be a little more elegant, but it adds complexity and assumes people know what a block is (maybe less clear with text vs. code?). I'll keep this in the back of my mind, but for now will stick with the pattern you show above. Thanks for the suggestion, glad you figure this out!
