### ISSUE TITLE
Add rule to enforce letter case of project names [WAS: How to add custom rules?]

### ISSUE THREAD

**Issue by bebraw** [DavidAnson/markdownlint#39]
Hi,

I checked the docs/source but I didn't see any obvious extension mechanism (apart from forking). Do you have some preferred way on how to handle custom rules? I can see the rule mechanism itself is quite simple. If it was possible to inject new ones through the API somehow (match through npm/Node), I could likely do what I want (I need to verify certain word is lowercase always).

**Comment by DavidAnson** [comment]
As you note, there is no public extension mechanism right now. Rules are already independent, so this is something I've considered - but it hasn't come up. I have some concerns about presenting a friendly API that versions well and I also haven't decided how I think rule names should integrate or migrate.

None of this is insurmountable, this just hasn't been a priority so far.

Regarding your specific desire, could you please describe it in a bit more detail? I wonder if there's a general-purpose rule I might add that would address your needs (and defer extensibility a bit longer).

**Comment by bebraw** [comment]
@DavidAnson My first use case is simple. I need to validate that people are writing webpack as webpack at [webpack.js.org](https://github.com/webpack/webpack.js.org). It's a trivial check, but you have to start somewhere.

Basically I want to push as much work to CI as possible (faster reviews, less work).

**Comment by DavidAnson** [comment]
This seems like a rule that might be fairly broadly useful: ensure that certain names are cased in a standard manner. I have an idea how I could add a rule for this - I'll look into it shortly.

Thanks for the idea!
