### ISSUE TITLE
MD044: Fixes are too greedy

### ISSUE THREAD

**Issue by skyzyx** [DavidAnson/markdownlint#403]
| Package | Version |
|-|-|
| markdownlint-cli | `0.27.1` |
| markdownlint | `~0.23.1` |

I run into this issue _often_ where ignoring code blocks is sometimes followed, and sometimes not. Also, sometimes the globbing of the word is greedier than I'd like (e.g., `docker.service` → `Docker`). But maybe the latter is a separate issue.

----

```plain
The proper case is: Docker

Fixing this in the other panel will glob too greedily: `/var/lib/docker/overlay2`

<!-- markdownlint-configure-file {
    "proper-names": {
        "names": [
            "Docker"
        ]
    },
    "code_blocks": false
} -->
```

----

https://dlaa.me/markdownlint/#%25m%23%20Issue%20403%0A%0AThe%20proper%20case%20is%3A%20Docker%0A%0AFixing%20this%20in%20the%20other%20panel%20will%20glob%20too%20greedily%3A%20%60%2Fvar%2Flib%2Fdocker%2Foverlay2%60%0A%0A%3C!--%20markdownlint-configure-file%20%7B%0A%20%20%20%20%22proper-names%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%22names%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22Docker%22%0A%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%22code_blocks%22%3A%20false%0A%7D%20--%3E%0A

**Comment by DavidAnson** [comment]
If you fix the configuration per issue #402, is this still an issue?

**Comment by DavidAnson** [comment]
Updated repro: https://dlaa.me/markdownlint/#%25m%23%20Issue%20403%0A%0AThe%20proper%20case%20is%3A%20Docker%0A%0AFixing%20this%20in%20the%20other%20panel%20will%20glob%20too%20greedily%3A%20%60%2Fvar%2Flib%2Fdocker%2Foverlay2%60%0A%0A%3C!--%20markdownlint-configure-file%20%7B%0A%20%20%20%20%22proper-names%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%22names%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22Docker%22%0A%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%0A%7D%20--%3E%0A

**Comment by shaggy-2** [comment]
The proper case is: Docker

Fixing this in the other panel will glob too greedily: `/var/lib/docker/overlay2`
