### ISSUE TITLE
Add rule to check for file naming

### ISSUE THREAD

**Issue by pascalberger** [DavidAnson/markdownlint#41]
Adding a rule to check for file naming would be a nice enhancement.

Guidelines which for example we currently are using:
* Filename needs to be lowercase
* Allowed characters: `a-z 0-9 - .`

**Comment by DavidAnson** [comment]
To be clear, you are referring to the names of the Markdown files that are parsed for content, right? If so, this feels a bit on the edge of what I thing a Markdown linter should do. But I will think about this more.

**Comment by pascalberger** [comment]
Yes, I was referring to the `*.md` files. I see the point that this is not a typical use case for a linter, since it is no longer about the content. On the other hand, considering a repo containing some source and Markdown documentation, it still has to do with the Markdown part :)

**Comment by DavidAnson** [comment]
Got it.

What about something like this instead: https://www.npmjs.com/package/gulp-check-file-naming-convention

Or maybe:
https://www.npmjs.com/package/check-filename

**Comment by pascalberger** [comment]
Thinking a little bit more about it, doing these checks outside might be the better solution than duplicating existing functionality here.

**Comment by DavidAnson** [comment]
Great.
