### ISSUE TITLE
Is there an option to replace inlined 2/3 backticks with one?

### ISSUE THREAD

**Issue by tetafro** [DavidAnson/markdownlint#411]
I want to replace this
```
Hello ```world```
```

or this
```
Hello ``world``
```

with this
```
Hello `world`
```

Is it possible? Default settings don't do it, and I can't see any option for this.

**Comment by DavidAnson** [comment]
No. These are all correct and there is no rule like "preferred inline dash count" today. I don't expect this is a common situation, or?

**Comment by tetafro** [comment]
> I don't expect this is a common situation

Agree. But unfortunately we have a project, where it's done everywhere :) I'm just trying to find an easy way to fix it.
Anyway, thanks for your answer.
