### ISSUE TITLE
MD0013 line length and tables

### ISSUE THREAD

**Issue by peteraritchie** [DavidAnson/markdownlint#414]
Table rows must be on a single line so row markdown that spans the configured max column products noisy md0013 errors.

e.g.
```markdown
|a|b|c|d|
|--|--|--|--|
| DateTime | UTC DateTime | Text/String | `YYYY-MM-DDThh:mm:ss:mmmZ` or `YYYY-MM-DDThh:mm:ssZ` |
```

**Comment by DavidAnson** [comment]
You can set this rule's `tables` parameter to `false` to suppress violations in tables.

https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md013
