### ISSUE TITLE
Built in rules: API to rule descriptions

### ISSUE THREAD

**Issue by markkulube** [DavidAnson/markdownlint#423]
Is there functionality and/or API to mutate and customize the built-in-rule error descriptions?

For example customize:
## MD048 - Code fence style

to

**Comment by markkulube** [comment]
@DavidAnson thanks. I may have found a temporary hack to customize these messages inside my node applet that relies on `markdownlint`. But totally agreed, making these configurable inside `markdownlint ` is the preferred long term enhancement.

**Comment by DavidAnson** [comment]
I agree some of the rule descriptions could be improved by being clearer and more consistent. However, I don't see the need for an API to support this. As a library, callers can already manipulate the results however they like.
