### ISSUE TITLE
No bare URL (MD034) doesn't support autolink titles

### ISSUE THREAD

**Issue by mondeja** [DavidAnson/markdownlint#424]
I'm not sure if I should open this here, please close it if you found it out of scope.

The problem is simple, an autolink with title like `<https://foo.bar "with title">` breaks the MD034 rule. I've seen that this parsing [is not supported by markdown-it](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3Chttps%3A%2F%2Fautolink.ext%20%5C%22with%20title%5C%22%3E%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Afalse%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D), but other parsers based on CommonMark like [MD4C](https://github.com/mity/md4c) support it.

The latest [CommonMark spec is not clear about if it should be supported](https://spec.commonmark.org/0.30/#autolink), possibly breaking the "Spaces are not allowed in autolinks" statement.

So I'm very confused here. Should markdownlint allow that? Should CommonMark spec clarify this? Is possible to use a markdown-it plugin that implements this when using markdownlint?

Thanks for your great work!

**Comment by nschonni** [comment]
It doesn't seem that autolinks support titles at all

**Comment by DavidAnson** [comment]
Agreed, example 601 of the CommonMark specification explicitly forbids space in autolinks: https://spec.commonmark.org/0.30/#example-601

That said, MD034 is written so that if a markdown extension parsed an autolink with a space, it would not then be reported as a violation.

**Comment by mondeja** [comment]
OK, thanks!
