### ISSUE TITLE
[feature] distinguish list from math environment

### ISSUE THREAD

**Issue by Freed-Wu** [DavidAnson/markdownlint#434]
Some markdowns support math environment, e.g.,

```tex
$$1
+ 1$$
```

However, markdownlint will think the line started with `+, -, *`
is a list:

![image](https://user-images.githubusercontent.com/32936898/135430104-7a512df7-a907-4268-a543-92423f3c35a7.png)

Thanks!

**Comment by DavidAnson** [comment]
To add new behavior to the Markdown parser, you can use plugins: https://github.com/DavidAnson/markdownlint#optionsmarkdownitplugins

The VS Code extension includes the `markdown-it-texmath` plugin to support math syntax like you show: https://www.npmjs.com/package/markdown-it-texmath

**Comment by Freed-Wu** [comment]
Great!
