### ISSUE TITLE
Raise of rule MD037 in correct situation

### ISSUE THREAD

**Issue by rfresow** [DavidAnson/markdownlint#444]
The rule *MD037 - Spaces inside emphasis markers* is raised in the following correct situation:

New_value is *old_value* and *new_value*.

Using v0.44.4.

![image](https://user-images.githubusercontent.com/4982940/137268452-7a6d6792-3881-4b0a-a65a-87643af08a27.png)

**Comment by DavidAnson** [comment]
Note to self: See also #408.
