### ISSUE TITLE
MD026: "Trailing punctuation in heading" confuses emoji codes with punctuation

### ISSUE THREAD

**Issue by mlibre** [DavidAnson/markdownlint#457]
In header like:
```
# Header :heartpulse:
```
It can't detect where ":" is for emoji code or it is an unnecessary ":"

**Comment by DavidAnson** [comment]
Emoji are not part of the CommonMark specification, but I'll look into this.

**Comment by DavidAnson** [comment]
See #653 for markdown-it plug-in.
