### ISSUE TITLE
False MD401 Errors (First line in a file should be a top level heading)

### ISSUE THREAD

**Issue by FrightRisk** [DavidAnson/markdownlint#459]
This error comes up now everytime I create a new page. The page is no different than any other page. I use a line of asterisks above and below my H1 headings. The top asterisk like shows the squigglies and gives me an error. I can't see a pattern and there are no special characters in the .rtf file seen in a next editor. Yet if I delete the file and then cut and paste it all back in again and save, the error goes away. This has just started happening in the last couple of weeks.

**Comment by nschonni** [comment]
If you're putting those astrix lines above and below your heading, it is likely being interpreted as front matter rather than a plain H1

**Comment by DavidAnson** [comment]
If the first line of the file is a line of asterisks as I think you are saying, then this rule is correctly reporting that the first line is not a top-level heading. If not, please show a small example of the Markdown you are using.

**Comment by DavidAnson** [comment]
(What Nick suggested.)
