### ISSUE TITLE
Consider using cosmiconfig to manage configs

### ISSUE THREAD

**Issue by xboy2012** [DavidAnson/markdownlint#461]
The current implementation just support `markdownlintrc.json` and `markdownlintrc.yaml`

Why not just use cosmiconfig, the solution many projects uses?

**Comment by DavidAnson** [comment]
This library does not directly deal with configuration files by name and supports any kind of parser the user wants: https://github.com/DavidAnson/markdownlint#parsers

I think you are asking about markdownlint-cli: https://github.com/igorshubovych/markdownlint-cli

It uses the `rc` package: https://github.com/igorshubovych/markdownlint-cli#configuration

**Comment by xboy2012** [comment]
Well, my consideration is to support markdownlintrc.js，in order to integrate with our team code standard tools
Then we could implement dynamic configs.

**Comment by DavidAnson** [comment]
If you are making a request for the markdownlint-cli package, please open an issue in that project. I provide a link to it and explain what it currently uses in my comment above.

If you are making a request for this library, I do not understand what you want. Please see my comment above and explain what API or code in this project that you are suggesting a a change to.

Thanks.

**Comment by DavidAnson** [comment]
A Google search for `.markdownlintrc.js` suggests you may be using this package: https://www.npmjs.com/package/markdownlint-config-fluid

Their README explains how to integrate with both CLI's.

**Comment by xboy2012** [comment]
well, I see
https://github.com/DavidAnson/markdownlint-cli2/blob/main/test/markdownlint-cli2-js/.markdownlint-cli2.js

Then `markdownlint-cli2` is just what I need. Thanks a lot.

**Comment by DavidAnson** [comment]
Great!
