### ISSUE TITLE
Not working when use \\wsl$\ubuntu protocol access file

### ISSUE THREAD

**Issue by lautumn1990** [DavidAnson/markdownlint#462]
I have a problem when use Jekyll `-watch`. So I find a method use wsl2 instead of windows file system. [Speed up your builds...](https://www.forevolve.com/en/articles/2020/02/07/speed-up-your-builds-and-watch-for-changes-to-up-to-375-percent-using-this-workaround-on-wsl2-ubuntu-on-windows/)
Everything works fine, but markdownlint is not working when file over `\\wsl$\ubuntu` protocol.

**Comment by DavidAnson** [comment]
Can you show the errors from the Output panel's markdownlint tab, please? And can you try a network share without a "$" to confirm that works? Please see issue #196 for more about this and a workaround.

**Comment by DavidAnson** [comment]
I realized I don't know how you are running this, either. What tool are you using? I assumed the VS Code extension? More details would be helpful.

**Comment by lautumn1990** [comment]
Sorry, I confused  `markdownlint` with `vscode-markdownlint`. Yes, I have a problem when use the VS Code extension.

DavidAnson/vscode-markdownlint#196 worked for me, when I use `net use s: \\wsl$\ubuntu`. Thanks a million.

Here are some pictures show the difference.

windows 
![window](https://user-images.githubusercontent.com/4597231/142123705-f7eb1659-9cd9-4379-96be-c08a932d0a19.jpg)

\\wsl$\ubuntu
![\\wsl$](https://user-images.githubusercontent.com/4597231/142123848-dc5461ee-760e-4175-bbc2-38d4010cc412.jpg)

net use s: \\wsl$\ubuntu
![net use](https://user-images.githubusercontent.com/4597231/142123918-6d7153a2-9963-4a4e-a2c1-8ecfad5361f2.jpg)

problems panel
![problems pannel](https://user-images.githubusercontent.com/4597231/142123960-77f54611-daf7-4d09-888f-0db5698a09bf.jpg)

**Comment by DavidAnson** [comment]
This should work in the next version, see https://github.com/DavidAnson/vscode-markdownlint/issues/216
