### ISSUE TITLE
Counter-intuitive behavior after enable/disable + bug with ignore next line.

### ISSUE THREAD

**Issue by adithyabsk** [DavidAnson/markdownlint#468]
So I just ran into two separate issues. I was trying to disable an error for a really long iframe embed that I am including in my markdown but was running into all sorts of trouble. I think I was dealing with two separate bugs which is what made it all the more confusing

It seems that if you do the following, it re-enables all the previous ignored rules including deprecated rules such as MD002.

```md
<!-- markdownlint-disable -->
<iframe>Some really long iframe snippet</iframe>
<!-- markdownlint-enable -->
```

If you instead try to use disable next line in the presence of front-matter, the line does not actually get disabled since it is not offset in the code by the length of the front matter. (I put together a pull request for this issue https://github.com/DavidAnson/markdownlint/pull/469)

```md
<!-- markdownlint-disable-next-line -->
<iframe>Some really long iframe snippet</iframe>
```

**Comment by adithyabsk** [comment]
https://github.com/DavidAnson/markdownlint/pull/469

**Comment by nschonni** [comment]
https://github.com/DavidAnson/markdownlint#configuration explains that you need to `capture` first if you want to restore the same ruleset

**Comment by adithyabsk** [comment]
> explains that you need to capture first if you want to restore the same ruleset

Ah, you know what. Now that I've spent some time running through the code base re-reading that section makes a lot more sense. Don't think the wording could be made any clearer--I just missed the capture example.

**Comment by DavidAnson** [comment]
Glad you got this sorted out! If there's an example of something not working, please show it and I'll have a look.

**Comment by DavidAnson** [comment]
I think that's what you did with #469?

**Comment by adithyabsk** [comment]
Yep, I was just typing out a message.

**Comment by DavidAnson** [comment]
Closing this, applying the PR in #469.
