### ISSUE TITLE
Using ES modules in custom rules

### ISSUE THREAD

**Issue by pxl9588** [DavidAnson/markdownlint#477]
Is it possible to use ES module in custom rules? I’m running into this error when I use `const urlExist = require(‘url-exist’);`:

> Must use import to load ES module

When I use `import urlExist from ‘url-exist’` I get

> Cannot use import statement outside of a module

When I change the custom rule to a .mjs I get: 

> Property ‘names’ of custom rule at index 0 is incorrect

I believe that happens because the rules are imported by markdowlint by `require`.

Is there a work around for this?

**Comment by DavidAnson** [comment]
This is not supported currently for the reasons you outline. It may be as simple as changing from require to import, but my other experiences incorporating ESM suggest otherwise. I'll have a look at this for the next round of updates, thanks!

**Comment by DavidAnson** [comment]
To clarify, while your rule needs to be CommonJS, it should be able to use an import expression to pull in an ESM dependency. Because that is an asynchronous operation, it would need to take advantage of the new support for asynchronous custom rules. (Which is only available in the library for now; I am rolling it out to CLI2 and the VS Code extension soon.)

**Comment by DavidAnson** [comment]
Which is what you asked about, so yes, I think that's the workaround! :)

**Comment by pxl9588** [comment]
Sorry I’m advance,I’m not very familiar with this.

As far as I understand I can’t use import in a CommonJS file because it needs to be a module. So right now I don’t have a way to use the url-exist package. Did you mean there currently is a workaround or that it will be available in future releases?

**Comment by DavidAnson** [comment]
Docs: https://nodejs.org/api/esm.html#import-expressions

Example: https://github.com/DavidAnson/markdownlint/commit/05b9e6e43c8924beb932bebb8d93d657dd49a306

**Comment by DavidAnson** [comment]
That should work today. And since you are planning to use an asynchronous function (network access), you already needed the new support for asynchronous custom rules.

**Comment by pxl9588** [comment]
Ah right so the error isn’t about it being CommonJS, it’s about it being a module.
 Which brings back the original problem,
“Cannot use import statement outside a module”. Once it’s a module markdownlint can’t ‘require’ the custom rules.cjs any more.

**Comment by DavidAnson** [comment]
Not an import statement, an import expression. Check the docs I link to again - I think this should work.

**Comment by DavidAnson** [comment]
I wrote a simple custom rule that imports an ESM module to make sure this works like I claim: https://github.com/DavidAnson/markdownlint/blob/next/test/rules/validate-json.js

**Comment by pxl9588** [comment]
I was also having trouble with the async so this is a great example, I will give it a try. Thank you!

**Comment by pxl9588** [comment]
Is there something I have to enable to allow async custom rules? I followed your example but I don’t see any of the on errors printing.

**Comment by DavidAnson** [comment]
I mentioned above that asynchronous support is only released for the library so far. CLI2 should be in a few days and the VS Code extension a week or two after that.

**Comment by pxl9588** [comment]
Ah, right. Okay, I’ll keep an eye out for that. Thank you for all the help.

**Comment by DavidAnson** [comment]
I think we got this sorted out and the corresponding releases should all be out.
