### ISSUE TITLE
Trailing space in paragraph bug

### ISSUE THREAD

**Issue by thomasjbradley** [DavidAnson/markdownlint#48]
There seems to be a bug in the trailing space matching of some kind, but only errors when there’s front matter. I cannot recreate the error in the demo so it could also be related to `resultVersion: 1`.

This is the code that throws the error:

```md
---
basic-card: |
  The basic card is used to showcase the dogs that are available for adoption. It includes a button but never links itself.
---

The cards provide a way to highlight and group important information. 

```

There’s a trailing space right at the end of “information. ” and this is the error I get:

```
TypeError: Cannot read property 'match' of undefined on line 258
```

If I strip the front matter it seems to work okay.

----

**Version: 0.4.0**

**Comment by DavidAnson** [comment]
I have an idea. I'll take a look tonight. Sorry for the trouble!

**Comment by thomasjbradley** [comment]
No problem at all—thanks for being so responsive.

**Comment by DavidAnson** [comment]
I can reproduce this problem. It is related to `resultVersion`. I should have a fix tomorrow evening. I'll be releasing `0.4.1` soon with this fix. Thanks!

**Comment by thomasjbradley** [comment]
Thanks so much!
