### ISSUE TITLE
MD029 - Ordered list item prefix

### ISSUE THREAD

**Issue by wrenhal** [DavidAnson/markdownlint#49]
I have a document where I have an ordered list and I get the warning above on every item after 1.  
So if I have the following code I get the MD029 error on #'s 2, 3 and 4.  

`1. A computer or access to a computer that we can install software on. Preferably under our own user account.
2. Access to the internet.
3. A place where you can take and save notes.
4. Personal Grit`

Is this normal behavior, or is the linter not recognizing the OL properly?

**Comment by wrenhal** [comment]
Here's the full error message:
MD029/ol-prefix: Ordered list item prefix [Expected: 1; Actual: 2]     Actual is 2, 3 or 4 depending on which line I'm on.

**Comment by DavidAnson** [comment]
Could you have a look at the following issue? I think my explanation there is relevant. Please let me know if you disagree. 

https://github.com/DavidAnson/markdownlint/issues/45

**Comment by wrenhal** [comment]
OK.. So I should be able to add the following to the settings.json in VSCode:

"markdownlint.config": {
        "default": true,
        "MD029": { "style": "ordered" }
        }

And that should change those error notes.

**Comment by DavidAnson** [comment]
Glad it worked! The console error is VS Code telling you its JSON file is not perfect. Seems like the line above what you pasted needs a comma at the end.
