### ISSUE TITLE
MD034 should not trigger when link exists inside a code block

### ISSUE THREAD

**Issue by ReneRebsdorf** [DavidAnson/markdownlint#500]
Let me know if this is supposed to go into the super-linter issue tracker, but my best guess was it was relevant here.

As markdown can contain code blocks, which could include a curl or similar, a bare url is needed.
Our current workaround is to disable testing of the entire file, where we only need it excluded within code blocks.

While this test is valid if the code block is markdown, I'd say testing of MD034 inside code blocks should  be excluded, or at least validated that the code block is tagged as 'markdown'.

**Comment by DavidAnson** [comment]
Please show an example? MD034 does not warn for bare URLs in code spans, blocks, or fences as seen here: https://dlaa.me/markdownlint/#%25m%23%20Issue%20500%0A%0AText%20%60https%3A%2F%2Fexample.com%60%0A%0A%60%60%60text%0Ahttps%3A%2F%2Fexample.com%0A%60%60%60%0A%0A%20%20%20%20https%3A%2F%2Fexample.com%0A

**Comment by ReneRebsdorf** [comment]
@DavidAnson You are absolutely right! I had made a mistake in my conclusion when debugging linters as I was going through some of our file-wide disables.

Sorry for the noise - this was actually caused by a violation outside of a code block that I had missed when I was going through our md docs.
