### ISSUE TITLE
Asynchronous Rule's params.config will be overrided by other sync rules.

### ISSUE THREAD

**Issue by chriswong** [DavidAnson/markdownlint#510]
## [Source Code](https://github.com/DavidAnson/markdownlint/blob/main/lib/markdownlint.js#L505-L600):

[markdownlint.js#L505](https://github.com/DavidAnson/markdownlint/blob/main/lib/markdownlint.js#L505)

```js
    params.config = effectiveConfig[ruleName];
```
[markdownlint.js#L600](https://github.com/DavidAnson/markdownlint/blob/main/lib/markdownlint.js#L600)

```js
        const invokeRuleFunction = () => rule.function(params, onError);
```

## Reproduction

```yml
# markdownlint.yml
default: true
extends: null
MD002:
  level: 1

MD999:
  foobar: true
```

```js
const custeomRule =  {
    names: ['MD999', '...'],

    description: '...',

    tags: ['...'],

    asynchronous: true,

    function: function MD999(params, onError) {
        // params.config maybe { level: 1 }
        console.log(params.config.foobar); // undefined
        // ...
    }
}

 markdownlint({
    config,
    customRules: customRule
}, (error, results) => {});

```

**Comment by chriswong** [comment]
## Fixed Code

markdownlint.js#L505
```js
    const config = effectiveConfig[ruleName];
```

markdownlint.js#L600

```js
        const invokeRuleFunction = () => rule.function({ ...params, config }, onError);
```

**Comment by DavidAnson** [comment]
This is a good find, thank you! I started freezing the `params` object to prevent issues like this, but did not catch this scenario: https://github.com/DavidAnson/markdownlint/commit/5f0040679d2f18afa977b64f16b0a50302eede48.

I'm curious why I never saw this during development - and whether that means it will be hard to test for.

**Comment by DavidAnson** [comment]
(The synchronous part of custom rules is deliberately (supposed to be) deterministic, so I'm surprised by this.)

**Comment by DavidAnson** [comment]
Nope, I see this affects even the "synchronous" path. I'm adding tests now and hope to fix this shortly. Sorry about the error, I don't see a good workaround at the moment! How urgent is this and are you using any dependent projects like CLI/CLI2, VS Code extension, etc.?

**Comment by DavidAnson** [comment]
I thought of a workaround: Also create a synchronous rule that does nothing and pass the parameter to it and then share that parameter value across the two rules either in the same file or via a shared import.

**Comment by chriswong** [comment]
> Nope, I see this affects even the "synchronous" path. I'm adding tests now and hope to fix this shortly. Sorry about the error, I don't see a good workaround at the moment! How urgent is this and are you using any dependent projects like CLI/CLI2, VS Code extension, etc.?


Yes, i'm working on my vscode extension, for linting html/style/script code in markdown:

<img width="653" alt="image" src="https://user-images.githubusercontent.com/165639/159703465-b74e3ad8-bbc2-4997-8f86-bb03e09a5324.png">

So, we'd like to know when the next version could be published?

**Comment by DavidAnson** [comment]
Are you consuming the library directly or are you integrating with https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint

**Comment by chriswong** [comment]
We're consuming the library directly.

**Comment by DavidAnson** [comment]
Good, the library comes out first. Did you try the workaround I mention above? It should unblock you for now.

**Comment by chriswong** [comment]
> 

Yes, it works.
