### ISSUE TITLE
Possible to disable line length for normal lines but enforce for headers/code blocks?

### ISSUE THREAD

**Issue by wgehring-ml** [DavidAnson/markdownlint#514]
Title says it all, really. I see ways to disable enforcing `MD013/line_length` on headers/headings, code blocks, and tables but no way to enforce on headers/code blocks and ignore elsewhere.

Is there a way to do this already, and if not could it be added?

**Comment by DavidAnson** [comment]
See the docs: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md013

heading_line_length lets you set the length for headings

headings let's you disable for headings

Similar for code and tables (though you can't control table length, just disable).

**Comment by wgehring-ml** [comment]
Yes, I saw that, but there's no way to disable the check for normal lines and enforce it on others. As far as I can tell, the closest I can get to actually disabling it is to guess how long my general content lines may become and set the `line_length` property inside of `MD013` to be larger than that.

If that's the answer, that's all well and good but since the rule is using Regex to enforce line length I worry about increasing that value to the point where the rule slows down or freezes.

**Comment by DavidAnson** [comment]
I've never heard of the RegExp being a problem here. As long as your lines are reasonable lengths, it should bail out when they end anyway.
