### ISSUE TITLE
Should I NOT be using this for reStructured Text (Sphinx)?

### ISSUE THREAD

**Issue by FrightRisk** [DavidAnson/markdownlint#522]
I have been using this for a while and it seem to work for catching errors, but it doesn't like things like headings with over and under tags, which is standard ex:

############
Heading One
############

It says "first line heading should be a top level heading"

**Comment by DavidAnson** [comment]
The CommonMark specification supports two syntaxes for headings and what's shown above is neither of them. This library is intended for CommonMark syntax and the reported issue is correct in that context. Using this library for other syntaxes can result in "false" issues like this. You may wish to turn such rules off in your configuration.

See sections 4.2 and 4.3: https://spec.commonmark.org/0.30/
