### ISSUE TITLE
Feature Request: markdownlint-disable-line

### ISSUE THREAD

**Issue by Zamiell** [DavidAnson/markdownlint#524]
Hello, and thanks for the excellent linter!

Currently, markdownlint has the `disable-next-line` directive, which is quite a handy feature!

For example, the `README.md` file gives the following example:

```md
<!-- markdownlint-disable-next-line no-space-in-emphasis -->
deliberate space * in * emphasis
```

Unfortunately, this not the greatest example, because if you have Prettier installed (which many projects do nowadays), as soon as you hit `Ctrl + s` in VSCode to save the file, Prettier will automatically reformat it to the following:

```md
<!-- markdownlint-disable-next-line no-space-in-emphasis -->

deliberate space * in * emphasis
```

And now the comment will no longer apply.

This happened to me earlier today. Being familiar with [ESLint](https://eslint.org/), I intuitively knew how to fix the problem, so I tried this:

```md
deliberate space * in * emphasis <!-- markdownlint-disable-line no-space-in-emphasis -->
```

But unfortunately, that doesn't work, because surprisingly, markdownlint only supports `disable-next-line` and not `disable-line`.

Can this please be added?

**Comment by DavidAnson** [comment]
You can do this with disable/restore as shown in the documentation: https://github.com/DavidAnson/markdownlint#configuration

**Comment by Zamiell** [comment]
@DavidAnson Thanks for the quick response.
I see in the docs that it is possible to do disable/restore, but this is pretty cumbersome.
It also is not very DRY - programmers will have to duplicate the code on multiple lines.
It would be better UX and less maintenance for end-users if this linter could also have the `disable-line` feature, which would allow programmers to specify the directive and associated rule exactly one time.

**Comment by DavidAnson** [comment]
In my opinion, "next line" is better than "line" because it is clear, it doesn't interfere with the content, and it doesn't risk creating too-long lines. The problem is that Prettier breaks that and needs to be worked around. It would be nice if Prettier were more respectful here, but I can look into adding "line" as an alternative.

**Comment by DavidAnson** [comment]
I know of just one other Markdown linting tool in the Node ecosystem. I think they could handle it if they wanted to. :)

**Comment by Zamiell** [comment]
Well, what about CSpell? Surely, many people need to spell check their markdown documents. If you're not familiar with it, it has syntax like this:

```md
It is common to misspell the word absence as "absense". <!-- cspell:disable-line absense -->
```

That would have to be added as well. And what if some other extension for spell checking started to get more popular than CSpell or markdownlint? Should that be added too?

It seems pretty weird for Prettier to be in the business of hard-coding popular tools, as that would be a maintenance burden, especially for a hypothetical niche feature like this.
