### ISSUE TITLE
Should MD041 be ignored for Github Wiki markdown?

### ISSUE THREAD

**Issue by rcdailey** [DavidAnson/markdownlint#530]
Applies to Github Wiki, but also Azure Devops wiki too. I'm sure there are others. These types of wikis like to make the first heading automatic based on the filename. In these cases, it doesn't make sense to put a top-line heading because it would look weird.

In these cases, is it advised to disable this lint rule?

**Comment by DavidAnson** [comment]
Yes, that sounds appropriate. Feel free to disable any of the rules that don't suit you!

**Comment by rcdailey** [comment]
Thank you!
