### ISSUE TITLE
MSBuild-integrated Markdown linting for .NET projects

### ISSUE THREAD

**Issue by Piedone** [DavidAnson/markdownlint#541]
(I'd have opened a Discussions thread for this if that feature would be enabled. Sorry if this is not a good place for such show and tell announcements.)

Something curious you might like: In our [Lombiq Node.js Extensions project](https://github.com/Lombiq/NodeJs-Extensions) we've added Markdown linting, utilizing markdownlint too, in a way that it automatically runs as part of an MSBuild build process. This means that for .NET projects, lining for Markdown files happens automatically, as part of the normal build, and you get linter errors as build errors. This is how .NET static code analysis works as well, so this way, Markdown linting fits seamlessly into the .NET developer experience. See [docs here](https://github.com/Lombiq/NodeJs-Extensions/blob/dev/Lombiq.NodeJs.Extensions/Docs/Markdown.md).

What do you think?

**Comment by DavidAnson** [comment]
This sounds awesome! If you want to send a PR to add a link to the "Related "section of the README, that may help spread the word. (Please have a look at CONTRIBUTING.md before doing so.)

**Comment by Piedone** [comment]
Great idea, thanks, will do that.
