### ISSUE TITLE
MD022: Split into two separate configurations to allow enforcing only one of lines_above/lines_below

### ISSUE THREAD

**Issue by MicahZoltu** [DavidAnson/markdownlint#546]
https://github.com/DavidAnson/markdownlint/blob/main/README.md#md022---headings-should-be-surrounded-by-blank-lines

Unless I'm missing something, it doesn't appear I can configure markdownlint to enforce `lines_above` while not enforcing `lines_below`.  IIUC, I can only either turn the whole rule off, or configure linting on both.  I would like to enforce `lines_above` but *not* enforce `lines_below`.

**Comment by DavidAnson** [comment]
Can you explain more, please? It sounds like you want to ensure there is exactly one line above the heading, but do not care if there are 0, 1, 10, etc. lines below it and if that amount varies within the same file? Why?

**Comment by MicahZoltu** [comment]
This is correct.  There are 3 reasons one may want to do this:

1. If you are only linting for compatibility, then `lines_above` is necessary for maximum rendering engine compatibility while `lines_below` is not.
2. In some contexts, having 0 lines below makes sense, such as when you have a fairly concise document with a single paragraph per heading.  In other contexts, having 1 line below makes sense, such as when the content within each section is multiple paragraphs.
3. Within a given document, it may make sense to have top level headings (# and ##) with lines below while deeply nested headings it may make sense to have 0 lines below.
