### ISSUE TITLE
Rules.md does not show up in chrome

### ISSUE THREAD

**Issue by Reissner** [DavidAnson/markdownlint#551]
Very strange: your markdown toes not show up in chrome, but works fine in firefox.

**Comment by DavidAnson** [comment]
More information, please. Are you reporting that the GitHub web site does not render at all in Chrome? Which version? What URL?

**Comment by DavidAnson** [comment]
This URL loads and renders fine for me in Chrome: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

I suspect a browser extension on your side is breaking something.
