### ISSUE TITLE
MD031/MD032 triggered for HTML comment in code block in list

### ISSUE THREAD

**Issue by nschonni** [DavidAnson/markdownlint#563]
https://dlaa.me/markdownlint/#%25m-%20%E4%B8%8D%E8%A6%81%E5%BC%BA%E8%BF%AB%20Web%20%E5%BC%95%E6%93%8E%E6%9E%84%E5%BB%BA%E4%B8%8D%E9%9C%80%E8%A6%81%E7%9A%84%20DOM%EF%BC%8C%E4%B8%80%E7%A7%8D%E7%AE%80%E5%8D%95%E7%9A%84%E2%80%9Chack%E2%80%9D%E7%9A%84%E6%96%B9%E5%BC%8F%E6%98%AF%E6%8A%8A%E4%BD%A0%E7%9A%84%20HTML%20%E7%95%99%E5%9C%A8%E6%96%87%E6%A1%A3%E9%87%8C%EF%BC%8C%E4%BD%86%E6%98%AF%E5%9C%A8%E5%A4%96%E5%B1%82%E5%8C%85%E8%A3%B9%E6%B3%A8%E9%87%8A%E3%80%82%0A%0A%20%20%60%60%60html%0A%20%20%3Cdiv%20id%3D%22foo%22%3E%3C!--%0A%20%20%20%20%3Cdiv%3E%20...%0A%20%20--%3E%3C%2Fdiv%3E%0A%20%20%60%60%60%0A%0A-%20%E5%BD%93%E6%96%87%E6%A1%A3%E7%9A%84%E4%B8%80%E9%83%A8%E5%88%86%E9%9C%80%E8%A6%81%E8%A2%AB%E6%B8%B2%E6%9F%93%E6%97%B6%EF%BC%8C%E5%8A%A0%E8%BD%BD%E8%A2%AB%E6%B3%A8%E9%87%8A%E7%9A%84%20HTML

Probably and odd edge case in the parsing.

~~~md
- 不要强迫 Web 引擎构建不需要的 DOM，一种简单的“hack”的方式是把你的 HTML 留在文档里，但是在外层包裹注释。

  ```html
  <div id="foo"><!--
    <div> ...
  --></div>
  ```

- 当文档的一部分需要被渲染时，加载被注释的 HTML
~~~

This get's autofixed to

~~~md
- 不要强迫 Web 引擎构建不需要的 DOM，一种简单的“hack”的方式是把你的 HTML 留在文档里，但是在外层包裹注释。

  ```html
  <div id="foo"><!--

    <div> ...
  --></div>

  ```

- 当文档的一部分需要被渲染时，加载被注释的 HTML
~~~

**Comment by DavidAnson** [comment]
Simplified: https://dlaa.me/markdownlint/#%25m%23%20Issue%20563%0A%0A-%20item%0A%0A%20%20%60%60%60html%0A%20%20%3C!--%0A%20%20--%3Ex%0A%20%20%60%60%60%0A%0A-%20item%0A
