### ISSUE TITLE
False positive MD053 for image inside link

### ISSUE THREAD

**Issue by janosh** [DavidAnson/markdownlint#571]
I'm seeing a false-positive when wrapping referenced image inside a link:

```md
[![Binder]](test)

[Binder]: https://mybinder.org/badge_logo.svg
```

 ![Screen Shot 2022-08-31 at 20 57 03](https://user-images.githubusercontent.com/30958850/187828593-721d54ab-fb8b-4930-b137-adf5c8550445.png)

**Comment by DavidAnson** [comment]
FYI, the equivalent syntax `[![Binder][]](test)` should not trigger a violation in the current version.

**Comment by janosh** [comment]
This is not in fixed in https://github.com/DavidAnson/vscode-markdownlint/tree/next yet, correct?

**Comment by DavidAnson** [comment]
Right, it's fixed for the next release of the library which will be part of the next release of the extension. But neither exists yet.

**Comment by janosh** [comment]
Is anything blocking a new release? Still encountering this issue on a regular basis.

**Comment by DavidAnson** [comment]
Nothing blocking, though I am still working through some other issues that have been reported.
