### ISSUE TITLE
MD011 flagging content in code span

### ISSUE THREAD

**Issue by nschonni** [DavidAnson/markdownlint#572]
https://dlaa.me/markdownlint/#%25m-%20Chaque%20%C3%A9l%C3%A9ment%20de%20%60window.frames%60%20est%20un%20pseudo%20tableau%20repr%C3%A9sentant%20l'objet%20%5Bwindow%5D(%2Fen%2FDOM%2Fwindow)%20correspondant%20au%20contenu%20de%20la%20%20%5B%5C%3Cframe%3E%5D(%2Fen%2FHTML%2FElement%2Fframe)%20ou%20%5B%5C%3Ciframe%3E%5D(%2Fen%2FHTML%2FElement%2Fiframe)%20%2C%20et%20non%20au%20DOM%20element%20(i)frame%20(ex.%2C%20%60window.frames%5B%200%20%5D%60%20%C3%A9quivaut%20%C3%A0%20%60document.getElementsByTagName(%20%22iframe%22%20)%5B%200%20%5D.contentWindow%60).%0A

**Comment by DavidAnson** [comment]
Simplified example and repro: https://dlaa.me/markdownlint/#%25m%23%20Issue%20572%0A%0ASimplified%3A%20Text%20(text%20%60func()%5Bindex%5D%60)%20text%0A%0ANo%20code%3A%20Text%20(text()%5Bindex%5D%20text%0A
