### ISSUE TITLE
Feature request: Neovim/Lua-based plugin 

### ISSUE THREAD

**Issue by GaelanVenturi** [DavidAnson/markdownlint#574]
Hello there, 
Not sure if this is the place to request it. Are there plans in the future to include this as part of a vim/neovim plugin at all? I've used it on VSCode, and like the **lint on save** feature, but Neovim is my primary editor, and I would like to have the same for it if possible.  

Please let me know if there's a better way to request this. Thank you.

**Comment by DavidAnson** [comment]
This is not the right place to ask for that and I can say that I have no plans to do so. If it were to be done, it would not happen in this repository and would not need my involvement, approval, or knowledge. Unfortunately, I don't know a better place to post this.

**Comment by GaelanVenturi** [comment]
Thank you
