### ISSUE TITLE
Linting DRY markdown for Jekyll pages (resolve "include_relative")

### ISSUE THREAD

**Issue by pbronneberg** [DavidAnson/markdownlint#578]
For markdown pages that we render through Jekyll, we have moved common references to a `references.md` file.
In all pages, the common references are included like shown in this example:

```MARKDOWN
I want to use a reference defined single file and still use [a linter][markdown-lint]

{% include_relative references.md %}
```

An example of `references.md`:

```MARKDOWN
[markdown-lint]: https://github.com/DavidAnson/markdownlint

[some-other-link]: https://www.github.com
```

Since the cross-references checks were introduced recently, this leads to `MD053` linting errors: 
"MD053/link-image-reference-definitions: Link and image reference definitions should be needed [Unused link or image reference definition: \"markdown-lint\"]"

Any hints to overcome this without disabling `MD053`?

**Comment by DavidAnson** [comment]
In situations like this, I recommend linting the final Markdown output (rather than the pieces that are used to create it).

**Comment by pbronneberg** [comment]
Thanks for the reply! Will see where we can apply that approach.

As far as I've investigated now, Jekyll does not provide an option to just combine the markdown, will create a question on the Jekyll repo. In the meantime, we'll decide to either script this ourselves or ignore the errors.
