### ISSUE TITLE
GitHub Emoji's corrected in markdown file, exception for these? 

### ISSUE THREAD

**Issue by GaelanVenturi** [DavidAnson/markdownlint#589]
Hello, 
VS code with markdownlint changes emojis with a "colon-before-and-after" method to have only one colon. For example, `:tada:` is corrected to `:tada`. Is this addressable, or will it violate one of the other rules? 

Thank you, 

Gaelan Venturi

**Comment by DavidAnson** [comment]
What rule is applying a correction? It doesn't seem to be a violation: https://dlaa.me/markdownlint/#%25m%23%20Issue%20589%0A%0A%3Atada%3A%0A

Can you show an example, please?

**Comment by nschonni** [comment]
Is it because it's at the end of a heading? https://dlaa.me/markdownlint/#%25m%23%20%3Atada%3A%0A%0A%3Atada%3A%0A%0A

**Comment by nschonni** [comment]
You'd need to updated https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md026---trailing-punctuation-in-heading to allow `:` instead of the default if that's what you're running into

**Comment by GaelanVenturi** [comment]
@nschonni You are correct; it's because it is at the end of a heading, my mistake.

**Comment by nschonni** [comment]
Not a mistake, just an edge case 🙂

**Comment by DavidAnson** [comment]
Duplicate of #457
