### ISSUE TITLE
Support for presets?

### ISSUE THREAD

**Issue by brendo** [DavidAnson/markdownlint#59]
With the latest changes in 0.5.0 that introduce `extends`, I'm wondering what your thoughts are about supporting a concept of presets? This is similar to what [ESLint](http://eslint.org/docs/developer-guide/shareable-configs#using-a-shareable-config) offers and I think it'd be a useful addition this tool.

For some background, we currently maintain several projects that have `.markdownlint.json` files. For us, it'd be great to centrally define these rules, and then just pull that dependency into each project. We could then better communicate to our team what has changed and why :)

**Comment by DavidAnson** [comment]
Here's how I think you would do that today: Create desired rules in JSON file, put in npm package, publish, reference that package from each of your projects, "extend" it from each of those .markdownlint.json files (by relative path into node_modules). Would this work for you? If not, what's missing?

**Comment by DavidAnson** [comment]
If that works for you, I'll close this issue in a day or two.

**Comment by brendo** [comment]
Yes sorry, that solution is definitely workable, not pretty, but it'll work!

**Comment by DavidAnson** [comment]
How is it any uglier than what ESLint does? If you want, you can do the require/exports thing here as well. Only difference I see is the need for a require statement, but that seems trivial. Am I missing something?

**Comment by brendo** [comment]
ESLint supports specifying the package as simply a name, not a relative path, so you could do something like this:

```json
{
  "extends": "markdownlint-config-example",
  "default": true
}
```

ESLint does a nice thing where `example` is also possible, as it'd automatically prepend `eslint-config-` when resolving the config.

If I understand the solution suggested, markdownlint would instead require:

```json
{
  "extends": "./node_modules/markdownlint-config-example",
  "default": true
}
```

Very minor difference 😃

**Comment by DavidAnson** [comment]
Yes, that was my original suggestion!

If you're willing to do this in code, you can create a package that exports whatever config you want and then do something like:

```js
var config = {
    extends: require("my-config-module")
}
```

Or even:

```js
{
    extends: require("my-config-module").mySpecialConfig
}
```

All of which works today. :)

**Comment by brendo** [comment]
Excellent, I missed that, thanks for showing an example! Looks like I've got some configs to consolidate now 😄

**Comment by DavidAnson** [comment]
Great! If you feel like starting a library of configs that other people could reuse in their own projects, I'll link to it from the README. No pressure, just an idea I had. :)
