### ISSUE TITLE
Add an option to disable all Prettier-related rules at once

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [DavidAnson/markdownlint#592]
I often use Markdownlint and Prettier together in the same repo, both with editor extensions. When using Prettier, there's no need for Markdownlint to check formatting rules. I find myself disabling at least `no-hard-tabs` and `line-length`, and sometimes more if the Prettier config is customized (docs ref: https://github.com/DavidAnson/markdownlint/blob/main/doc/Prettier.md).

Can we have a one-line option in for Markdownlint configs that disables all formatting rules that would conflict with Prettier? For reference, the equivalent in ESLint-land is [`eslint-config-prettier`](https://github.com/prettier/eslint-config-prettier).

* Example repo: https://github.com/JoshuaKGoldberg/template-typescript-node-package/tree/19d02d06310097e867344714b36300776f12721a.
* Markdownlint configuration: https://github.com/JoshuaKGoldberg/template-typescript-node-package/blob/19d02d06310097e867344714b36300776f12721a/.markdownlint.json

If the answer to the issue is to disable all rules with certain tags, then this might be a docs request, not a feature request. 😄

**Comment by DavidAnson** [comment]
It sounds like you want to create a style for use with Prettier?

https://github.com/DavidAnson/markdownlint/tree/main/style

**Comment by JoshuaKGoldberg** [comment]
Sure, that would work! I'm having a hard time finding docs on inheriting those built-in styles though. Is there more than what's under https://github.com/DavidAnson/markdownlint#optionsconfig?

**Comment by DavidAnson** [comment]
You could have your configuration file "extends" a predefined style?

**Comment by JoshuaKGoldberg** [comment]
Yes, that'd be great. But I don't see any docs on this repo that explain how to do that. I'll file a separate issue for docs and send in a Prettier PR for this one 😄 thanks!
