### ISSUE TITLE
Docs: document how to extend from a built-in style

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [DavidAnson/markdownlint#593]
Following #592: https://github.com/DavidAnson/markdownlint#optionsconfig mentions that you can extend from premade styles and includes an example of how to do so with a CommonJS `require()`. But, the docs don't show:

* How to do so in a JSON file
* How to extend from one of the prebuilt styles in https://github.com/DavidAnson/markdownlint/blob/main/style

For example, I tried this in a JSON config file:

```json
{
  "extends": "markdownlint/style/all.json"
}
```

...but that didn't do anything.

Could this be documented, please? I'm happy to send in docs myself... if someone tells me how to do these things 😄

**Comment by DavidAnson** [comment]
In general, an explicit path or a module identifier can be specified. In this case, the somewhat recent addition of `package.json/exports` may block the syntax you show. Module resolution will also depend on the context in which it is invoked. The most reliable mechanism, may be to copy one of the example styles into your project and reference it from there.
