### ISSUE TITLE
warning and error level?

### ISSUE THREAD

**Issue by Mister-Hope** [DavidAnson/markdownlint#602]
Now it seems that markdownlint-cli will fail whenever a rule is failed, But in some cases, we may want theme show as warnings instead of errors failing ci.

Can we add `'error'` `'off'` `'warning'` support besides `true` or `false`, and support `level` for object format with `'error'` and `'warning'`?

**Comment by nschonni** [comment]
Duplicate of https://github.com/DavidAnson/markdownlint/issues/254
