### ISSUE TITLE
Add mdn/content repo to smoke tests

### ISSUE THREAD

**Issue by nschonni** [DavidAnson/markdownlint#607]
The repo now has Markdownlint enabled https://github.com/mdn/content and is a fair sized repo with some unique things. Downsides are that the custom generator https://github.com/mdn/yari does include some template extensions that aren't CommonMark complaint, and neither is the anchor linking schema.

The parallel i18n repo https://github.com/mdn/translated-content may also be an interesting one later, but the full Markdownlint CI hasn't landed yet.

**Comment by DavidAnson** [comment]
@nschonni, FYI that I claim the 3 violations newly reported in that repo for `next` branch are legitimate issues (two have extra "()" wrappers, one a trailing ")"): https://github.com/DavidAnson/markdownlint/commit/d352d4ece1e3222c9f9749ca40892a2816ec0d65#diff-04131531c5442e3c2d168cc915265d805f1691fbc7863479bd12a8f57256cf46

**Comment by DavidAnson** [comment]
(To be fair, I fixed the other things this turned up because they were legitimate bugs in MY code. :) This was a good addition!)

**Comment by nschonni** [comment]
Not sure if I caught them all, but submitted https://github.com/mdn/content/pull/22991
The repo has an auto-cleanup job and a commit hook, so likely something malformed that had a bad fix before

**Comment by DavidAnson** [comment]
Looks good!

**Comment by nschonni** [comment]
Upstream PR landed, so you can probably clean up the ignores again

**Comment by nschonni** [comment]
And I guess this can be closed if you've added it now, unless you want to keep it open to track the `translate` repo too

**Comment by DavidAnson** [comment]
This issue will be closed automatically when I merge next branch into main.
