### ISSUE TITLE
MD052 triggering in code span inside link

### ISSUE THREAD

**Issue by nschonni** [DavidAnson/markdownlint#619]
This example shows it being flagged in a link, but not the same code span on its own

https://dlaa.me/markdownlint/#%25m%5B%60WebGLRenderingContext.uniform%5B1234%5D%5Buif%5D%5Bv%5D()%60%5D(%2Fen-US%2Fdocs%2FWeb%2FAPI%2FWebGL2RenderingContext%2Funiform)%0A%0A%60WebGLRenderingContext.uniform%5B1234%5D%5Buif%5D%5Bv%5D()%60

**Comment by DavidAnson** [comment]
This may already be fixed by: https://github.com/DavidAnson/markdownlint/commit/c333976a4416e1a80f767bf82d117bb82e2f8b47

**Comment by nschonni** [comment]
OK, I couldn't remember if there the demo site used the latest `next` code or not, so I opened it when I saw it there still. That might be an interesting troubleshooting step, if there was a demo copy that used the `next` code to see if there are fixed things when reporting

**Comment by DavidAnson** [comment]
The demo site does not give you a way to try older or newer versions yet. I thought about this and know how I might do it, but it hasn't bubbled to the top yet.

**Comment by nschonni** [comment]
I'm guessing you already have a custom site setup that has the current demo site, so you could setup https://davidanson.github.com/markdownlint to point to the `demo` folder in `next`

**Comment by DavidAnson** [comment]
I think GitHub raw sets content type to text so people can’t host directly out of the repo. It’s been a while, that may not be true now.

**Comment by nschonni** [comment]
From https://github.blog/2022-08-10-github-pages-now-uses-actions-by-default/ you could probably use https://github.com/actions/starter-workflows/blob/main/pages/static.yml with a tweak to the path to be used

**Comment by DavidAnson** [comment]
What I'd really like is a way to point to any version of the script. Then I just hardcode the list of release tags and suddenly the demo site can load anyone of them (including next). A simple redirector wouldn't be hard to add to my web site, but it wouldn't natively work for anyone wanting to run the demo locally. That said, this is a pretty niche scenario, so I might only enable it via query string parameter anyway, and this wouldn't really matter. Like I said, it just hasn't been compelling yet.

**Comment by nschonni** [comment]
https://raw.githack.com/ might work for you but when I tried priming the cache with some of the JS files for https://raw.githack.com/DavidAnson/markdownlint/next/demo/default.htm there were a few 404s for some minfied helpers that aren't in the tree
