### ISSUE TITLE
Add an option allowed_languages to the fenced-code-language

### ISSUE THREAD

**Issue by regseb** [DavidAnson/markdownlint#627]
Add an option _allowed_languages_ to the [_fenced-code-language_](https://github.com/DavidAnson/markdownlint/blob/a6489ac/doc/Rules.md#md040) rule to define the allowed languages. With this option, `markdownlint` will be able to check:

- name consistency (`javascript` / `js`);
- case (`html` / `HTML`);
- typos (`markdown` / `markdonw`)
- unsupported languages (`json` / `jfather`).

**Comment by DavidAnson** [comment]
I think this has already been done for the next version here: https://github.com/DavidAnson/markdownlint/commit/01ba757d3a9288f2ccd94a6241762a943bdb85f6

**Comment by regseb** [comment]
I didn't see that there was already the #608 report. 😞

I looked at the commit, the languages are case insensitive. You could add `ignoreCase` option to check case (`html` / `HTML`).

**Comment by DavidAnson** [comment]
Since the new feature hasn't gone out yet, what do you folks think about making it case sensitive? If someone really wants to be able to use HTML and html, they could always add both to the allow list.

**Comment by regseb** [comment]
It's better if the rule is case sensitive because it has more possibilities.

**Comment by nschonni** [comment]
I think the default of case sensitivity makes sense, but I like the idea of `ignoreCase`. I don't think I'd see people wanting to put all permutations of the casing if there is a large code base. Either they'll want just one style + plus a list, or just a list, but "I don't care if you camelCase it or whatever" approach

**Comment by DavidAnson** [comment]
My thinking is to except the PR to make this case sensitive by default and then wait to see if there are really people who want to allow a mix of case and aren't willing to specify which ones. Does anyone really want HtMl?

**Comment by DavidAnson** [comment]
*accept

**Comment by nschonni** [comment]
I think skipping the `ignoreCase` might be an easy sell, if the casing would be fixable based on the allowed values. That would probably add a bunch of complication though
