### ISSUE TITLE
frontmatter should support TOML in addition to YAML

### ISSUE THREAD

**Issue by terinjokes** [DavidAnson/markdownlint#63]
Some blogging engines, such as hugo, support TOML in their frontmatter. However, MD041 only support detecting properties in YAML frontmatter.

```markdown
+++
title = "Example Title"
date = "2017-06-18T00:00:00Z"
+++
```

**Comment by DavidAnson** [comment]
Custom front matter is already supported: https://github.com/DavidAnson/markdownlint/blob/master/README.md#optionsfrontmatter

But TOML looks similar enough to YAML that I might as well support it natively.
