### ISSUE TITLE
support for frontmatter in the middle of the text

### ISSUE THREAD

**Issue by igalic** [DavidAnson/markdownlint#65]
Some of our markdown documents have frontmatter, but also… "middle-matter"

that frontmatter uses the exact same style, and usually declares (sub) sections:

```
---
section: faq
---
```

is there any way we can rig the frontmatter config to — optionally — support that, too?

**Comment by igalic** [comment]
i've committed a fix to one of our blogs, referencing this so you can see what it looks like!

**Comment by DavidAnson** [comment]
Is middle-matter a real thing, or something custom with your process? I have an idea and may implement this regardless, but would feel better about the investment if I knew it was a widespread need. :)

**Comment by igalic** [comment]
the "engine" we use is metalsmith

and now i'm trying to remember where else i've seen this

**Comment by DavidAnson** [comment]
I've done research on two occasions and can't find any documentation/specification that describes the use of front matter in the *middle* of a file as shown above.

* Metalsmith (the tool you use) says "at the top", http://www.metalsmith.io/
* Middleman (referenced by Metalsmith) also says "top", https://middlemanapp.com/basics/frontmatter/
* jekyll (seemingly the origin of front matter) says "front matter must be the first thing in the file", https://jekyllrb.com/docs/frontmatter/

While I could guess at how "middle matter" is expected to behave, it seems like it's rare in the wild AND you have a confirmed workaround in the form of `markdownlint-disable`. Therefore, I'm closing this issue for now.

If you find a specification and can point to significant use in practice, I'm happy to revisit this.

Thanks!

**Comment by edobry** [comment]
I know this was closed years ago but I have a related usecase, namely ignoring a generated section at the end of the file. My document is a README for a Terraform module, which has some handwritten Markdown, and then a section which gets filled in by a tool called [`terraform-docs`](https://terraform-docs.io/) in between these markers:

```markdown
<!-- BEGIN_TF_DOCS -->
<!-- END_TF_DOCS -->
```

The generated Markdown is not compliant with my rules and it would be difficult to make it be so, and not really important. Right now i'm able to make this work with the following format:


```markdown
<!-- markdownlint-disable -->
<!-- BEGIN_TF_DOCS -->
<!-- END_TF_DOCS -->
<!-- markdownlint-restore -->
```

but it would be quite nice to be able to configure markdownlint to instead match on those existing markers.

**Comment by DavidAnson** [comment]
See #249
