### ISSUE TITLE
MD026 Breaks GitHub emoji

### ISSUE THREAD

**Issue by dserodio** [DavidAnson/markdownlint#653]
I have a few headers that end in GitHub Emoji, eg.:

`# Known Issues :bug:`

Which GitHub renders as:

# Known Issues :bug:

However, MD026 is "fixing" this as:

`# Known Issues :bug`, which is not an actual fix, since it renders as:

# Known Issues :bug

**Comment by DavidAnson** [comment]
GitHub emoji are not part of the CommonMark specification. If you used a markdown-it plugin that recognized them, I think this issue would not get flagged.

**Comment by DavidAnson** [comment]
This might work based on the description: https://www.npmjs.com/package/markdown-it-emoji

**Comment by DavidAnson** [comment]
Duplicate of linked issue.
