### ISSUE TITLE
New version, please?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [DavidAnson/markdownlint#669]
Hi - I know these issues asking for new versions are sometimes annoying, and I apologize if this is one of them... but I'd really like to use the changes in #594 (82a5de08212ce5004d3bf2a923786ec4cb19b73b), which was merged a couple of months ago. #562 has been sitting for a little longer than that.

Is there anything that I/we can do to help get a new version published to npm? ❤️

**Comment by DavidAnson** [comment]
Sorry, I'm close but still hoping to drive to 0 open issues for the next release. Various PRs have taken time I'd otherwise have spent on this. The upcoming holiday period will hopefully give me an opportunity to wrap this up.

**Comment by DavidAnson** [comment]
Here's an easy one: I'd like someone to verify this change correctly interoperates with Prettier and add the missing `ol_single` parameter to the example: https://github.com/DavidAnson/markdownlint/commit/cc701ea70023ce172883e916c9ec91ffc940d8e9

A new unit test for Prettier interoperability might be nice, but I do not want to add a dependency on that project. It is probably enough to make the one-line edit to the sample.

**Comment by DavidAnson** [comment]
Note to self: Improve MD011/MD013/MD022/MD031/MD032/MD033/MD034/MD040/MD043/MD051/MD053, generate/separate documentation, improve documentation, update dependencies.

**Comment by JoshuaKGoldberg** [comment]
🎉 Hooray! Thanks!
