### ISSUE TITLE
Comments not supported

### ISSUE THREAD

**Issue by PrincessColumbia** [DavidAnson/markdownlint#671]
Probably more of a feature request as this can probably be set as a custom rule;

# Comments in markdown not supported

Per the [Markdown Guide](https://www.markdownguide.org/hacks/#comments), comments can be added to a markdown file using the following syntax:
`[comment]: #`

Example:
`[Added to published site 12/07/2022 11:07 am]: #`

However, markdownlint throws an error:
> `MD053/link-image-reference-definitions: Link and image reference definitions should be needed [Unused link or image reference definition: "added to published site 12/07/2022 11:07 am"]markdownlint[MD053](https://github.com/DavidAnson/markdownlint/blob/v0.26.2/doc/Rules.md#md053)`

As this has been tested and peer reviewed, having the definition in the extension by default would be ideal.

Non-critical feature request, issue can be closed if no further feedback needed from me.

**Comment by DavidAnson** [comment]
There is another hack for this which is fairly popular and is already supported.

Context here: <https://github.com/DavidAnson/markdownlint/issues/545>

Documentation here: <https://github.com/DavidAnson/markdownlint/blob/next/doc/md053.md>

I think this is a clearer approach than the one you reference and don’t see a need to support both.
