### ISSUE TITLE
Showing a warning about url encoded special characters when linking to headings

### ISSUE THREAD

**Issue by Breigner01** [DavidAnson/markdownlint#676]
So basically I have something like this in a markdown:

```
- [Build & Run](#build-%26-run)

# Build & Run
```

Which looks something like this:

- [Build & Run](#build-%26-run)

# Build & Run

I first realized that I couldn't use the ampersand character in the link but encoding it for URL works.
The slight "issue" if we can say so, is that markdownlint shows a warning because it thinks the link is not right but the markdown preview plugin that I'm using rightfully redirects to the right heading.

It would be nice to see this plugin interpret URL-encoded characters.

**Comment by DavidAnson** [comment]
MD051 enforces the GitHub algorithm as described here: <https://github.com/DavidAnson/markdownlint/blob/next/doc/md051.md>

That algorithm removes punctuation which leads to:

```markdown
# Build & Run

- [Build & Run](#build--run)
```

Which produces no errors when linted: <https://dlaa.me/markdownlint/#%25m%23%20Build%20%26%20Run%0A%0A-%20%5BBuild%20%26%20Run%5D(%23build--run)%0A>
