### ISSUE TITLE
Improve discoverability of changelog

### ISSUE THREAD

**Issue by bmish** [DavidAnson/markdownlint#694]
Currently, there's a changelog called "History" at the bottom of the README:

* https://github.com/DavidAnson/markdownlint/blob/main/README.md#history

This is lacking in discoverability when many/most repositories use a standard `CHANGELOG.md` file as well as GitHub releases to announce releases. These standard mechanisms have benefits like:
* Easier to find
* Consumable by tooling (like Dependabot which can then display the changelog in update PRs)
* Can be subscribed to for updates (in the case of GitHub releases)
* Maintainable by a myriad of automated release tools like release-it 

What do you think?

Note: Even if you don't want to switch the format, even just including the word "changelog" somewhere could make it easier to search for it, or a table of contents at the top of the README like the one generated by [this](https://marketplace.visualstudio.com/items?itemName=joffreykern.markdown-toc) VSCode extension.

**Comment by DavidAnson** [comment]
I'm fine with CHANGELOG.md (I use it for the VS Code extension), but I find GitHub Releases redundant. npm is the authority for what releases are available and what is in each; tags provide information about commits in the repo.

**Comment by bmish** [comment]
Got it. I'll open up a PR for this in a moment.

**Comment by DavidAnson** [comment]
Great, thank you! Please copy the content over as it is and link to it from the README. Please also add the new file to the handful of test cases that analyze Markdown files in the repository. Remember to PR against "next" branch.
