### ISSUE TITLE
MD034 false positive for links with whitespaces enclosed in angle brackets

### ISSUE THREAD

**Issue by NomarCub** [DavidAnson/markdownlint#707]
Here's an example that should be completely valid, yet gets a warning for MD034 (`no-bare-urls`): `[blue jay](<https://en.wikipedia.org/wiki/Blue jay>)`.
The quick fix recommended by the VSCode plugin is also wrong, it would turn it into this: `[blue jay](<<https://en.wikipedia.org/wiki/Blue> jay>)`

![image](https://user-images.githubusercontent.com/5298006/213787316-aa31c3a2-bb93-4bbb-8eb6-e361614e2de7.png)

**Comment by nschonni** [comment]
It is a bad fix/error, but the actual URL should have an underscore instead of space, because that is what Wikipedia actually servers https://en.wikipedia.org/wiki/Blue_jay
Unescaped spaces generally aren't actually valid URLs, and should be replaced with `%20` if they're actually needed

**Comment by NomarCub** [comment]
I know that's not what Wikipedia serves, and about the %20 replacement. I made the link up for easy demonstration, and my version should still be valid, as Markdown implementations (such as CommonMark) and browsers support it.

**Comment by NomarCub** [comment]
When can I expect this to make it into the VSCode plugin too?

**Comment by DavidAnson** [comment]
In a few weeks, thanks!
