### ISSUE TITLE
MD009 I can't set br_space parameter

### ISSUE THREAD

**Issue by daltonbr** [DavidAnson/markdownlint#71]
I am trying to set `br_spaces` to 2 to insert an explicit **line break**/br element, as suggested here at [MD009 documentation](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md009)

Is my syntax wrong? Thanks for this awesome extension!
```
"markdownlint.config": {"MD009": 2, false}  // not working
"markdownlint.config": {"MD009": false}     // working...not ideal tough
```

**Comment by DavidAnson** [comment]
This is the correct syntax: https://github.com/DavidAnson/markdownlint/blob/master/test/trailing_spaces_br.json

**Comment by daltonbr** [comment]
Thank you so much @DavidAnson 
Have a nice day Sir!
