### ISSUE TITLE
Is prettier redundant if I use markdownlint?

### ISSUE THREAD

**Issue by astier** [DavidAnson/markdownlint#716]
Hi. I am using markdownlint and it works great. Does it make sense to use prettier additionally to markdownlint or is it redundant? Are there case which prettier covers which markdownlint doesn't?

I read that some rules might conflict between prettier and markdownlint. Do I have to include to my `markdownlint` config-file

```
"extends": "markdownlint/style/prettier.json"
```
or is the following enough?

```
"extends": "prettier.json"
```

Thank you.

**Comment by DavidAnson** [comment]
It's not hard to interoperate with prettier. Here is a bit of documentation to help with that: https://github.com/DavidAnson/markdownlint/blob/main/doc/Prettier.md

I don't have an opinion about whether you should or shouldn't combine the two. It's really about what rules are important to you and whether one or the other of these tools is adequate or whether they each have something to offer you.

**Comment by nschonni** [comment]
Prettier can be helpful in doing formatting work on things like the frontmatter or inside code fences. That's how it's used in conjunction with Markdownlint in mdn/content.

**Comment by astier** [comment]
Thanks.
