### ISSUE TITLE
Why discussion tab is not enabled?

### ISSUE THREAD

**Issue by ImBIOS** [DavidAnson/markdownlint#723]
# 🤔 I have a question

Does markdownlint support MDX? I encounter a lot of warnings when opening an MDX file or an MD file with an HTML tag.

# ✅ I recommend

Please enable the discussion tab so we can ask and answer questions like this in a better place, I'd happy to help if you @DavidAnson need any help.

**Comment by DavidAnson** [comment]
MDX is not supported. I recommend performing linting on the final Markdown content.

Regarding Discussions, I have not used it but looking over it now, there seems to be a lot of overlap with Issues and I'd worry it causes people confusion about where to post.

**Comment by ImBIOS** [comment]
I understand your point, but if the issues tab is also used to ask questions or open discussions, it will be more challenging to distinguish which problems need to be worked on and which are still being discussed with the community because they are mixed.

Isn't it nice to see the number of issues dropping and letting the discussion continue freely in the discussion tab?

People wouldn't be confused if they slowly adapted to this culture. We direct them to the discussion when it's discussion and direct them to issues if the information should be tracked and worked on.

Let me know what you think.

**Comment by DavidAnson** [comment]
I don't think this solves a problem I've seen. I expect to leave Discussions disabled (the default) for now.
