### ISSUE TITLE
Exception when calling forEachHeading

### ISSUE THREAD

**Issue by mrsrhodehum** [DavidAnson/markdownlint#759]
Looks like markdownlint-cli2 version 0.6.0 is not compatible with markdownlint-rule-helpers version 0.19.0. When trying to call forEachHeading from a custom markdownlint rule:

```
"function": function rule(params, onError) {
        forEachHeading(params, (heading) => {
```

I got the following exception:

`Exception has occurred: TypeError: Cannot read properties of undefined (reading 'markdownit')`

**Comment by DavidAnson** [comment]
I don't understand. If you are getting an exception from custom rule code, why do you think that is an issue with markdownlint-cli2? If the custom rule does not work with the latest version of markdownlint-rule-helpers, it should reference an earlier version in package.json.
