### ISSUE TITLE
Allow declaring rules in a config within a "rules" object

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [DavidAnson/markdownlint#78]
A lot of other linters ask that rule settings be declared in a rules object so that configurations are separate:

```json
{
    "extends": ["tslint:all"],
    "rules": {
        "terrible-rule": false
    }
}
```

Can this project allow the same? The logic would be that if the object is present, it's merged with the base one.

**Comment by DavidAnson** [comment]
Please see the documentation for `extends` here:
https://github.com/DavidAnson/markdownlint/blob/master/README.md#optionsconfig

**Comment by DavidAnson** [comment]
Please reopen if `extends` doesn't cover your scenario.
