### ISSUE TITLE
<a href="https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18915764/3678731/17004/#/?version=2"><img src="https://s3.amazonaws.com/cla-project-logo-prod/cla-not-signed.svg" alt="CLA Not Signed" align="left" height="28" width="328"></a><br/><br /><ul><li><a href='https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18915764/3678731/17004/#/?version=2' target='_blank'>:x:</a> - login: @A-2f . The commit (62693f4f11e787e876ee0986110ee1ae1092245c) is not authorized under a signed CLA. <a href='https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18915764/3678731/17004/#/?version=2' target='_blank'>Please click here to be authorized</a>. For further assistance with EasyCLA, <a href='https://jira.linuxfoundation.org/servicedesk/customer/portal/4' target='_blank'>please submit a support request ticket</a>.</li></ul>

### ISSUE THREAD

**Issue by A-2f** [DavidAnson/markdownlint#780]
<a href="https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18915764/3678731/17004/#/?version=2"><img src="https://s3.amazonaws.com/cla-project-logo-prod/cla-not-signed.svg" alt="CLA Not Signed" align="left" height="28" width="328"></a><br/><br /><ul><li><a href='https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18915764/3678731/17004/#/?version=2' target='_blank'>:x:</a> - login: @A-2f . The commit (62693f4f11e787e876ee0986110ee1ae1092245c) is not authorized under a signed CLA. <a href='https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18915764/3678731/17004/#/?version=2' target='_blank'>Please click here to be authorized</a>. For further assistance with EasyCLA, <a href='https://jira.linuxfoundation.org/servicedesk/customer/portal/4' target='_blank'>please submit a support request ticket</a>.</li></ul>

_Originally posted by @linux-foundation-easycla in https://github.com/webpack/webpack/pull/17004#issuecomment-1510559610_

**Comment by DavidAnson** [comment]
SPAM
