### ISSUE TITLE
Sort failure outputs within a file instead of by rule?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [DavidAnson/markdownlint#79]
![image](https://user-images.githubusercontent.com/3335181/31865779-1c9d76ec-b729-11e7-89c2-acd8b2f2b9a6.png)

When I get a bunch of failure reports, my behavior is to go to the file and fix them in reverse order (so line numbers are preserved). It's pretty inconvenient to have them grouped by rule and therefore out of order. Can the default be to sort by line number?

**Comment by DavidAnson** [comment]
This is a package to find issues. It does not render the results. Feedback on rendering is best directed at one of the tools that present results in the UI or CLI:
https://github.com/DavidAnson/markdownlint/blob/master/README.md#related
