### ISSUE TITLE
Rule request: one sentence per line

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [DavidAnson/markdownlint#81]
A lot of markdown commits are small corrections such as spelling or grammar fixes. Having multiple sentences in a line increases the git commit diff size for these smaller fixes. It's good to follow all sentence-ending periods with an endline to reduce the chance of conflicts.

For documentation that tends towards long sentences, this can be a good alternative to strict line lengths.

**Comment by DavidAnson** [comment]
Great idea! This is a pattern I try to follow myself.

**Comment by KvanTTT** [comment]
Also, I suggest an 80-line string length pattern (80 can be changed to another custom value).

**Comment by DavidAnson** [comment]
@KvanTTT That exists: https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md013

**Comment by KvanTTT** [comment]
Cool! This was not working for me: disabled in VSCode extension by default :)

**Comment by DavidAnson** [comment]
Closing as duplicate of #66.
