### ISSUE TITLE
Support underlining style via `_` (underscores) and italics via `*` (asterisks) simultaneously

### ISSUE THREAD

**Issue by redactedscribe** [DavidAnson/markdownlint#810]
[Regarding MD049](https://github.com/DavidAnson/markdownlint/blob/main/doc/md049.md): The only options are `asterisk` / `consistent` / `underscore`. If we could have a `mixed` or `off` option, we could use `*` for emphasis (italicisation) and `_` for underlining without markdownlint complaining that we have inconsistent emphasis styling in play. This however would give up the checks we have for emphasising which isn't ideal.

Maybe some specific support could be given to underlining so that markdownlint could ensure we're using asterisks for emphasis and underscores for underlining? I don't know how common support for underlining in Markdown parsers is, but the [Markdown Extended VS Code extension](https://marketplace.visualstudio.com/items?itemName=jebbs.markdown-extended) enables support for it (via something called markdown-it I think) and it would be cool if markdownlint could support underlining too.

Thanks.

markdownlint 0.50.0

**Comment by nschonni** [comment]
"Underlining" isn't part of CommonMark spec https://spec.commonmark.org/0.30/. There asterisks and underscore both produce `<em>` elements only in compliant parsers

**Comment by DavidAnson** [comment]
Agreed. This behavior is not per specification (the plug-in agrees: https://www.npmjs.com/package/markdown-it-underline) and it would be confusing to try to support it for this one isolated case.

**Comment by redactedscribe** [comment]
I'm not educated enough on the details to argue otherwise so I'll have to agree. I thought it may be common among other parsers etc. Feel free to close if this is clear-cut.

**Comment by redactedscribe** [comment]
Another thought: Since underlining via underscore would just render as emphasised text in parsers which don't handle underscores vs asterisks differently, with an `off` option for MD049, we could at least use both styles in VS Code via Markdown Extended without markdownlint complaining, even if the linter won't support it specifically.
