### ISSUE TITLE
[Feature] Global config

### ISSUE THREAD

**Issue by AesthetiCoder** [DavidAnson/markdownlint#825]
it will be nice to have a global configuration and then a locla configuration for a project, this method is common in eslitn when you set a config file in your root or home direcory of the machine like `~/` for linux and `C:\Users\{ user }` for windows, here we can have a file for `.markdownlint.json` and have a global config for all the repos, if for some reason i need to change in a repo the rules, i just create another config file in the root of the directory and this rules are overrired

**Comment by DavidAnson** [comment]
As a library, you can fetch configuration from wherever you want when calling the API. If you are using one of the CLIs, `.markdownlint.json` supports "~" in `extends` paths which can be used to reference the user's home directory in the usual manner. This should allow the behavior you describe.

**Comment by AesthetiCoder** [comment]
Thanks, yes this works, still I have to create a file in every project but for now works, it will be nice to avoid that and also there can be problems in a team when a new member download the repo he will no have the file in his home directory, is there a way to create a repo with a custom config and extended ?

**Comment by DavidAnson** [comment]
You may be able to use a template in GitHub or scaffold with something like Yeoman. Anything like that would be out of scope for this project, though.
