### ISSUE TITLE
Consider using TypeScript or similar for newer ES features

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [DavidAnson/markdownlint#84]
+1 to using TypeScript in particular, but anything like it or Babel would be nice.

**Comment by DavidAnson** [comment]
I prefer to avoid compilation for the core scripts. I’ve used Babel in the past and found it to be big and slow. Keeping the code on ES5 makes supporting older Node versions easy. If/when that change, I’d look at moving to ES6 directly (no compiler).

**Comment by JoshuaKGoldberg** [comment]
> Babel

Have you tried TypeScript? `tsc -w` is pretty speedy. :)

**Comment by DavidAnson** [comment]
We use TS->ES5 at my day job. :) It sounds better than Babel, but still adds complexity/dependencies.

**Comment by DavidAnson** [comment]
Commit 18125a1872df8f5551ae81734e1d2627d6783586 updates supported Node versions to 6+, supporting most new ES features (http://node.green/).
Commit 78c1af7bfd89b32fb531db20bc5f9b158d51ee2d adds TypeScript to the demo script to maintain ES3 support for older browsers.
