### ISSUE TITLE
Consider using JSDoc-style function annotations everywhere

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [DavidAnson/markdownlint#85]
Editors like Atom and VS Code will give better experiences when functions declare what their input and output types are.

Now:

![image](https://user-images.githubusercontent.com/3335181/32150490-ef7901e2-bcd0-11e7-901f-043a28bfa9a3.png)

With proper JSDoc:

![image](https://user-images.githubusercontent.com/3335181/32150497-12c988ba-bcd1-11e7-9f10-e317003da7e6.png)

**Comment by DavidAnson** [comment]
I do so for public functions, see `function markdownlint` for example. I have a note to look into `// @ts-check` (https://code.visualstudio.com/docs/languages/javascript) which would complement this for private functions.

**Comment by JoshuaKGoldberg** [comment]
> public functions

👍. Title changed.
