### ISSUE TITLE
MD005 - Fixable rules must set the `meta.fixable` property

### ISSUE THREAD

**Issue by Celtech** [DavidAnson/markdownlint#899]
Seems to be missing the meta.fixable key

<img width="1072" alt="image" src="https://github.com/DavidAnson/markdownlint/assets/7949140/f8613553-9098-42d4-8b41-b0af0870f312">

**Comment by DavidAnson** [comment]
That error message looks to be coming from ESLint: https://github.com/eslint-community/eslint-plugin-eslint-plugin/blob/main/docs/rules/require-meta-fixable.md

Therefore, it is probably trying to report an issue with the eslint-plugin-markdownlint plugin which is a separate project written by someone else: https://gitlab.com/pawelbbdrozd/eslint-plugin-markdownlint
