### ISSUE TITLE
markdownlint-rule-helpers: provide an option to treat `<code>` tag content as code

### ISSUE THREAD

**Issue by OnkarRuikar** [DavidAnson/markdownlint#914]
We have a situation where we want to display strings with non breaking spaces and multiple blank spaces in HTML tables to demo JS regular expression stuff.

Following is a bare minimum sample:
```md
## Example

Matching strings with multiple spaces.

<table>
  <tr>
    <th>Strings</th>
  </tr>
  <tr>
    <td>
      <code>apple&nbsp;&nbsp;mango</code>
    </td>
  </tr>
</table>
```
We have to use HTML because Markdown doesn't have non breaking space character and also multiple spaces inside markdown inline code spans get collapsed (`apple<space><space>mango`).

We are removing `&nbsp;` characters in Markdown text using a custom rule and we don't want to remove it from code fences, code spans, and `<code>` tags. But current helper API doesn't provide a way to consider `<code>` tags. Is it possible to provide an option to consider text inside `<code>` HTML tags as a code span in `helpers.codeBlockAndSpanRanges(params, lineMetadata)` method?

https://github.com/DavidAnson/markdownlint/blob/d01180ec5a014083ee9d574b693a8d7fbc1e566d/helpers/helpers.js#L561C16-L571

**Comment by DavidAnson** [comment]
HTNL entities are valid Markdown, so this is legal and seems to do what you want without anything fancy: https://dlaa.me/markdownlint/#%25m%23%20Issue%20914%0A%0Aapple%26nbsp%3B%26nbsp%3Bmango%0A

Helpers is unsupported and I'd rather not make changes for non-core scenarios. Additionally, the function you identify is rooted in how I integrate with the markdown-it parser and I am very slowly moving away from that toward micromark.
