### ISSUE TITLE
How to fix everything what is possible when using a files option?

### ISSUE THREAD

**Issue by jcubic** [DavidAnson/markdownlint#927]
How to fix what is possible when using `default: true`? Do I need to duplicate every single rule to add fixInfo? There should be a way to make it fix what it can by default.

I've found this issue #663 but I'm not sure how to use this API if I have this config:

```javascript
const options = {
  'files': process.argv.slice(2),
  'config': {
    'default': true,
    'line-length': {
      'heading_line_length': 100,
      'line_length': 100,
      'code_block_line_length': 100,
    },
  },
};

const fixResults = markdownlint(options, function callback(err, result) {
  if (!err) {
    console.log(result.toString());
    process.exit(1);
  }
});

markdownlintRuleHelpers.applyFixes(options, fixResults.content);
```

It seems that `markdownlintRuleHelpers.applyFixes` requires `{ content: string }` but I have a file.

I've also tried this:

```javascript
const { sync: markdownlint }  = require('markdownlint');
const markdownlintRuleHelpers = require('markdownlint-rule-helpers');

const fixResults = markdownlint(options, function callback(err, result) {
  if (!err) {
    console.log(result.toString());
    process.exit(1);
  }
});

markdownlintRuleHelpers.applyFixes(options, fixResults.content);
```

but this give an error:

```
./node_modules/markdownlint-rule-helpers/helpers.js:793
  const endings = input.match(newLineRe) || [];
                        ^

TypeError: input.match is not a function
```

**Comment by jcubic** [comment]
So I was able to figure this out:

```javascript
const { sync: markdownlint }  = require('markdownlint');
const fs = require('fs/promises');
const { applyFixes } = require('markdownlint-rule-helpers');

const options = {
  'files': process.argv.slice(2),
  'config': {
    'default': true,
    'line-length': {
      'heading_line_length': 100,
      'line_length': 100,
      'code_block_line_length': 100,
    },
  },
};

const fixResults = markdownlint(options, function callback(err, result) {
  if (!err) {
    console.log(result.toString());
    process.exit(1);
  }
});


Object.entries(fixResults).forEach(([filename, rules]) => {
  if (rules.length) {
    fs.readFile(filename, 'utf8').then(content => {
      const output = applyFixes(content, rules);
      fs.writeFile(filename, output);
    });
  }
});
```

Do you want me to add this to docs? If yes then where I should add this code?

**Comment by DavidAnson** [comment]
Issue #663 that you link to gives context and references a commit that adds an explanation and an example to the documentation:

- https://github.com/DavidAnson/markdownlint#fixing
- https://github.com/DavidAnson/markdownlint/blob/main/helpers/README.md#applying-recommended-fixes

**Comment by DavidAnson** [comment]
Types for markdownlint's sync API are available here: https://github.com/DavidAnson/markdownlint/blob/d641caf90ca67660a1939e50f6cc8acb1939819f/lib/markdownlint.d.ts#L74

And described here: https://github.com/DavidAnson/markdownlint#usage

**Comment by jcubic** [comment]
Sorry, but it's not clear how to use your library from the docs. But If you don't care that your user will struggle (like I did) you can close the issue.

**Comment by jcubic** [comment]
Sorry, but I don't see documentation on how to call `applyFixes` with an output of `markdownlint`. As I said there are only docs how to call it with string.

**Comment by DavidAnson** [comment]
There is documentation to describe and demonstrate various ways of giving input into the tool as well as how to interpret the output, including fixing issues. There may not be an example that corresponds precisely to your scenario.

From what I can see above, what's missing is code to read and write each file. Those are standard Node APIs and examples exist in their documentation and elsewhere.
