### ISSUE TITLE
Why there are no binary/executable?

### ISSUE THREAD

**Issue by jcubic** [DavidAnson/markdownlint#928]
Why provide only the NodeJS module? This is a common thing to run the executable. In order to add lint to the pre-commit hook I need to create an executable. It would be much more useful if there was a binary.

The first thing I did after the installation was use `npx markdownlint` which give an error, next was searching node_module/.bin for the binary.

**Comment by DavidAnson** [comment]
Distributing the library as a standalone package along with another package for the command-line interface is a pretty common pattern in the Node.js ecosystem.

Regarding your workflow, if you are going to use NPX, then you do not need to also install the package.

As Nick points out, there are two CLI options for this library: a more traditional one (markdownlint-cli)and an alternative (markdownlint-cli2).

**Comment by jcubic** [comment]
Thanks for your quick response, I just assumed that those were similar but different projects.
