### ISSUE TITLE
Parsers are missing in the type definitions

### ISSUE THREAD

**Issue by JPeer264** [DavidAnson/markdownlint#929]
Parsers with following type have been introduced [here](https://github.com/DavidAnson/markdownlint/commit/1461ad6272ce4b67a87d27d1cc001c3f365260f9#diff-807e51fda288b4ebd0ccd4229d72a4c025f9b9316b0244ac45e76d8ff2317269R568):

```ts
parsers: {
  markdownit: { tokens: markdownit.Token[]  };
  micromark: { tokens: micromark.Token[] };
};
```

Types for:
- `markdownit.Token`: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/markdown-it/lib/token.d.ts#L8
- `micromark.Token`: https://github.com/DavidAnson/markdownlint/blob/main/helpers/micromark.cjs#L16

I could add a PR. But I am afraid I need to install `@types/markdown-it` into the dependencies to make them available for the type declarations. Unless there is a better way of doing this.

**Comment by DavidAnson** [comment]
markdown-it tokens are already defined in the .d.ts file: https://github.com/DavidAnson/markdownlint/blob/d641caf90ca67660a1939e50f6cc8acb1939819f/lib/markdownlint.d.ts#L139

micromark tokens and the micromark parser are not documented or referenced because they are not officially supported for use by plug-ins yet.

Is there something you think is missing?

**Comment by JPeer264** [comment]
Thanks for coming back that quickly. The main reason why I came up with this issue is that we're writing our own custom rules (and we're using typescript for it). Unfortunately, we took advantage of the undocumented, yet [officially exported](https://github.com/DavidAnson/markdownlint/blob/d641caf/package.json#L9 ), [helpers file](https://github.com/DavidAnson/markdownlint/blob/d641caf90ca67660a1939e50f6cc8acb1939819f/helpers/helpers.js). 

Before we took the function `forEachInlineChild`, which got removed with the latest version: https://github.com/DavidAnson/markdownlint/commit/ef1bd286a9802e7242fc620a0b0a856df8b644b2#diff-77185aed1090adda14ba6426fa837ea81f1c778a03fb90761798f08c670ab484L455-L462. In a matter of fact, it got replaced with the not exported `filterByTypes` from `micromark.cjs` as [shown here](https://github.com/DavidAnson/markdownlint/commit/e8cc7eb3cb3e5f9f3a7276341e7c53ca302195ac#diff-8c61751df67014eedef463cbcc88590d10d4fffcf23c30f5f049f5f1a221e012R13-R28). 

As these things are all undocumented, it would be an excellent opportunity for us to move away from these features and use the types we actually have.

---

Since `parsers` are not officially supported, I guess these lines can be changed to `params.tokens` since these are the same types: https://github.com/DavidAnson/markdownlint/blob/main/doc/CustomRules.md#:~:text=params.parsers.markdownit.tokens
