### ISSUE TITLE
MD055: Table style consistency check

### ISSUE THREAD

**Issue by lloeki** [DavidAnson/markdownlint#93]
It would be nice to be able to enforce table style consistency:

```
| foo | bar |
|-----|-----|
| 123 | 456 |
```

vs

```
| foo | bar
|-----|----
| 123 | 456
```

vs

```
foo | bar
----|----
123 | 456
```

Style could be detected as being inconsistent from first occurence, or globally enforced as a setting.

**Comment by StanzillaManticore** [comment]
Something like https://github.com/remarkjs/remark-lint/tree/master/packages/remark-lint-table-cell-padding would indeed be nice
