### ISSUE TITLE
'\' used to escape a '_' in the URL is invalid according to MD051

### ISSUE THREAD

**Issue by FlorentPoinsaut** [DavidAnson/markdownlint#956]
The '\' character used to escape a '_' character in the URL is invalid according to MD051.

Example : `[nfs](#module\_nfs)` is invalid

But if I try here, it is correctly interpreted: https://spec.commonmark.org/dingus/?text=%5Bnfs%5D(%23module_nfs)%20%0A&smart=1

Is this deliberate behaviour?
I'm wondering because this breaks compatibility with [terrafom-docs](https://terraform-docs.io/) and I'd like to know whether I should ask them to correct this or not :-D

**Comment by DavidAnson** [comment]
It should be unnecessary to escape the underscore in that scenario, but I need to look at the specifications to see if it's wrong to do so. I notice that the backslash is ignored in your example and by the markdown-it parser. I will look into this more when I'm not on my phone.

**Comment by DavidAnson** [comment]
It seems to be ignored by the micromark parser as well.

**Comment by DavidAnson** [comment]
CommonMark explicitly allows backslash escapes in link destinations: https://spec.commonmark.org/0.30/#example-22

**Comment by FlorentPoinsaut** [comment]
Thank you so much for your responsiveness and all your hard work!
