### ISSUE TITLE
how to add subscript or superscript 

### ISSUE THREAD

**Issue by noaRricky** [DavidAnson/markdownlint#96]
I use the tag <sup> to add superscript but the plugin shows it wrong.

**Comment by noaRricky** [comment]
``

**Comment by chandu-v** [comment]
> 
> 
> I use the tag sup to add superscript but the plugin shows it wrong.

Same here

**Comment by DavidAnson** [comment]
This is a linter, not a renderer. If something is not being displayed correctly, it has nothing to do with this tool.
