### ISSUE TITLE
MD007: Alternating fixes for nested list item definition (`* * item`)

### ISSUE THREAD

**Issue by UnkwUsr** [DavidAnson/markdownlint#969]
List item with heading extra asterisk makes `markdownlint` mad so it shifts this line right-left from run to run.

I know this is not valid markdown syntax, but it is strange to stuck in loop.

## Example

Original:

```
* * asd
```

After running `markdownlint --fix`:

```
  * * asd
```

After running `markdownlint --fix` (x2):

```
* * asd
```

**Comment by DavidAnson** [comment]
Fun! Did this start in a recent release? (I'd guess it was there for a while.)

https://dlaa.me/markdownlint/#%25m%23%20Issue%20969%0A%0A*%20*%20asd%0A

**Comment by DavidAnson** [comment]
This behavior is present in the first version of `markdownlint-cli2` that supported `--fix`, so it's at least 3 years old. (Not a new regression.)

`markdownlint-cli2 v0.0.13 (markdownlint v0.22.0)`
