### ISSUE TITLE
Make helpers in `micromark.cjs` available through `markdownlint-rule-helpers`

### ISSUE THREAD

**Issue by khiga8** [DavidAnson/markdownlint#994]
Our team is writing some custom rules for our projects. We would like to test these rules in our projects and upstream it here, if it makes sense.

I notice there are helpful methods available as an NPM package to support writing custom lint rules in [markdownlint-rule-helpers](https://github.com/DavidAnson/markdownlint/tree/main/helpers). 

I'm hoping to be able to use the `getHtmlTagInfo` and `filterByTypes` functions which are currently in `micromark.cjs`, but these don't appear to be available as part of the package.

I'd like to avoid repro-ing/copying this logic into our project -- would you be open to making these micromark functions available as part of [markdownlint-rule-helpers](https://github.com/DavidAnson/markdownlint/tree/main/helpers)?

**Comment by DavidAnson** [comment]
Quick history lesson for context:
- The `markdownlint-rule-helpers` package is unsupported and provided for convenience only
- Anything in that package related to the parser is going to work with the `markdown-it` parser
- I've been gradually migrating everything over to the `micromark` parser (which provides rich positional information) and didn't want to introduce any public dependencies on that until I felt more confident about what I'm doing 
- Once migrated, I hope to stop running the `markdown-it` parser except in the presence of custom rules which so far only have access to it (officially)
- I may even stop publishing `markdownlint-rule-helpers`
- Undocumented access to both parsers has been available to custom rules for a while now
- As recently as the current version, I am still tweaking some of the helpers in `micromark.cjs`

So I'm not sure I'd like to go down the road you outline... I'm open to suggestions, but propose that copying those two functions is reasonable at the current time.
